### ISSUE TITLE
sync-catalog: Consul to K8s:  cannot reach k8s FQDN's

### ISSUE THREAD

**Issue by GregHanson** [hashicorp/consul-k8s#10]
I deployed version  0.2.0 of consul-helm charts with service sync enabled.  I see the consul services in the `kubectl get svc` output but I can only `curl` them via their consul FQDN's (i.e. consul.service.consul) and not using the default k8s FQDN (consul.default.svc.cluster.local).  The Consul to Kubernetes section from official consul blog [here](https://www.hashicorp.com/blog/consul-and-kubernetes-service-catalog-sync) uses 
```
dig consul.default.svc.cluster.local
```
Does `dig` behave any different from `curl` for consul DNS resolution?  I have tried accessing the k8s FQDN's for consul services from inside other pods on IKS and locally with minikube and have not been able to get it to work.

**Comment by mitchellh** [comment]
Are you using CoreDNS instead of `kube-dns`? And did you setup the Consul DNS? This is currently a requirement as noted here: https://www.consul.io/docs/platform/k8s/service-sync.html#consul-to-kubernetes. CoreDNS is on its way to becoming the default for K8S, hence they aren't fixing the bug that forces this in `kube-dns`.

**Comment by GregHanson** [comment]
@mitchellh I was following the DNS steps listed here: https://www.consul.io/docs/platform/k8s/dns.html

I created the following configmap:
```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {"consul": ["$(kubectl get svc consul-dns -o jsonpath='{.spec.clusterIP}')"]}
EOF
```
Was there another step needed ?
