### ISSUE TITLE
Upstream request timeout on consul connect(envoy) with helm chart

### ISSUE THREAD

**Issue by sesakki** [hashicorp/consul-k8s#1021]
### Service Defaults & Proxy Default

I did set proxy defaults with vaule
```
apiVersion: consul.hashicorp.com/v1alpha1
kind: ProxyDefaults
metadata:
  name: global
spec:
  config:
    local_connect_timeout_ms: 1000000
    handshake_timeout_ms: 1000000
    local_request_timeout_ms: 1000000
```
I did add upstream config in service defaults
```
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: web
spec:
  protocol: "http"
  transparentProxy:
    dialedDirectly: true
  upstreamConfig:
    defaults:
      connectTimeoutMs: 1000000
      limits:
        maxConnections: 10
      passiveHealthCheck:
        interval: 3s
        maxFailures: 5
```
But above settings are not working.

Consul version v1.11.1
Consul chart version consul-0.39.0
Deployed on AKS

### Helm Configuration

```
global:
  name: consul
  datacenter: dc1
  tls:
    enabled: false
    enableAutoEncrypt: false
    verify: false
server:
  replicas: 1
client:
  enabled: true
controller:
  enabled: true
  default: true
syncCatalog:
  enabled: true
  toConsul: true
  toK8S: true
  default: true
connectInject:
  enabled: true
  default: false
ui:
  enabled: true
  service:
    enabled: true
```

### Logs

`kubectl get proxydefaults global -n martserver`

```
NAME     SYNCED   LAST SYNCED   AGE
global   True     3d23h         4d3h

```
is there a way to change default envoy connect timeout?
