### ISSUE TITLE
How to configure envoy max streams limit?

### ISSUE THREAD

**Issue by FelipeEmerim** [hashicorp/consul-k8s#1036]
#### Question

We are having a problem using consul with websockets. If we have about +1024-1100 open websocket connections at the same time, envoy starts dropping new incoming connections. Because of that our healthchecks (kafka ping) start failing and the service becomes unreachable.

We tried changing `upstreamConfig.defaults.limits` in service defaults and, while that changed the behavior for HTTP traffic, TCP streams remained unchanged.

If we remove the envoy sidecar from the pods it starts accepting as many connections as it can.

Is there a way to increase the concurrent stream limit on envoy?

### Helm Configuration
```yaml
# consul-values.yaml   -- Consul Helm Chart Values
global:
  name: consul
  datacenter: local
  logLevel: "error"
  logJSON: true
  metrics:
    enabled: true
    enableAgentMetrics: true
  consulSidecarContainer:
    resources:
      requests:
        memory: "50Mi"
        cpu: "20m"
      limits:
        cpu: 100m
        memory: 256Mi
  tls:
    enabled: true
    enableAutoEncrypt: true
    verify: true
    httpsOnly: false
    serverAdditionalDNSSANs:
  
      - "consul-server.consul.svc.cluster.local"      
  
server:
  replicas: 3
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  securityContext:
    runAsNonRoot: false
    runAsUser: 0  
  extraConfig: |
    {
      "log_level": "error",
      "ui_config": {
        "dashboard_url_templates": {
          "service": "https://grafana"
        }
      }
    }
  nodeSelector: |
    dedicated-to: sre
  tolerations: |
    - key: dedicated-to
      value: sre
      effect: NoSchedule
      operator: Equal
client:
  resources:
    requests:
      memory: "500Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  tolerations: |
    - key: dedicated-to
      effect: NoSchedule
      operator: Exists
  extraConfig: |
    {
      "log_level": "ERROR"
    }
ui:
  enabled: true
  service:
    type: "ClusterIP"
  metrics:
    baseURL: http://prometheus-server.monitoring.svc.cluster.local
controller:
  enabled: true
  replicas: 2
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 200Mi
  nodeSelector: |
    dedicated-to: sre
  tolerations: |
    - key: dedicated-to
      value: sre
      effect: NoSchedule
      operator: Equal
prometheus:
  enabled: false
acls:
  manageSystemACLs: false
connectInject:
  
  enabled: true
  
  default: false
  envoyExtraArgs: "--log-level error"
  resources:
    requests:
      cpu: 125m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
  sidecarProxy:
    resources:
      requests:
        cpu: 125m
        memory: 128Mi
      limits:
        cpu: 125m
        memory: 128Mi
  nodeSelector: |
    dedicated-to: sre
  tolerations: |
    - key: dedicated-to
      value: sre
      effect: NoSchedule
      operator: Equal
syncCatalog:
  
  enabled: true
  
  default: false
  
  toConsul: true
  
  toK8S: false
  k8sAllowNamespaces: ["*"]
  addK8SNamespaceSuffix: true
  
  logLevel: "error"
  nodeSelector: |
    dedicated-to: sre
  tolerations: |
    - key: dedicated-to
      value: sre
      effect: NoSchedule
      operator: Equal
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "100m"
webhookCertManager:
  tolerations: |
    - key: dedicated-to
      value: sre
      effect: NoSchedule
      operator: Equal
```

### Steps to reproduce this issue

1. Create a simple socket.io application using transport: ['websocket'];
2. Run a script that opens more than 1024-1100 * "number of replicas" concurrent connections;
3. Check that after some time new connections will start dropping;
4. After stopping the script, the service becomes reachable again;
5. Restart the pod with connect-inject: false and run the script again;
6. Check that connections are not dropped.

### Logs

The only log we could relate to this problems is below:

```
[2022-02-16 19:42:27.155][15][debug][pool] [source/common/conn_pool/conn_pool_base.cc:239] [C5221] using existing connection
[2022-02-16 19:42:27.155][15][debug][pool] [source/common/conn_pool/conn_pool_base.cc:170] max streams overflow
[2022-02-16 19:42:27.155][15][debug][router] [source/common/router/router.cc:1130] [C5228][S6567386237767641786] upstream reset: reset reason: overflow, transport failure reason: 
[2022-02-16 19:42:27.155][15][debug][http] [source/common/http/filter_manager.cc:947] [C5228][S6567386237767641786] Sending local reply with details upstream_reset_before_response_started{overflow}
[2022-02-16 19:42:27.155][15][debug][http] [source/common/http/conn_manager_impl.cc:1412] [C5228][S6567386237767641786] closing connection due to connection close header
[2022-02-16 19:42:27.155][15][debug][http] [source/common/http/conn_manager_impl.cc:1467] [C5228][S6567386237767641786] encoding headers via codec (end_stream=false):
```

### Current understanding and Expected behavior

- We think envoy is blocking connections because when we remove the sidecar, we cannot reproduce the problem. 
- We thought circuit breaker could be causing the issue, but after altering service defaults upstream limits, only HTTP traffic was affected.
- Every stream is affected, websocket connections, kafka connections, etc. We found that out because our healthchecks ping kafka. They stop working when the stream limit is reached.
- During our testing we found that services which use the dialedDirectly feature (traefik) are unaffected by service defaults upstream limits, is this intended? Also the max stream limit seems to not affect traefik either.

### Environment details

- Kubernetes version: v1.20.9
- Cloud provider: Azure AKS
- Consul version: 1.11.1
- Networking CNI Plugin: Calico
