### ISSUE TITLE
manageSystemACLs doesn't make token required for Consul UI

### ISSUE THREAD

**Issue by goodoldneon** [hashicorp/consul-k8s#1040]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

When setting `global.acls.manageSystemACLs: true` in Helm values, Consul UI is accessible without a token.

Here's my full Helm values:

```yml
global:
  name: consul
  datacenter: hashidc1
  tls:
    enabled: true
  acls:
    manageSystemACLs: true
ui:
  enabled: true
  service:
    type: LoadBalancer
```

When I shell into one of the `consul-server` pods, I do see `"default_policy": "deny"`:

```
$ cat consul/config/acl-config.json
{
  "acl": {
    "enabled": true,
    "default_policy": "deny",
    "down_policy": "extend-cache",
    "enable_token_persistence": true
  }
}
```

So `acl-config.json` looks correct but I'm still able to access Consul UI without a token.

### Environment details

- Kubernetes version: v1.21.6-gke.1500
- Cloud Provider (If self-hosted, the Kubernetes provider utilized): GKE
