### ISSUE TITLE
Service default upstream default limits not applied to local_app envoy cluster

### ISSUE THREAD

**Issue by FelipeEmerim** [hashicorp/consul-k8s#1046]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

We are using consul-k8s in our setup with the envoy proxy. We have an issue with the circuit breakers, even if we configure the
service defaults upstream limits, the local_app cluster is not updated with the circuit breaker config. That is a problem on our services using websockets, because after opening 1024 + connections the service will go down and all probes will return 503 status code.

We only have this issue on services called by traefik, note that traefik dials our pods directly (each service has transparentProxy.dialedDirectly=true on their service defaults), so maybe that is the reason its connections count towards the local_app cluster limits.

### Reproduction Steps

1. Deploy traefik as shown [here](https://github.com/kschoche/traefik-consul) (it is on consul's docs);
2. Deploy a connect injected pod with probes, we used a simple socketio pod;
3. Configure an ingress to connect to that service using traefik;
4. Make more than 1024 to the deployed service;
5. Envoy will start rejecting connections and the probes will start returning 503 errors.

#### Consul helm

```yaml
# consul-values.yaml   -- Consul Helm Chart Values
global:
  name: consul
  datacenter: local
  logLevel: "error"
  logJSON: true
  metrics:
    enabled: true
    enableAgentMetrics: true
  consulSidecarContainer:
    resources:
      requests:
        memory: "50Mi"
        cpu: "20m"
      limits:
        cpu: 100m
        memory: 256Mi
  tls:
    enabled: true
    enableAutoEncrypt: true
    verify: true
    httpsOnly: false
    serverAdditionalDNSSANs:
  
      - "consul-server.consul.svc.cluster.local"      
  
server:
  replicas: 3
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  securityContext:
    runAsNonRoot: false
    runAsUser: 0  
  extraConfig: |
    {
      "log_level": "error",
      "ui_config": {
        "dashboard_url_templates": {
          "service": "https://grafana"
        }
      }
    }
  nodeSelector: |
    dedicated-to: sre
  tolerations: |
    - key: dedicated-to
      value: sre
      effect: NoSchedule
      operator: Equal
client:
  resources:
    requests:
      memory: "500Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  tolerations: |
    - key: dedicated-to
      effect: NoSchedule
      operator: Exists
  extraConfig: |
    {
      "log_level": "ERROR"
    }
ui:
  enabled: true
  service:
    type: "ClusterIP"
  metrics:
    baseURL: http://prometheus-server.monitoring.svc.cluster.local
controller:
  enabled: true
  replicas: 2
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 200Mi
  nodeSelector: |
    dedicated-to: sre
  tolerations: |
    - key: dedicated-to
      value: sre
      effect: NoSchedule
      operator: Equal
prometheus:
  enabled: false
acls:
  manageSystemACLs: false
connectInject:
  
  enabled: true
  
  default: false
  envoyExtraArgs: "--log-level error"
  resources:
    requests:
      cpu: 125m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
  sidecarProxy:
    resources:
      requests:
        cpu: 125m
        memory: 128Mi
      limits:
        cpu: 125m
        memory: 128Mi
  nodeSelector: |
    dedicated-to: sre
  tolerations: |
    - key: dedicated-to
      value: sre
      effect: NoSchedule
      operator: Equal
syncCatalog:
  
  enabled: true
  
  default: false
  
  toConsul: true
  
  toK8S: false
  k8sAllowNamespaces: ["*"]
  addK8SNamespaceSuffix: true
  
  logLevel: "error"
  nodeSelector: |
    dedicated-to: sre
  tolerations: |
    - key: dedicated-to
      value: sre
      effect: NoSchedule
      operator: Equal
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "100m"
webhookCertManager:
  tolerations: |
    - key: dedicated-to
      value: sre
      effect: NoSchedule
      operator: Equal
```

#### Traefik helm

```yaml
additionalArguments:
- --providers.file
- --providers.file.directory=/static
- --tracing.zipkin=true
- --tracing.zipkin.httpEndpoint=http://jaeger-collector.monitoring.svc.cluster.local:9411/api/v2/spans
- --providers.consulcatalog.connectAware=true
- --providers.consulcatalog.exposedByDefault=false
- --providers.consulcatalog.connectByDefault=true
- --providers.consulcatalog.servicename=traefik
- --providers.consulcatalog.endpoint.address=consul-server.consul.svc.cluster.local:8501
- --providers.consulcatalog.endpoint.scheme=https
- --providers.consulcatalog.endpoint.tls.ca=/certs/consul-ca/tls.crt
additionalVolumeMounts:
- mountPath: /tls-secret
  name: ssl
- mountPath: /static
  name: config
autoscaling:
  enabled: true
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 80
    type: Resource
  - resource:
      name: memory
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 2
deployment:
  additionalVolumes:
  - name: ssl
    secret:
      secretName: star-randon-tls
  - configMap:
      name: custom-traefik-config
    name: config
  initContainers: null
  podAnnotations:
    consul.hashicorp.com/connect-inject: "true"
    consul.hashicorp.com/enable-metrics-merging: "true"
    consul.hashicorp.com/transparent-proxy-exclude-inbound-ports: 80,443,8000,9000,8443
    consul.hashicorp.com/transparent-proxy-exclude-outbound-cidrs: 10.100.0.1/32
  replicas: 2
image:
  name: traefik
  tag: v2.5
ingressRoute:
  dashboard:
    annotations: {}
    enabled: false
    labels: {}
nodeSelector:
  dedicated-to: sre
persistence:
  accessMode: ReadWriteOnce
  annotations: {}
  enabled: false
  name: data
  path: /data
  size: 128Mi
podSecurityContext:
  fsGroup: 65532
ports:
  metrics:
    expose: false
    exposedPort: 9100
    port: 9100
    protocol: TCP
  traefik:
    expose: false
    exposedPort: 9000
    port: 9000
    protocol: TCP
  web:
    expose: true
    exposedPort: 80
    port: 8000
    protocol: TCP
  websecure:
    expose: true
    exposedPort: 443
    port: 8443
    protocol: TCP
    tls:
      domains:
      - main: '*.domain.com'
      enabled: true
      options: ""
resources:
  limits:
    cpu: 500m
    memory: 1000Mi
  requests:
    cpu: 200m
    memory: 500Mi
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532
service:
  annotations:
    consul.hashicorp.com/service-name: traefik
    consul.hashicorp.com/service-sync: "false"
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  enabled: true
  externalIPs: []
  labels: {}
  loadBalancerSourceRanges: []
  spec:
    loadBalancerIP: 10.39.40.25
  type: LoadBalancer
tolerations:
- effect: NoSchedule
  key: dedicated-to
  operator: Equal
  value: sre
volumes:
- mountPath: /certs/consul-ca/
  name: consul-ca-cert
  type: secret
```

### Logs

We find the following logs on envoy-sidecar when we have the problem:

```
[2022-02-16 19:42:27.155][15][debug][pool] [source/common/conn_pool/conn_pool_base.cc:239] [C5221] using existing connection
[2022-02-16 19:42:27.155][15][debug][pool] [source/common/conn_pool/conn_pool_base.cc:170] max streams overflow
[2022-02-16 19:42:27.155][15][debug][router] [source/common/router/router.cc:1130] [C5228][S6567386237767641786] upstream reset: reset reason: overflow, transport failure reason: 
[2022-02-16 19:42:27.155][15][debug][http] [source/common/http/filter_manager.cc:947] [C5228][S6567386237767641786] Sending local reply with details upstream_reset_before_response_started{overflow}
[2022-02-16 19:42:27.155][15][debug][http] [source/common/http/conn_manager_impl.cc:1412] [C5228][S6567386237767641786] closing connection due to connection close header
[2022-02-16 19:42:27.155][15][debug][http] [source/common/http/conn_manager_impl.cc:1467] [C5228][S6567386237767641786] encoding headers via codec (end_stream=false):
```

### Expected behavior

I expected the service defaults limits to be applied to the local_app cluster.

### Environment details

- Kubernetes version: v1.20.9
- Cloud provider: Azure AKS
- Consul version: 1.11.1
- Networking CNI Plugin: Calico

#### Related issues
- https://github.com/hashicorp/consul/issues/12373
- https://github.com/envoyproxy/envoy/issues/20020
- https://github.com/hashicorp/consul/issues/7211

#### Things we tried

To make sure the local_app cluster was the problem we used envoy admin endpoints, we can see in the config_dump endpoint that the circuit breakers were not applied, and in the stats_dump that the overflow counter is increased for the local_app cluster. The other clusters had the circuit breaker correctly configured and their overflow counter was 0.

```jsonc
//config dump local app cluster
{
    "version_info": "25f00611228c29a0e12ab6a09c01822b735f910d0aedd4d8cd6ed1b6f28f99e8",
    "cluster": {
        "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
        "name": "local_app",
        "type": "STATIC",
        "connect_timeout": "5s",
        "load_assignment": {
            "cluster_name": "local_app",
            "endpoints": [
                {
                    "lb_endpoints": [
                        {
                            "endpoint": {
                                "address": {
                                    "socket_address": {
                                        "address": "127.0.0.1",
                                        "port_value": 3000
                                    }
                                }
                            }
                        }
                    ]
                }
            ]
        }
    },
    "last_updated": "2022-02-22T12:06:13.618Z"
}
```

```jsonc
// connection overflow in stats
{
      "name": "cluster.local_app.upstream_cx_overflow",
      "value": 17
}
```

We tried using the `envoy_local_cluster_json` escape hatch to manually add the circuit breaker config to the local_app cluster. However, we could not find a way to add a dynamic service port. A static port does not work because our services run in different ports. This is the proxy-defaults we were trying to apply:

```yaml
apiVersion: consul.hashicorp.com/v1alpha1
kind: ProxyDefaults
metadata:
  name: global
  namespace: consul
spec:
  config:
    envoy_local_cluster_json: "{\"@type\":\"type.googleapis.com/envoy.config.cluster.v3.Cluster\",\"name\":\"local_app\",\"type\":\"STATIC\",\"connect_timeout\":\"5s\",\"circuit_breakers\":{\"thresholds\":[{\"max_connections\":10000000,\"max_pending_requests\":10000000,\"max_requests\":10000000}]},\"load_assignment\":{\"cluster_name\":\"local_app\",\"endpoints\":[{\"lb_endpoints\":[{\"endpoint\":{\"address\":{\"socket_address\":{\"address\":\"127.0.0.1\",\"port_value\":3000}}}}]}]}}\n"
  transparentProxy:
    dialedDirectly: false
```

> **dialedDirectly** is false by default, we turn it on in each service's serviceDefaults.

If we could use escape hatches on serviceDefaults manifest or pass a dynamic port to the existing escape hatch, that would fix the problem for us. We tried using {{ .ServicePort }} as shown in a related issue, but later saw that the OP forked consul to make that work.

We opened this as a bug because we do not know if the behavior is intentional or not, maybe this could be a feature request to add a way of setting local_cluster's circuit breakers.
