### ISSUE TITLE
Helm Post Render with kustomize Custom Environment Variable Value

### ISSUE THREAD

**Issue by kholisrag** [hashicorp/consul-k8s#1147]
#### Question

Is the consul docker official image `hashicorp/consul:1.11.4`, can't evalute `$(eval cat ip.txt)` in the helm template `server-statefulset.yaml` `command:` section ?

### CLI Commands (consul-k8s, consul-k8s-control-plane, helm)

```
helm -n consul upgrade --install consul hashicorp/consul --version 0.42.0 -f ../consul_values.yaml --post-renderer ./kustomize --debug --atomic --timeout 2m --dry-run
```

### Helm Configuration

`consul_values.yaml`
<details>
  <summary>Helm Values!</summary>

```yaml
fullnameOverride: consul
global:
  enabled: true
  logLevel: "info"
  logJSON: false
  name: null
  domain: consul
  adminPartitions:
    enabled: false
  image: "hashicorp/consul:1.11.4"
  imagePullSecrets: []
  imageK8S: "hashicorp/consul-k8s-control-plane:0.42.0"
  datacenter: dc1
  enablePodSecurityPolicies: false
  secretsBackend:
    vault:
      enabled: false
      consulServerRole: ""
      consulClientRole: ""
      manageSystemACLsRole: ""
      agentAnnotations: null
      consulCARole: ""
      ca:
        secretName: ""
        secretKey: ""
      connectCA:
        address: ""
        authMethodPath: "kubernetes"
        rootPKIPath: ""
        intermediatePKIPath: ""
        additionalConfig: |
          {}
  gossipEncryption:
    autoGenerate: false
    secretName: "consul-gossip-encryption-key"
    secretKey: "key"
  recursors: []
  tls:
    enabled: true
    enableAutoEncrypt: true
    serverAdditionalDNSSANs: []
    serverAdditionalIPSANs: []
    verify: true
    httpsOnly: false
    caCert:
      secretName: null
      secretKey: null
    caKey:
      secretName: null
      secretKey: null
  enableConsulNamespaces: false
  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: null
      secretKey: null
    createReplicationToken: false
    replicationToken:
      secretName: null
      secretKey: null
  federation:
    enabled: false
  metrics:
    enabled: true
    enableAgentMetrics: true
    agentMetricsRetentionTime: 1m
    enableGatewayMetrics: true
  imageEnvoy: "envoyproxy/envoy-alpine:v1.20.2"
server:
  enabled: "-"
  image: null
  replicas: 3
  bootstrapExpect: null
  serverCert:
    secretName: null
  exposeGossipAndRPCPorts: true
  ports:
    serflan:
      port: 8301
  storage: 10Gi
  storageClass: null
  connect: true
  serviceAccount:
    annotations: null
  resources:
    requests:
      memory: "4000Mi"
      cpu: "1000m"
    limits:
      memory: "8000Mi"
      cpu: "2000m"
  securityContext:
    runAsNonRoot: true
    runAsGroup: 1000
    runAsUser: 100
    fsGroup: 1000
  containerSecurityContext:
    server: null
  updatePartition: 0
  disruptionBudget:
    enabled: true
  extraConfig: |
    {}
  extraVolumes:
    - load: true
      name: aws-public-ip
      type: emptyDir
  extraContainers: []
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: {{ template "consul.name" . }}
              release: "{{ .Release.Name }}"
              component: server
          topologyKey: kubernetes.io/hostname
  tolerations: |
    - key: "nomad-federation"
      operator: "Equal"
      value: "true"
      effect: "NoExecute"
  topologySpreadConstraints: ""
  nodeSelector: |
    nomad-servers: nomad-federation-001
  priorityClassName: ""
  extraLabels: null
  annotations: null
  service:
    annotations: null
  extraEnvironmentVars: {}
ui:
  enabled: true
  service:
    enabled: true
    type: null
    port:
      http: 80
      https: 443
    nodePort:
      http: null
      https: null
    annotations: null
    additionalSpec: null
  ingress:
    enabled: false
    ingressClassName: ""
    pathType: Prefix
    hosts: []
    tls: []
    annotations: null
  metrics:
    enabled: "-"
    provider: "prometheus"
    baseURL: http://prometheus-server
  dashboardURLTemplates:
    service: ""
externalServers:
  enabled: false
client:
  enabled: false
dns:
  enabled: false
syncCatalog:
  enabled: false
connectInject:
  enabled: false
controller:
  enabled: false
meshGateway:
  enabled: false
ingressGateways:
  enabled: false
terminatingGateways:
  enabled: false
apiGateway:
  enabled: false
webhookCertManager:
  tolerations: null
prometheus:
  enabled: false
tests:
  enabled: true
```

</details>

`kustomization/kustomize`
```
#!/bin/bash
cat <&0 > all.yaml

kubectl kustomize . && rm all.yaml

```

`kustomization/kustomization.yaml`
```yaml
resources:
- all.yaml
patches:
- path: server-statefulset.yaml
  target:
    kind: StatefulSet
    name: consul-server
- patch: |-
    - op: remove
      path: /spec/template/spec/containers/0/env/0/valueFrom
    - op: add
      path: /spec/template/spec/containers/0/env/0/value
      value: "\"$(eval cat /consul/userconfig/aws-public-ip/aws-public-advertise-ip.txt)\""
  target:
    kind: StatefulSet
    name: consul-server

```

`server-statefulset.yaml`
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul-server
spec:
  template:
    spec:
      initContainers:
      - command:
        - /bin/bash
        - -ec
        - |
          public_ipv4=$(curl http://169.254.169.254/latest/meta-data/public-ipv4)
          consul_config_string="{\"advertise_addr\": \"${public_ipv4}\"}"
          echo $consul_config_string | jq > /consul/userconfig/aws-public-advertise-ip.json
          echo -n $public_ipv4 > /consul/userconfig/aws-public-advertise-ip.txt
        image: 123456789012.dkr.ecr.us-west-2.amazonaws.com/nomad-tools:1.1.2
        imagePullPolicy: IfNotPresent
        name: aws-public-ip-detector
        resources:
          limits:
            cpu: 10m
            memory: 10Mi
          requests:
            cpu: 10m
            memory: 10Mi
        volumeMounts:
        - mountPath: /consul/userconfig
          name: userconfig-aws-public-ip
```

### Logs

```
❯ k -n consul logs consul-server-2 -c consul
==> 2 errors occurred:
	* advertise_addr: invalid ip address: $(eval
	* advertise_addr: invalid ip address: $(eval
```

### Current understanding and Expected behavior

after successfully do helm install, and get consul server statefulset command like below : 
```
      - command:
        - /bin/sh
        - -ec
        - |
          CONSUL_FULLNAME="consul"

          mkdir -p /consul/extra-config
          cp /consul/config/extra-from-values.json /consul/extra-config/extra-from-values.json
          [ -n "${HOST_IP}" ] && sed -Ei "s|HOST_IP|${HOST_IP?}|g" /consul/extra-config/extra-from-values.json
          [ -n "${POD_IP}" ] && sed -Ei "s|POD_IP|${POD_IP?}|g" /consul/extra-config/extra-from-values.json
          [ -n "${HOSTNAME}" ] && sed -Ei "s|HOSTNAME|${HOSTNAME?}|g" /consul/extra-config/extra-from-values.json

          exec /usr/local/bin/docker-entrypoint.sh consul agent \
            -advertise="${ADVERTISE_IP}" \
            -bind=0.0.0.0 \
            -bootstrap-expect=3 \
            -hcl='ca_file = "/consul/tls/ca/tls.crt"' \
            -hcl='cert_file = "/consul/tls/server/tls.crt"' \
            -hcl='key_file = "/consul/tls/server/tls.key"' \
            -hcl='auto_encrypt = {allow_tls = true}' \
            -hcl='verify_incoming_rpc = true' \
            -hcl='verify_outgoing = true' \
            -hcl='verify_server_hostname = true' \
            -hcl='ports { https = 8501 }' \
            -client=0.0.0.0 \
            -config-dir=/consul/config \
            -datacenter=dc1 \
            -data-dir=/consul/data \
            -domain=consul \
            -encrypt="${GOSSIP_KEY}" \
            -hcl="connect { enabled = true }" \
            -hcl='telemetry { prometheus_retention_time = "1m" }' \
            -ui \
            -retry-join="${CONSUL_FULLNAME}-server-0.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc:8301" \
            -retry-join="${CONSUL_FULLNAME}-server-1.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc:8301" \
            -retry-join="${CONSUL_FULLNAME}-server-2.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc:8301" \
            -serf-lan-port=8301 \
            -config-dir=/consul/userconfig/aws-public-ip \
            -config-file=/consul/extra-config/extra-from-values.json \
            -server
        env:
        - name: ADVERTISE_IP
          value: '"$(eval cat /consul/userconfig/aws-public-ip/aws-public-advertise-ip.txt)"'
```

from my understanding the `${ADVERTISE_IP}` will be replaced like : 

```
...
          exec /usr/local/bin/docker-entrypoint.sh consul agent \
            -advertise="$(eval cat /consul/userconfig/aws-public-ip/aws-public-advertise-ip.txt)" \
...
```

`/consul/userconfig/aws-public-ip/aws-public-advertise-ip.txt`
containts the public ip of the aws ec2 instance,
but checking from the consul server pod logs its say : 

```
❯ k -n justice-play logs consul-server-2 -c consul
==> 2 errors occurred:
	* advertise_addr: invalid ip address: $(eval
	* advertise_addr: invalid ip address: $(eval

```

not reading the txt value, but reading the k8s env ADVERTISE_IP value

### Environment details

Additionally, please provide details regarding the Kubernetes Infrastructure, as shown below:
- Kubernetes version: v1.20.11
- Cloud Provider : AWS EKS
- Networking CNI plugin in use: AWS VPC CNI

### Additional Context

any insight that I can get ?
