### ISSUE TITLE
connect: Communication between pods of the same consul service

### ISSUE THREAD

**Issue by Poweranimal** [hashicorp/consul-k8s#1155]
#### Question

Hi there,

How can two or more `Pod`s that belong to the same consul connect service communicate between each other?

Example:
`StatefulSet` with 2 replicas, connect-inject enabled and transparent proxy enabled.
The consul registered port is `8000`.
`pod-0` sends a request to `pod-1` (e.g. `wget -qO- http://pod-1.pod.default:8000`).

Context:
`StatefulSet` services like [minio](https://github.com/minio/minio) have a gossip communication between their `Pod`s on the consul registered service port.
For that reason they must be able to communicate between each other.

### Example Setup
1. Deploy consul with connect enabled and transparent proxy enabled.
2. Deploy the k8s manifest defined below
3. Run: `kubectl exec nginx-0 -- curl -v http://nginx-1.nginx.default:8000`

*Expected Result:*
The `curl` command should return `Hello world!`

*Actual Result:*
The `curl` command returns an empty response.

<details>
  <summary>k8s Manifest</summary>

```yaml
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: nginx
spec:
  protocol: http
  transparentProxy:
    dialedDirectly: true
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/name: nginx
    component: nginx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  default.conf.template: |
    server {
      listen  8000;
      location / {
        return 200 'Hello world!';
        add_header Content-Type text/plain;
      }
    }
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: nginx
      app.kubernetes.io/name: nginx
      component: nginx
  serviceName: nginx
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: nginx
      annotations:
        consul.hashicorp.com/connect-inject: "true"
      labels:
        app.kubernetes.io/instance: nginx
        app.kubernetes.io/name: nginx
        component: nginx
    spec:
      serviceAccountName: nginx
      containers:
        - name: nginx
          image: docker.io/nginx:1.21.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/templates
              name: config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: nginx
```

</details>

**Comment by david-yu** [comment]
Hi @Poweranimal 

We do have a field within the the ServiceDefaults CRD called `DialedDirectly` ([link](https://www.consul.io/docs/connect/config-entries/service-defaults#dialeddirectly)) which allows you to dial the proxies directly for a given Service. Could you try setting the `DialedDirectly` config to true?

**Comment by Poweranimal** [comment]
Hi @david-yu ,
I already enabled this mode.
However, this only seems to allow direct IP address dialing from another consul service to the target consul service. It seems to have no effect when it comes to communication between pods that belong to the same consul service.

**Comment by david-yu** [comment]
Apologies, I had neglected to glance at the first part of your k8s manifest as I did not expand it. One thing to try is also to use some annotations on the pods themselves to exclude traffic redirection on certain ports. In this it seems you may want to exclude traffic re-direction based on inbound request to port 8000.

https://www.consul.io/docs/connect/transparent-proxy#traffic-redirection-configuration

```
template:
    metadata:
      name: nginx
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/transparent-proxy-exclude-inbound-ports: "8000"
```
