### ISSUE TITLE
consul-consul-server-acl-init job fails consecutively when using manageSystemACLs 

### ISSUE THREAD

**Issue by JonathanG3** [hashicorp/consul-k8s#1198]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

consul-consul-server-acl-init job fails consecutively when using manageSystemACLs 

### Reproduction Steps

Create a Consul Cluster with the following helm values.yaml:
```
global:
  enabled: true
  logLevel: "info"
  logJSON: false
  name: null
  domain: consul
  adminPartitions:
    enabled: false
    name: "default"
    service:
      type: LoadBalancer
      nodePort:
        rpc: null
        serf: null
        https: null
      annotations: null
  image: "hashicorp/consul:1.12.0"
  imagePullSecrets: []
  imageK8S: "hashicorp/consul-k8s-control-plane:0.43.0"
  datacenter: dc1
  enablePodSecurityPolicies: false
  gossipEncryption:
    autoGenerate: false
    secretName: "gossip-encryption-key"
    secretKey: "key"
  recursors: []
  tls:
    enabled: false
  enableConsulNamespaces: false
  acls:
    manageSystemACLs: true
  metrics:
    enabled: true
    enableAgentMetrics: true
    agentMetricsRetentionTime: 1m
    enableGatewayMetrics: true
  consulSidecarContainer:
    resources:
      requests:
        memory: "25Mi"
        cpu: "20m"
      limits:
        memory: "50Mi"
        cpu: "20m"
  imageEnvoy: "envoyproxy/envoy:v1.22.0"
  openshift:
    enabled: false
server:
  enabled: "-"
  image: null
  replicas: 3
  bootstrapExpect: null
  serverCert:
    secretName: null
  exposeGossipAndRPCPorts: false
  ports:
    serflan:
      port: 8301
  storage: 10Gi
  storageClass: 'consul-storageclass'
  connect: true
  serviceAccount:
    annotations: null
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "100Mi"
      cpu: "100m"
  updatePartition: 0
client:
  enabled: false
ui:
  enabled: "-"
  service:
    enabled: true
    type: null
    port:
      http: 80
      https: 443
    nodePort:
      http: 30780
      https: 31433
    annotations: null
    additionalSpec: null
  metrics:
    enabled: false
tests:
  enabled: true
```
Logs -

From kubectl get all -n consul:
```
NAME                                         READY   STATUS    RESTARTS   AGE
pod/consul-consul-server-0                   1/1     Running   0          5m9s
pod/consul-consul-server-1                   1/1     Running   0          5m9s
pod/consul-consul-server-2                   1/1     Running   0          5m9s
pod/consul-consul-server-acl-init--1-bbsxf   0/1     Error     0          2m36s
pod/consul-consul-server-acl-init--1-jblxh   0/1     Error     0          5m6s
pod/consul-consul-server-acl-init--1-nwphb   0/1     Error     0          4m36s
pod/consul-consul-server-acl-init--1-qp62l   0/1     Error     0          3m56s
pod/consul-consul-server-acl-init--1-s8w4g   0/1     Error     0          4m56s
pod/consul-consul-server-acl-init--1-tkhrj   0/1     Error     0          5m9s
```

```
flag provided but not defined: -create-client-token
Usage:
  -acl-binding-rule-selector string
        Selector string for connectInject ACL Binding Rule.
  -acl-replication-token-file string
        Path to file containing ACL token to be used for ACL replication. If set, ACL replication is enabled.
   .... <the rest of the options available> ...

```

### Expected behavior

Cluster created without any issue

### Environment details

Additionally, please provide details regarding the Kubernetes Infrastructure, as shown below:
- Kubernetes version: v1.22.2
- Kubernetes provider utilized: Kubeadm
- Networking CNI plugin in use: Calico

--->

### Additional Context

None
