### ISSUE TITLE
Does ingress gateways shareable across k8s cluster

### ISSUE THREAD

**Issue by LDHo** [hashicorp/consul-k8s#1220]
#### Question

Hello I am currently trying out with HCP Consul. I have a network setup as diagram below.
![Untitled drawio](https://user-images.githubusercontent.com/30370361/168108045-63519c51-0e45-43a0-abe4-04edf1fcfb95.png)

I was just wondering if I have an ingress gateway pod setup in the k8s cluster located in `vpc-1`, would it be able to access the the application service deployed in `vpc-2`.  I have had some reading on [this docs](https://www.consul.io/docs/k8s/installation/deployment-configurations/single-dc-multi-k8s ) where the application in the cluster with only consul client deployed could eventually connect to the application deployed alongside in the cluster with consul servers. 
Just wondering whether same case applied here. Eventually I have tried it up myself but doesn't seem it works, which is why I am here to ensure my finding.

**Comment by david-yu** [comment]
Hi @LDHo I assume the two Kubernetes clusters are not peered from those two VPCs so you simply cannot send traffic from K8s cluster to another? 

If peering is not an option, another workflow we have enabled is Admin Partitions which should be part of your HCP offering (since it also bundles enterprise features) and I would encourage you to try the cross partition networking feature to communicate between two different k8s clusters. In addition to opening up a few ports for Mesh Gateway traffic, this would require though that each k8s cluster be associated to its own partition, and that you export services in order to enable communication between services across partitions. 

Admin Partitions docs: https://www.consul.io/docs/enterprise/admin-partitions
Exported services docs: https://www.consul.io/docs/connect/config-entries/exported-services

**Comment by david-yu** [comment]
Closing as was addressed via previous response.

**Comment by LDHo** [comment]
Hi @david-yu, I have been researching the admin partition and the exported services features advised by you. I did manage to create two separate partitions and install some services into them. However, I was unable to allow the ingress gateway from one cluster to reach the services deployed in another cluster. Below are the configs that I used for my setup. Just wondering whether you could help and point out what I missed.

Helm chart version: v0.44.0
Kubernetes version: v1.22

cluster-1 config: 
```
global:
  name: dc1
  enabled: false
  image: hashicorp/consul-enterprise:1.12.0-ent
  enableConsulNamespaces: true
  adminPartitions:
    enabled: true
    name: dc1
  datacenter: igw-test
  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: consul-bootstrap-token
      secretKey: token
  gossipEncryption:
    secretName: consul-gossip-key
    secretKey: key
  tls:
    enabled: true
    enableAutoEncrypt: true
    caCert:
      secretName: consul-ca-cert
      secretKey: tls.crt
externalServers:
  enabled: true
  hosts: [${RETRY_JOIN}]
  httpsPort: 443
  useSystemRoots: true
  k8sAuthMethodHost: ${KUBE_API_URL}
client:
  enabled: true
  join: [${RETRY_JOIN}]
connectInject:
  enabled: true
  default: false
  transparentProxy:
    defaultEnabled: false
controller:
  enabled: true
ui:
  enabled: true
dns:
  enabled: true
meshGateway:
  enabled: true
  replicas: 1
ingressGateways:
  enabled: true
  defaults:
    replicas: 1
  gateways:
    - name: igw-1
      service:
        ports:
          - port: 9090

```

cluster-2 config:
```
global:
  name: dc2
  enabled: false
  image: hashicorp/consul-enterprise:1.12.0-ent
  enableConsulNamespaces: true
  adminPartitions:
    enabled: true
    name: dc2
  datacenter: igw-test
  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: consul-bootstrap-token
      secretKey: token
  gossipEncryption:
    secretName: consul-gossip-key
    secretKey: key
  tls:
    enabled: true
    enableAutoEncrypt: true
    caCert:
      secretName: consul-ca-cert
      secretKey: tls.crt
externalServers:
  enabled: true
  hosts: [${RETRY_JOIN}]
  httpsPort: 443
  useSystemRoots: true
  k8sAuthMethodHost: ${KUBE_API_URL}
client:
  enabled: true
  join: [${RETRY_JOIN}]
connectInject:
  enabled: true
  default: false
  transparentProxy:
    defaultEnabled: false
controller:
  enabled: true
dns:
  enabled: true
meshGateway:
  enabled: true
  replicas: 1
```

ingress-gateway.yaml applied in cluster-1
```
apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: igw-1
spec:
  listeners:
    - port: 9090
      protocol: http
      services:
        - name: '*'
        - name: '*'
          partition: dc2
```

service-intentions.yaml applied in cluster-1
```
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: allow-ingress-gateway-to-all
spec:
  destination:
    name: '*'
  sources:
    - name: igw-1
      action: allow
```

service-intentions.yaml applied in cluster-2
```
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: allow-ingress-gateway-to-all
spec:
  destination:
    name: '*'
  sources:
    - name: igw-1
      partition: dc1
      action: allow
```

application.yaml applied in cluster-2
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodejs
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs
spec:
  selector:
    app: nodejs
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: js-deployment
  labels:
    app: nodejs
spec:
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: liande1203/dummy-js
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      serviceAccountName: nodejs
```
exported-services.yaml applied in cluster-2
```
apiVersion: consul.hashicorp.com/v1alpha1
kind: ExportedServices
metadata:
  name: dc2
spec:
  services:
    - name: nodejs
      consumers:
        - partition: dc1
```
proxy-defaults configuration applied in both clusters
```
apiVersion: consul.hashicorp.com/v1alpha1
kind: ProxyDefaults
metadata:
  name: global
spec:
  meshGateway:
    mode: local
  config:
    protocol: "http"
```

As I have enabled `consul-dns`, I send requests to the service via command below:
```
curl -XGET http://nodejs.ingress.consul:9090/api/whoami
```


Hope to hear from you soon.
Thanks.
