### ISSUE TITLE
Cannot create Ingress Gateways with the same name in different namespaces

### ISSUE THREAD

**Issue by thomashashi** [hashicorp/consul-k8s#1285]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

When using the Helm chart version 0.42.0 (haven't been able to try it with the latest version) I am unable to create two ingress gateways with the same name but in different namespaces. I could do that manually if I were outside of Kubernetes, but cannot with the Helm chart — I believe we make some assumptions in how we name the Deployments and Pods created which don't take into account the namespace into which an IGW is provisioned.

### Reproduction Steps

Create a Helm values file with the following stanza:

```
ingressGateways:
  enabled: true
  defaults:
    annotations: |
      "service.beta.kubernetes.io/aws-load-balancer-internal": "true"
      "service.beta.kubernetes.io/aws-load-balancer-scheme": "internal"
      "service.beta.kubernetes.io/aws-load-balancer-type": "nlb"
  gateways:
    - name: ingressgw
      consulNamespace: gateways
      service:
        type: ClusterIP
        ports:
          - port: 80
          - port: 443
    - name: ingressgw
      consulNamespace: k8s-122-gateways
      service:
        type: ClusterIP
        ports:
          - port: 80
          - port: 443
```
and attempt to deploy.

### Logs

Output from `helm upgrade consul hashicorp/consul -f consul-helm.yaml --namespace consul --version 0.42.0` (where `consul-helm.yaml` is the values file containing the stanza in the previous section): 

```
Error: UPGRADE FAILED: template: consul/templates/ingress-gateways-deployment.yaml:18:3: executing "consul/templates/ingress-gateways-deployment.yaml" at <fail (cat "ingress gateways must have unique names but found duplicate name" $innerIngressVal.name)>: error calling fail: ingress gateways must have unique names but found duplicate name ingressgw
```

### Environment details

* Helm chart version 0.42.0
* Consul Enterprise 1.11.4
