### ISSUE TITLE
can't create directory '/consul/extra-config': Permission denied

### ISSUE THREAD

**Issue by eb4x** [hashicorp/consul-k8s#1306]
### Overview of the Issue

There's a little snippet introduced by hashicorp/consul-helm#1042 trying to `mkdir -p /consul/extra-config` which results in `mkdir: can't create directory '/consul/extra-config': Permission denied` on openshift / okd clusters.

### Reproduction Steps

1. When running helm install with the following `values.yml`:
```
global:
  name: consul
  enablePodSecurityPolicies: true
  openshift:
    enabled: true
```
2. Observe the error on openshift / okd v4 clusters.

### Environment details

- `consul-k8s` version: 0.45.0
- Kubernetes version: v1.23.5
- Cloud Provider: Openstack / OpenShift 4.10
- Networking CNI plugin in use: OpenShiftSDN
