### ISSUE TITLE
How to Expose Consul DNS Outside of Kubernetes

### ISSUE THREAD

**Issue by felipeavilis** [hashicorp/consul-k8s#1320]
#### Question

How to Expose Consul DNS Outside of Kubernetes?

I did some searches to try and figure if someone else is trying to do the same thing as me. I'm somewhat new to Consul so I apologize if this is a bad question. I found [this old topic](https://github.com/hashicorp/consul-helm/issues/362) but with no answer and the topic was moved and closed. This link https://www.consul.io/docs/k8s/dns does not explain how to do it.

I had the idea to expose NodePorts to the network by leveraging Consul's kubernetes sync. I got Services to sync, but now I need some DNS, which defaults to name.service.consul.

My point is: I have some applications running out of Kubernetes, and i want to use Consul DNS to resolve name of services that are controled by Consul and running inside Kubernetes.

Thanks in advance!

### Helm Configuration

helm_values.yml
```
global:
  datacenter: dc-valecard
  name: consul

server:
  replicas: 1
  securityContext:
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
    fsGroup: 0

client:
  enabled: true

ui:
  enabled: true
  service:
    enabled: true
    type: 'NodePort'
  ingress:
    enabled: true
    annotations: |
      kubernetes.io/ingress.class: nginx
    
connectInject:
  enabled: true
  replicas: 1

controller:
  enabled: true

ingressGateways:
  enabled: true
  defaults:
    replicas: 1
    service:
      type: LoadBalancer
  gateways:
    - name: ingress-gateway
```
