### ISSUE TITLE
If kube service has port without name, use different meta

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul-k8s#142]
If a kube service has an unnamed port (which is allowed if there's only one port):
```yaml
spec:
  clusterIP: 10.35.247.0
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
```
Then we sync it over and set meta to `"port-": "80"` which looks weird and broken.

Instead we should use `port` or `port-unnamed` or something like that.
