### ISSUE TITLE
Orphaned ACL tokens

### ISSUE THREAD

**Issue by Mlaczkowski** [hashicorp/consul-k8s#1441]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

Consul is not cleaning up ACL tokens when the k8s node is suddenly shutdown without draining or sending sigterm signal.

### Reproduction Steps

Using `manageSystemACLs` is required.
Force destroy any k8s node that is holding the consul client pod. You can see that pod is not able to perform consul logout command in pre-stop and in that case, is leaving ACL token inside consul. We will also see an unhealthy node in the consul catalog, but that is not so big of the problem, as after 72h it will be cleaned up. 
The same is true for injected pods, they will also leave some ACL entries when the node hosting them (and the local consul agent) is shut down in an unexpected manner. In injector logs, you will not see any information about revoking ACL for them. 

After running like that on our very unstable test cluster we observe that we have ~4000 orphaned ACL entries after a few weeks of testing.

In our case, we use external servers, but it should work the same in the local server setup.
Simplified values.yaml: 
```
---
global:
  image: "hashicorp/consul:1.12.2"
  logLevel: "info"
  datacenter: qa
  imageEnvoy: "envoyproxy/envoy-alpine:v1.20.3"
  logJSON: true
  tls:
    enabled: true
    enableAutoEncrypt: true
    httpsOnly: false
    caCert:
      secretName: consul-ca-certs
    caKey:
      secretName: consul-ca-certs
  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: consul-acl-bootstrap-token
      secretKey: acl-bootstrap-token
  metrics:
    enabled: true
    enableAgentMetrics: true
controller:
  enabled: true
server:
  enabled: false
externalServers:
  enabled: true
  hosts: &servers ["consul01", "consul02", "consul03"]
  httpsPort: 8501
  k8sAuthMethodHost: <k8s_address>
connectInject:
  priorityClassName: "core-critical"
  enabled: true
client:
  join: *servers
  priorityClassName: "daemonset-critical"
```

In this particular cluster, we got ~10-20 nodes and only a few injected applications (less than 30 pods). After a few weeks, we are seeing that number of ACL tokens is constantly growing. As they don't have any TTL assigned to them, they will never expire. 
```
>consul acl token list  | grep 'token created via login: {"component":"client"}' | wc -l
3130
>consul acl token list  | grep 'token created via login: {"pod":"' | wc -l
1434
```

### Expected behavior

Pods should not leave any ACL tokens that are not needed anymore.

### Environment details

- Kubernetes version: 1.22.10
- Cloud Provider GKE
- Networking CNI plugin in use: Calico
