### ISSUE TITLE
Gossip Encryption autogenerate fails in Openshift on K8s 1.24 when using PSPs

### ISSUE THREAD

**Issue by adaumann** [hashicorp/consul-k8s#1503]
If using Openshift with Consul/helm, The 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

Currently using Consul Helm within Openshift 4.11.1 context (with Kubernetes 1.24). The Gossip Encryption fails, even if the openshift.enabled flag is set, with following error:

Error creating: pods "consul-gossip-encryption-autogenerate-" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, provider restricted-v2: .spec.securityContext.fsGroup: Invalid value: []int64{1000}: 1000 is not an allowed group, spec.containers[0].securityContext.runAsUser: Invalid value: 100: must be in the ranges: [1000660000, 1000669999], provider "restricted": Forbidden: not usable by user or serviceaccount, provider "nonroot-v2": Forbidden: not usable by user or serviceaccount, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork-v2": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]

My expectation is that with the flag openshift.enabled all security contexts are set corrently. Not only for the server, client etc. Also for the init containers. Additionally took the latest images from redhat, see below.

### Reproduction Steps

Steps to reproduce this issue, eg:

1. When running helm install with the following `values.yml`:
```
consul:
  global:
    name: consul
    datacenter: dc1
    image: registry.connect.redhat.com/hashicorp/consul:1.13.1-ubi
    imageK8S: registry.connect.redhat.com/hashicorp/consul-k8s-control-plane:0.48.0-ubi
    imagePullSecrets:
      - name: 15472453-hcv-redhat-registry-pull-secret
    openshift:
      enabled: true
    gossipEncryption:
      autoGenerate: true
    tls:
      enabled: true
      enableAutoEncrypt: true
      verify: false
      serverAdditionalDNSSANs:
        - localhost
        - consul-server
        - consul-server.sbk-hcv-infra
        - consul-server.sbk-hcv-infra.svc.cluster.local     
    acls:
      manageSystemACLs: true 
```
1. View error

Error creating: pods "consul-gossip-encryption-autogenerate-" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, provider restricted-v2: .spec.securityContext.fsGroup: Invalid value: []int64{1000}: 1000 is not an allowed group, spec.containers[0].securityContext.runAsUser: Invalid value: 100: must be in the ranges: [1000660000, 1000669999], provider "restricted": Forbidden: not usable by user or serviceaccount, provider "nonroot-v2": Forbidden: not usable by user or serviceaccount, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork-v2": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]
### Expected behavior

Security context is set correctly.
