### ISSUE TITLE
Using Consul Helm chart in Openshift 4.11 context does not allow to generate system ACL

### ISSUE THREAD

**Issue by adaumann** [hashicorp/consul-k8s#1504]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

Currently using Consul Helm within Openshift 4.11.1 context (with Kubernetes 1.24). The automatic generation of system ACL fails

### Reproduction Steps

1. When running helm install with the following `values.yml`:
```
consul:
  global:
    name: consul
    datacenter: dc1
    image: registry.connect.redhat.com/hashicorp/consul:1.13.1-ubi
    imageK8S: registry.connect.redhat.com/hashicorp/consul-k8s-control-plane:0.48.0-ubi
    imagePullSecrets:
      - name: 15472453-hcv-redhat-registry-pull-secret
    openshift:
      enabled: true
    #gossipEncryption:
    # autoGenerate: true
    tls:
      enabled: true
      enableAutoEncrypt: true
      verify: false
      serverAdditionalDNSSANs:
        - localhost
        - consul-server
        - consul-server.sbk-hcv-infra
        - consul-server.sbk-hcv-infra.svc.cluster.local     
    acls:
      manageSystemACLs: true 
```

1. View error

### Logs

![image](https://user-images.githubusercontent.com/94932945/190405917-5d02cca7-0da8-4ac6-9d33-8e06c88eab47.png)

### Expected behavior

The system ACL with the secret Id is created und Kubernetes secret is build.
