### ISSUE TITLE
Consul inject side car fails for rabbitmq server in Openshift 4.11

### ISSUE THREAD

**Issue by adaumann** [hashicorp/consul-k8s#1510]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview

The consul inject sidecar init fails in Rabbit MQ. Using the RabbitMQ Cluster Operator in Openshift. If disabling the connectInject rabbitMQ works

### Reproduction Steps

- Using Openshift 4.11 CRC 
- Installing RabbitMQ Cluster Operator via Operator hub with security context information. https://www.rabbitmq.com/kubernetes/operator/using-on-openshift.html
- Rabbit MQ runs in privileged mode
- Installing Consul 1.12.0 and Consul operator 0.43 (Any version higher does not work at all in Openshift, see other issue)

Use following values:

```
consul:
  global:
    name: consul
    datacenter: hcv-dc1
    # Only this combination is working, 0.47.1 and 0.48 not working to start in insecure container. Secure container never possible
    image: registry.connect.redhat.com/hashicorp/consul:1.12.0-ubi
    imageK8S: registry.connect.redhat.com/hashicorp/consul-k8s-control-plane:0.43.0-ubi
    imagePullSecrets:
      - name: xxxxxxxxxxx-hcv-redhat-registry-pull-secret
    openshift:
      enabled: true
      
  server:
    replicas: 1
    bootstrapExpect: 1
    disruptionBudget:
      enabled: true
      maxUnavailable: 0
      
  client:
    enabled: true
    grpc: true
      
  ui:
    enabled: true 
      
  connectInject:
    enabled: true
    default: true
      
  controller:
    enabled: true
```

### Logs

- rabbitmq-cluster-server-0 : Failed to start because cluster-consul-connect-init not woking

```

2022-09-16T08:37:25.697Z [INFO] Unable to find registered services; retrying
2022-09-16T08:37:25.697Z [INFO] Check to ensure a Kubernetes service has been created for this application. If your pod is not starting also check the connect-inject deployment logs.
2022-09-16T08:37:26.698Z [INFO] Unable to find registered services; retrying
2022-09-16T08:37:27.700Z [INFO] Unable to find registered services; retrying
2022-09-16T08:37:28.702Z [INFO] Unable to find registered services; retrying
2022-09-16T08:37:29.702Z [INFO] Unable to find registered services; retrying
2022-09-16T08:37:30.703Z [INFO] Unable to find registered services; retrying
2022-09-16T08:37:31.705Z [INFO] Unable to find registered services; retrying
```

--->

### Expected behavior

The consul connect init container should not fail in rabbitmq context
