### ISSUE TITLE
Injection fails and freezes on pure clients w/o service specified

### ISSUE THREAD

**Issue by darkn3rd** [hashicorp/consul-k8s#1528]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Overview of the Issue

When installing a pure client, a single Deployment object, the pods are forever in a Pending state.  So far it has been over 166 minutes, and still nothing is deployed.

### Reproduction Steps

1. Install NSM (consul-connect):
   ```bash
   helm install consul hashicorp/consul \
     --create-namespace \
     --namespace consul \
     --set global.name=consul \
     --set connectInject.enabled=consul \
     --set controller.enabled=consul
   ```
2. Install pure client (one that does not listen on a port):
   ```bash
   kubectl create namespace test

   cat << EOF > deploy.yaml
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: pydgraph-client
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: pydgraph-client
     template:
       metadata:
         annotations:
           consul.hashicorp.com/connect-inject: "true"
           consul.hashicorp.com/transparent-proxy: "true"
         labels:
           app: pydgraph-client
       spec:
         containers:
         - env:
           - name: DGRAPH_ALPHA_SERVER
             value: dgraph-dgraph-alpha.dgraph.svc.cluster.local
           image: darknerd/pydgraph-client
           name: pydgraph-client
   EOF

   kubectl aplly -f deploy.yaml -n test
   ```
3. Get status of pods after some time:
   ```bash
   $ kubectl get pods -n test
   NAME                               READY   STATUS    RESTARTS   AGE
   pydgraph-client-85b788bb79-pwp7w   0/2     Pending   0          166m
   ```

### Logs

The consul-connect-injector logs only show:

```log
2022-09-25T00:39:15.522Z	INFO	handler.connect	received pod	{"name": "", "ns": "test"}
```

### Expected behavior

The init container, envoy proxy side-car, and application containers would be deployed.  

### Actual behavior

Nothing happen except the pod deployment is freezing.  

### Environment details

- `consul-k8s` version: v0.48.0
- `values.yaml` used to deploy the helm chart:
  ```yaml
  global:
    name: consul
  connectInject:
    enabled: true
  controller:
    enabled: true
  ```
- Kubernetes version: v1.22.12-gke.300
- Cloud Provider: GKE
- Networking CNI plugin in use: whatever comes default with GKE

### Additional Context

This is a utility client that communicates with a service that is on the mesh network.  If this member is not part of the mesh network, then it cannot communicate to the server.  This use case is not unusual, and I am surprise this does not work.  I have used this container to test service meshes on Istio, Linkerd, and NGINX service mesh, and this is the only service mesh that has failed for this use case.

**Comment by darkn3rd** [comment]
@kschoche I never had an issue with other service meshes, and have implemented this successfully in Istio, Linkerd, and NGINX Service Mesh without any issues.  Having a service sit frozen for days without feedback to the users I hope is not a desired experience for users.  The very least this should be documented more clearly.

**Comment by darkn3rd** [comment]
@kschoche Following your suggestion, I created a small python flask server, and tested it. It runs fine locally, as a docker container, and when deployed without CSM annotations.  When I deploy it with injection, it freezes in `pending` state.

This is my manifest:

```yaml
---
# Source: raw/templates/patched_resources.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: raw
    chart: raw-v0.2.5
    heritage: Helm
    release: pydgraph-client
  name: pydgraph-client
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: pydgraph-client
  type: ClusterIP
---
# Source: raw/templates/patched_resources.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: raw
    chart: raw-v0.2.5
    heritage: Helm
    release: pydgraph-client
  name: pydgraph-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pydgraph-client
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/transparent-proxy: "true"
      labels:
        app: pydgraph-client
    spec:
      containers:
      - env:
        - name: DGRAPH_ALPHA_SERVER
          value: dgraph-dgraph-alpha.dgraph.svc.cluster.local
        image: darknerd/pydgraph-client:consul-v0.3
        name: pydgraph-client
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 25m
            memory: 128Mi
          requests:
            cpu: 8m
            memory: 64Mi
```
