### ISSUE TITLE
Does Consul configures Envoy with request buffering?

### ISSUE THREAD

**Issue by raphlcx** [hashicorp/consul-k8s#1588]
### Question

Good day HashiCorp.

I would like to seek clarification regarding how Envoy handles request buffering in Consul service mesh.

Our case is that, we are currently running a few load tests by setting up:
1. A stressor script written using k6
2. A Spring Application that serves as the system-under-tests

The stressor script will connect to the Spring Application via 3 methods:
1. Using custom NGINX ingress within our Kubernetes cluster
2. Using KubeDNS
3. Using service mesh (i.e. the localhost:port pair)

We noticed that the load test is successful in connection case (1) and (2), but is failling on connection case (3).

Our speculation is that, in scenarios (1) and (2), there are intermediary proxies (NGINX and kube-proxy) that buffer the traffic, so it does not hit the Spring Application hard.

In the case of scenario (3), service communicates with another service directly in a service mesh, using Envoy as the proxy. If Envoy does not have any form of buffering, the load test requests could be hitting the application directly, potentially overloading the application's max of 200 simultaneous request handling capability [[ref](https://docs.bmc.com/docs/brid91/en/tomcat-container-workload-configuration-825210082.html)].

Is this assumption valid?

### CLI Commands (consul-k8s, consul-k8s-control-plane, helm)

n/a

### Helm Configuration

```
global:
  enabled: false
  name: stag-eks
  datacenter: staging
  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: staging-hcp-consul
      secretKey: consul-bootstrap-token
  gossipEncryption:
    secretName: staging-hcp-consul
    secretKey: consul-gossip-key
  tls:
    enabled: true
    enableAutoEncrypt: true
    caCert:
      secretName: staging-hcp-consul
      secretKey: consul-ca-cert
  metrics:
    enabled: true
  image: xxx.dkr.ecr.us-east-1.amazonaws.com/hashicorp/consul:1.12.0
  imageK8S: xxx.dkr.ecr.us-east-1.amazonaws.com/hashicorp/consul-k8s-control-plane:0.44.0
  imageEnvoy: xxx.dkr.ecr.us-east-1.amazonaws.com/envoyproxy/envoy:v1.22.0
externalServers:
  enabled: true
  hosts: ["staging.private.consul.xxx.aws.hashicorp.cloud"]
  httpsPort: 443
  useSystemRoots: true
  k8sAuthMethodHost: https://xxx.yyy.us-east-1.eks.amazonaws.com
client:
  enabled: true
  priorityClassName: "high-priority"
  join: ["staging.private.consul.xxx.aws.hashicorp.cloud"]
  resources:
    requests:
      memory: "130Mi"
    limits:
      memory: "130Mi"
connectInject:
  enabled: true
  default: false
  priorityClassName: "high-priority"
  transparentProxy:
    defaultEnabled: false
  resources:
    requests:
      memory: "160Mi"
    limits:
      memory: "160Mi"
  failurePolicy: "Ignore"
  disruptionBudget:
    enabled: true
    maxUnavailable: 0
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: {{ template "consul.name" . }}
              release: "{{ .Release.Name }}"
              component: connect-injector
          topologyKey: kubernetes.io/hostname
controller:
  enabled: true
```

### Current understanding and Expected behavior

Expecting load test via service mesh should also be successful, as with load test using custom ingress and KubeDNS.

### Environment details

HCP Consul: 1.12.5
consul-k8s version: 0.44.0
Kubernetes version: 1.21
Cloud Provider: AWS EKS
