### ISSUE TITLE
Can't get Connect to work in Kubernetes

### ISSUE THREAD

**Issue by 0xCA7F00D** [hashicorp/consul-k8s#16]
Hello, 
I recently tried the Connect functionality on my PC, and thought that it'll be great trying it in k8s.

So I looked at the sources here of the ongoing development of the mutating webhook and seen what is the plan for getting it to work in Kubernetes.

I tried to add an "unmanaged" Connect proxy as a sidecar to a pod:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        # ports:
        # - containerPort: 80
      - name: connect
        image: "consul:latest"
        # ports:
        # - containerPort: 12500
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        command:
          - "/bin/sh"
          - "-ec"
          - "exec /bin/consul connect proxy -service=nginx -listen=${POD_IP}:12500 -service-addr=127.0.0.1:80  -register"
```

that completely worked for me, according to the logs when I do "kubectl logs":
```
$ kubectl logs nginx-6fb7b46fbd-tfdd9 connect
==> Consul Connect proxy starting...
    Configuration mode: Flags
               Service: nginx
       Public listener: 10.244.1.88:12500 => 127.0.0.1:80
==> Log data will now stream in as it occurs:
    2018/10/09 07:25:29 [INFO] proxy loaded config and ready to serve
    2018/10/09 07:25:29 [INFO] public listener starting on 10.244.1.88:12500
    2018/10/09 07:25:29 [INFO] proxy: registered Consul service: nginx-proxy
```

I checked in the web UI that the nginx service is registered well(the ip + port is good) and I tied it both by syncing k8s services and Consul and by manually registering it with a json through the HTTP API.

The problem is that when I curl the proxy that is what I get:
```
$ curl 10.244.1.88:12500

```
And when I curl the nginx service directly:
```
$ curl 10.244.1.88:80
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```
I tried to remove and add the container ports individually or together and it still did not work.
I also tried to change the -service-addr flag to ${POD_IP} and that made no difference as well.
I tried as well to change the -service-addr flag to ${POD_IP}:80

When I sniff the network I see in Wireshark that the connection to port 12500 gets a "HTTP continuation"(?) packet.
That has also happened to me locally a few times when I tried to make those proxies work, so I decided to try with an upstream proxy as well:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        # ports:
        # - containerPort: 80
      - name: connect
        image: "consul:latest"
        # ports:
        # - containerPort: 9090
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        command:
          - "/bin/sh"
          - "-ec"
          - "exec /bin/consul connect proxy -service=nginx -upstream=nginx:9090
```
This time, when I curl port 9090 I get a "connection refused" message, and when I nsenter the network namespace and curl locally I get the same results as above with the "unmanaged" proxy.
(I of course made sure that nginx's service is registered correctly)

I would like to get your help on this.
Thanks in advance.
