### ISSUE TITLE
Connections bypass ACL security in multi-port

### ISSUE THREAD

**Issue by darkn3rd** [hashicorp/consul-k8s#1606]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Overview of the Issue

When using multi-port service with ACLs, traffic between upstream via localhost to the server is protected, but traffic from outside to the service endpoint is not protected.  Essentially, it looks like mult-port disables ACLs.

I followed guides related from:

* https://learn.hashicorp.com/tutorials/consul/kubernetes-secure-agents
* https://www.consul.io/docs/k8s/connect#kubernetes-pods-with-multiple-ports

### Reproduction Steps

1. Deploy consul with these values:
   ```yaml
   global:
     name: consul
     enabled: true
     datacenter: dc1
     gossipEncryption:
       autoGenerate: true
     tls:
       enabled: true
       enableAutoEncrypt: true
       verify: true
     acls:
       manageSystemACLs: true
   server:
     replicas: 1
     securityContext:
       runAsNonRoot: false
       runAsUser: 0
   connectInject:
     enabled: true
   controller:
     enabled: true
   ```
2. Deploy server:
   ```yaml
   # server.yaml
   ---
   apiVersion: consul.hashicorp.com/v1alpha1
   kind: ServiceDefaults
   metadata:
     name: static-server
   spec:
     protocol: 'http'
   ---
   apiVersion: v1
   kind: Service
   metadata:
     name: web
   spec:
     selector:
       app: web
     ports:
       - protocol: TCP
         port: 80
         targetPort: 8080
   ---
   apiVersion: v1
   kind: Service
   metadata:
     name: web-admin
   spec:
     selector:
       app: web
     ports:
       - protocol: TCP
         port: 80
         targetPort: 9090
   ---
   apiVersion: v1
   kind: ServiceAccount
   metadata:
     name: web
   ---
   apiVersion: v1
   kind: ServiceAccount
   metadata:
     name: web-admin
   ---
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: web
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: web
     template:
       metadata:
         name: web
         labels:
           app: web
         annotations:
           'consul.hashicorp.com/connect-inject': 'true'
           'consul.hashicorp.com/transparent-proxy': 'false'
           'consul.hashicorp.com/connect-service': 'web,web-admin'
           'consul.hashicorp.com/connect-service-port': '8080,9090'
       spec:
         containers:
           - name: web
             image: hashicorp/http-echo:latest
             args:
               - -text="hello world"
               - -listen=:8080
             ports:
               - containerPort: 8080
                 name: http
           - name: web-admin
             image: hashicorp/http-echo:latest
             args:
               - -text="hello world from 9090"
               - -listen=:9090
             ports:
               - containerPort: 9090
                 name: http
         serviceAccountName: web
   ```
3. Deploy client:
   ```yaml
   # client.yaml
   ---
   apiVersion: consul.hashicorp.com/v1alpha1
   kind: ServiceDefaults
   metadata:
     name: static-client
   spec:
     protocol: 'http'
   ---
   apiVersion: v1
   kind: Service
   metadata:
     # This name will be the service name in Consul.
     name: static-client
   spec:
     selector:
       app: static-client
     ports:
       - port: 80
   ---
   apiVersion: v1
   kind: ServiceAccount
   metadata:
     name: static-client
   ---
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: static-client
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: static-client
     template:
       metadata:
         name: static-client
         labels:
           app: static-client
         annotations:
           'consul.hashicorp.com/connect-inject': 'true'
           consul.hashicorp.com/connect-service-upstreams: "web:1234,web-admin:2234"
       spec:
         containers:
           - name: static-client
             image: curlimages/curl:latest
             # Just spin & wait forever, we'll use `kubectl exec` to demo
             command: ['/bin/sh', '-c', '--']
             args: ['while true; do sleep 30; done;']
         # If ACLs are enabled, the serviceAccountName must match the Consul service name.
         serviceAccountName: static-client
   ```
4. Exec into client container:
   ```bash
   export NS=${NS:-"default"}
   POD=$(kubectl get pods --namespace $NS --selector app=static-client --output name)
   kubectl exec -ti --container "static-client" --namespace $NS ${POD} -- /bin/sh
   ```
5. Connect through upstream (run from within client container):
   ```bash
   curl localhost:1234 # fails as expected
   # curl: (7) Failed to connect to localhost port 1234 after 0 ms: Connection refused
   curl localhost:2234 # fails as expected
   # curl: (7) Failed to connect to localhost port 2234 after 0 ms: Connection refused
   ```
6. Connect through service endpoint:
   ```bash
   export NS=${NS:-"default"}
   curl web.$NS.svc.cluster.local # this SHOULD FAIL
   # "hello world"
   curl web-admin.$NS.svc.cluster.local # this SHOULD FAIL
   # "hello world from 9090"
   ```

### Logs

n/a

### Expected behavior

I expected that when communicating through the service endpoints, e.g. `web.default.svc.cluster.local`, this would be blocked.  However, this works fine despite ACLs enabled.

### Environment details

Additionally, please provide details regarding the Kubernetes Infrastructure, as shown below:
- Kubernetes version: v1.22
- Cloud Provider: GKE
- Networking CNI plugin in use: default whatever that is

### Additional Context

This works fine in single-port scenario.
