### ISSUE TITLE
token with AccessorID '00000000-0000-0000-0000-000000000002' lacks permission 'service:write' on "demo20221017"

### ISSUE THREAD

**Issue by Din-He** [hashicorp/consul-k8s#1640]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue
k8s环境下使用helm部署consul。之后在springboot应用中使用global-management  token将服务注册到consul报错
token with AccessorID '00000000-0000-0000-0000-000000000002' lacks permission 'service:write' on "demo20221017"

### Reproduction Steps
1. 我自定义了一个config-secure.yaml如下：
```yaml
# Configure global settings in this section.
global:
  name: consul
  # Bootstrap ACLs within Consul. This is highly recommended.
  datacenter: test-hdy
  image: hashicorp/consul:1.12.3
  enabled: true
  gossipEncryption:
    autoGenerate: true
  acls:
    manageSystemACLs: true
# Configure your Consul servers in this section.
server:
  # Specify three servers that wait until all are healthy to bootstrap the Consul cluster.
  replicas: 1
  # Specify the resources that servers request for placement. These values will serve a large environment.
  resources:
    requests:
      memory: 200Mi
      cpu: 200m
    limits:
      memory: 200Mi
      cpu: 200m
  storageClass: nfs-client
  exposeService:
    enabled: true
    type: NodePort
    nodePort:
      http: 30088
  securityContext:
    runAsNonRoot: false
    runAsUser: 0
# Configure Consul clients in this section
client:
  # Specify the resources that clients request for deployment.
  resources:
    requests:
      memory: 200Mi
      cpu: 200m
    limits:
      memory: 200Mi
      cpu: 200m
# Enable and configure the Consul UI.
ui:
  enabled: true
  service:
    enabled: true
# Enable Consul connect pod injection
connectInject:
  enabled: true
controller:
  enabled: true

```
这里面的 storageClass: nfs-client 是我提前使用nfs在k8s中安装好了一个 storageClass名字叫 nfs-client。
2. 我运行了命令
```shell
helm install consul hashicorp/consul --values config-secure.yaml --create-namespace --namespace consul1 --atomic --debug
```
kubectl get pod -n consul1 查看所有pod运行都正常，其他组件也是正常的，然后我在chrom输入ip:30088/ 访问ui页面看到services中consul instance也是正常的
![1666336775388](https://user-images.githubusercontent.com/66732359/197136589-f8b87ad3-56ee-4ba6-9128-d67320f9366d.jpg)
同时自动生成了一些token
![image](https://user-images.githubusercontent.com/66732359/197136666-8d4affdd-9d68-462d-912d-ee0f196f903d.png)
3. 然后在springboot应用中使用global-management  token（上面截图中e985dc44）企图将服务注册到consul上，然后程序报错
 com.ecwid.consul.v1.OperationException: OperationException(statusCode=403, statusMessage='Forbidden', statusContent='Permission denied: token with AccessorID '00000000-0000-0000-0000-000000000002' lacks permission 'service:write' on "demo20221017"')  其中demo20221017是我的应用名称。
![1666336923003](https://user-images.githubusercontent.com/66732359/197137058-71a8c535-e90c-4b97-a429-fd8f9768c6da.jpg)
我自己分析：报错显示0002这个token没有写入服务的权限，但是我并没有用那个token我用的是global-management  token。（这也正是我的问题，我并没有用0002那个token，他为什么会自动用0002token请求consul，导致报错呢？）据我所知， 00002是anonymous-token-policy 应该是consul默认创建的权限非常小的一个token。
