### ISSUE TITLE
Consul Client can't connect to external server on VM in the same network.

### ISSUE THREAD

**Issue by sMteX** [hashicorp/consul-k8s#1708]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

Consul *Client* deployed in Kubernetes can't connect to the existing Consul Server outside the Kube cluster (on a VM) **even though it has the CA cert and https verification is disabled**. I have deployed a Consul Server on a VM, then setup a Consul Client on another VM, and I'm trying to join another Consul Client from a Kubernetes cluster. I have followed various docs and also imitating the settings that are being used when deploying servers and clients on Kube. 

I can somewhat get the Client and Server to communicate (though I'm dissatisfied that I had to provide the client certs too (because of Envoy proxy, namely `consul connect envoy`) but I can deal with that). In the UI, everything looks green, but I can't figure out what I'm doing wrong when I try joining K8s cluster into the service mesh.

### Reproduction Steps
Preface - all machines/VMs exist on the same private network and to my knowledge, there shouldn't be a firewall interfering with requests.

#### Consul Server
Set up a Consul Server on a VM 1 (IP `192.168.1.230`).  
<details>
  <summary>Server config</summary>

```hcl
bind_addr = "0.0.0.0"
bootstrap_expect = 1
client_addr = "0.0.0.0"
connect {
  enabled = true
}
datacenter = "dc1"
log_level = "DEBUG"
data_dir = "/etc/consul/data"
domain = "consul"
ports {
  # defaults, for clarity
  dns = 8600
  serf_lan = 8301
  serf_wan = 8302
  server = 8300
  # overrides
  https = 8501
  http = -1
  grpc = 8502
}
recursors = []
retry_join = ["127.0.0.1:8301"]
server = true
ui_config {
  enabled = true
}
encrypt = "..."
tls {
  defaults {
    ca_file = "/etc/consul/config/consul-agent-ca.pem"
    cert_file = "/etc/consul/config/dc1-server-consul-0.pem"
    key_file = "/etc/consul/config/dc1-server-consul-0-key.pem"
    verify_outgoing = true
    verify_incoming = true
  }
  https {
    // to allow Kube server to join
    verify_incoming = false
  }
  grpc {
    verify_incoming = false
  }
  internal_rpc {
    verify_server_hostname = true
  }
}
auto_encrypt {
  allow_tls = true
}
acl {
  enabled = true
  default_policy = "deny"
  down_policy = "extend-cache"
  enable_token_persistence = true
}
```
</details>

Then the following:
- Created a CA cert (`consul tls ca create`)
- Server cert (`consul tls cert create -server`)
- started the server
- created default DNS policy (node read, service read), server policy (write on all server nodes)
- created tokens to both policies, assigned to the server's agent

#### Consul Client
Set up a Client node on a different VM (IP `192.168.1.233`)

<details>
  <summary>Client config</summary>

```hcl
server = false
datacenter = "dc1"
domain = "consul"
bind_addr = "0.0.0.0"
client_addr = "0.0.0.0"
log_level = "DEBUG"

retry_join = ["192.168.1.230:8301"]
leave_on_terminate = true

ports {
  # defaults, for clarity
  dns = 8600
  serf_lan = 8301
  serf_wan = 8302
  server = 8300
  # overrides
  https = 8501
  http = -1
  grpc = 8502
}

enable_script_checks = false
enable_central_service_config = true

data_dir = "/etc/consul/data"
encrypt = "..."

tls {
  defaults {
    ca_file = "/etc/consul/config/consul-agent-ca.pem"
    verify_outgoing = true
    verify_incoming = false
  }
  grpc {
    verify_incoming = false
  }
  // https {
  //   verify_incoming = true
  // }
  internal_rpc {
    verify_server_hostname = true
  }
}
auto_encrypt {
  tls = true
}
acl {
  enabled = true
  default_policy = "deny"
  down_policy = "extend-cache"
}
acl {
  tokens {
    # DNS token
    default = "..."
    # Consul Client 1 token
    agent = "..."
  }
}
// tls {
//  defaults {
//    cert_file = "/etc/consul/config/dc1-client-consul-0.pem"
//     key_file = "/etc/consul/config/dc1-client-consul-0-key.pem"
//  }
// }
auto_encrypt {
  ip_san = ["192.168.1.233"]
}
```

</details>

Additional steps/info:
- created a "general" client policy (node read, service write), and then a client-specific policy (node write, agent write for that specific node), created token that combined those 2 policies (this is in `acl.tokens.agent`)
- copied the `consul-agent-ca.pem` and all the configs to the VM, installed Consul and started 

This mostly worked (I had to uncomment the `tls` block with cert/key files in order to get Envoy connected).

#### Kubernetes config
I followed https://developer.hashicorp.com/consul/docs/k8s/deployment-configurations/servers-outside-kubernetes 
<details>
  <summary>Helm values</summary>

```yaml
# https://developer.hashicorp.com/consul/docs/k8s/deployment-configurations/servers-outside-kubernetes
global:
  enabled: false
  name: consul
  datacenter: dc1
  logLevel: DEBUG

  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: consul-bootstrap-token
      secretKey: token

  tls:
    enabled: true
    enableAutoEncrypt: true
    verify: false
    # caCert:
    #   secretName: consul-ca-cert-client
    #   secretKey: tls.crt
    # caKey:
    #   secretName: consul-ca-key-client
    #   secretKey: tls.key
  gossipEncryption:
    secretName: consul-gossip-encryption-key
    secretKey: key
  
client:
  enabled: true
  exposeGossipPorts: true
  join:
    - '192.168.1.230'
  extraConfig: |
    { "log_level": "debug" }

externalServers:
  enabled: true
  hosts: 
    - '192.168.1.230'
  # Kube API server
  k8sAuthMethodHost: 'https://192.168.1.150:443'

# maybe?
connectInject:
  enabled: true
controller:
  enabled: true
syncCatalog:
  enabled: true
dns:
  enabled: true
```

</details>

I copied the bootstrap token, encryption key, created K8s secrets in proper namespace. Then I tried copying various certs - CA, client, new client, server certs... (from the server, where they were created) and also creating secrets from them that the Pods could mount.

### Logs

I expected this setup to somewhat work, however the only thing that happens is that Kubernetes pods cannot use the CA cert to communicate with the Server. For example `server-acl-init` job hangs forever with a spam of following error:

```
[ERROR] Failure: calling /agent/self to get datacenter: err="Get \"https://192.168.1.230:8501/v1/agent/self\": x509: certificate is valid for 127.0.0.1, not 192.168.1.230"
```

I've tried connecting to the pod and inside it running `curl -k https://192.168.1.230:8501/v1/agent/self` which lets me talk to the server (well actually kicks me out but with ACL token related error message which is kinda expected) so there has to exist a connection.

### Expected behavior

As I followed the documentation, I expected the Kubernetes part of the Consul datacenter to just work. Either I'm missing something blatantly obvious or the documentation might not be as detailed as needs to be. 

### Environment details
- Kubernetes version `1.24.6`, CNI `Calico`
- Consul server version `1.13.3`
- From the `Chart.yaml`:
    - `consul - 1.13.2`
    - `consul-k8s-control-plane - 0.49.0`
    - `envoy - 1.23.1`
    - chart version `1.13.2`

### Additional Context
- https://developer.hashicorp.com/consul/docs/k8s/deployment-configurations/servers-outside-kubernetes
- https://developer.hashicorp.com/consul/tutorials/get-started-vms/virtual-machine-gs-deploy
- https://developer.hashicorp.com/consul/tutorials/get-started-vms/virtual-machine-gs-service-discovery
