### ISSUE TITLE
[k8s][ingress-nginx] Upstream prematurely closed connection with transparent proxy enabled for Consul 1.14+

### ISSUE THREAD

**Issue by chebykinn** [hashicorp/consul-k8s#1761]
#### Question

Hi, I have a configuration of k8s services with ingress-nginx, and starting with Consul 1.14+ I always receive `502 Bad Gateway` while trying to access services through nginx, more specifically I get an error: `upstream prematurely closed connection while reading the response header from upstream`.

#### Service configuration

Deployment
```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: service1
  namespace: ns1
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: service1
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/transparent-proxy: 'true'
    spec:
      containers:
        - name: service1
          image: img
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
```

Ingress:
```yaml
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: service1-ingress
  namespace: ns1
  annotations:
    cert-manager.io/issuer: cert-issuer
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - host.example.com
      secretName: host.example.com-tls
  rules:
    - host: host.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service1
                port:
                  number: 80
```

Service:
```yaml
kind: Service
apiVersion: v1
metadata:
  name: service1
  namespace: ns1
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: service1
  type: ClusterIP

```

ServiceDefaults:
```yaml
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: service1
  namespace: ns1
spec:
  transparentProxy:
    dialedDirectly: true
```

### Helm Configuration

Consul:

```yaml
global:
  name: consul
  datacenter: dc1
  enabled: true
server:
  replicas: 3
client:
  enabled: true
  tolerations: |
    - key: "node-role.kubernetes.io/ingress"
      operator: "Exists"
connectInject:
  enabled: true
controller:
  enabled: true
```

ingress-nginx:
```yaml
controller:
  tolerations:
    - key: "node-role.kubernetes.io/ingress"
      operator: "Exists"
  podAnnotations:
    consul.hashicorp.com/connect-inject: "true"
    consul.hashicorp.com/transparent-proxy: "true"
    consul.hashicorp.com/transparent-proxy-exclude-inbound-ports: "80,443,8000,9000,8443"
    consul.hashicorp.com/transparent-proxy-exclude-outbound-cidrs: "10.233.0.1/32"
  labels:
    consul.hashicorp.com/service-ignore: "true"
  service:
    type: NodePort
    nodePorts:
      http: "31085"
      https: "31086"
```
NOTE: `service-ignore` for nginx is set because it has two services and one of them should be excluded for consul.

### Logs

No errors from consul side, from nginx:

```
2022/11/30 23:36:51 [error] 25#25: *3637 upstream prematurely closed connection while reading response header from upstream, client: 10.233.97.0, server: host.example.com, request: "GET / HTTP/2.0", upstream: "http://10.233.107.52:80/", host: "host.example.com"
```
Here, `http://10.233.107.52:80/` is pod IP.

### Current understanding and Expected behavior

Ingress-nginx tries to access pods by their IP and with Consul 1.10.4-1.13.3 it's succeeding, but for anything above I get an error. 
I assume something changed and I need to update my configuration.

### Environment details

Consul versions that works: 1.10.4-1.13.3
Consul versions, which are not working: 1.14+
k8s version: 1.24.6

### Additional Context

There was an issue like that, it was solved by adding ServiceDefaults: https://github.com/hashicorp/consul-k8s/issues/916, and now, for new versions, it doesn't help.
