### ISSUE TITLE
ACL auth method login failed... unknown service hashicorp.consul.acl.ACLService

### ISSUE THREAD

**Issue by bwmetcalf** [hashicorp/consul-k8s#1798]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Issue

Upgrading secondary DC from 0.46.1 to 1.0.2

### Reproduction Steps

Our primary DC is still running 0.46.1.  Upgrading our secondary DC to 1.0.2 results in the mesh-gateway and injector pods throwing the following error:
```
{"@level":"error","@message":"ACL auth method login failed","@module":"consul-server-connection-manager","@timestamp":"2022-12-14T17:11:26.363913Z","error":"rpc error: code = Unimplemented desc = unknown service hashicorp.consul.acl.ACLService"}
{"@level":"error","@message":"connection error","@module":"consul-server-connection-manager","@timestamp":"2022-12-14T17:11:26.364113Z","error":"rpc error: code = Unimplemented desc = unknown service hashicorp.consul.acl.ACLService"}
```

Below is our `values.yaml`:
```
global:
  name: consul
  datacenter: ${datacenter_name}

  logJSON: true

  gossipEncryption:
    secretName: ${encryption_secret_name}
    secretKey: ${encryption_secret_key}

  acls:
    manageSystemACLs: true
    createReplicationToken: ${is_primary_dc}

  tls:
    enabled: true

    caCert:
      secretName: ${tls_secret_name}
      secretKey: ${tls_ca_cert_secret_key}
    caKey:
      secretName: ${tls_secret_name}
      secretKey: ${tls_ca_key_secret_key}

  # Settings related to federating with another Consul datacenter.
  federation:
    enabled: true
    createFederationSecret: ${is_primary_dc}

  consulSidecarContainer:
    resources:
      requests:
        memory: "50Mi"
        cpu: "20m"
      limits:
        memory: "100Mi"
        cpu: "20m"

controller:
  enabled: true
  priorityClassName: ${priority_class_name}

  resources:
    limits:
      cpu: 500m
      memory: 50Mi
    requests:
      cpu: 100m
      memory: 50Mi

# Server, when enabled, configures a server cluster to run. This should
# be disabled if you plan on connecting to a Consul cluster external to
# the Kube cluster.
server:
  replicas: ${server_replicas}
  priorityClassName: ${priority_class_name}
  storage: 10Gi
  storageClass: null

  # This value is used to carefully
  # control a rolling update of Consul server agents. This value specifies the
  # partition (https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#partitions)
  # for performing a rolling update. Please read the linked Kubernetes documentation
  # and https://www.consul.io/docs/k8s/upgrade#upgrading-consul-servers for more information.
  updatePartition: ${update_partition}

  # extraConfig is a raw string of extra configuration to set with the
  # server. This should be JSON.
  extraConfig: |
    ${server_extra_config}

  annotations: |
    "tags.datadoghq.com/env": "${stage}"
    "tags.datadoghq.com/service": "consul-server"
    "tags.datadoghq.com/version": "${chart_version}"

  resources:
    requests:
      memory: 2Gi
    limits:
      memory: null
      cpu: null

client:
  enabled: true

  priorityClassName: ${priority_class_name}

  # extraConfig is a raw string of extra configuration to set with the
  # client. This should be JSON.
  extraConfig: |
    ${client_extra_config}

  # updateStrategy for the DaemonSet.
  # See https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/#daemonset-update-strategy.
  # This should be a multi-line string mapping directly to the updateStrategy
  updateStrategy: ${indent(2, client_update_strategy)}

  annotations: |
    "tags.datadoghq.com/env": "${stage}"
    "tags.datadoghq.com/service": "consul-client"
    "tags.datadoghq.com/version": "${chart_version}"

  resources:
    requests:
      memory: 600Mi
      cpu: 100m
    limits:
      memory: 1000Mi
      cpu: 250m

  # Toleration Settings for Client pods
  # This should be a multi-line string matching the Toleration array
  # in a PodSpec.
  # The example below will allow Client pods to run on every node
  # regardless of taints
  #
  # ```yaml
  # tolerations: |
  #   - operator: Exists
  # ```
  %{ if client_node_tolerations != "" }
  tolerations: |
    ${indent(4, client_node_tolerations)}
  %{ endif ~}

ui:
  service:
    enabled: true
    type: NodePort
    nodePort:
      https: ${ui_node_port}

syncCatalog:
  # True if you want to enable the catalog sync. Set to "-" to inherit from
  # global.enabled.
  enabled: false
  default: false # true will sync by default, otherwise requires annotation
  addK8SNamespaceSuffix: false
  toConsul: false
  toK8S: false

# ConnectInject will enable the automatic Connect sidecar injector.
connectInject:
  enabled: "-"
  replicas: 3
  default: false # true will inject by default, otherwise requires annotation
  priorityClassName: ${priority_class_name}

  transparentProxy:
    defaultEnabled: false

  resources:
    requests:
      memory: "250Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "250m"

# Mesh Gateways enable Consul Connect to work across Consul datacenters.
meshGateway:
  enabled: true
  replicas: 2
  containerPort: 443
  priorityClassName: ${priority_class_name}

  resources:
    requests:
      cpu: 100m
      memory: 350Mi
    limits:
      cpu: 500m
      memory: 600Mi

  annotations: |
    "tags.datadoghq.com/env": "${stage}"
    "tags.datadoghq.com/service": "consul-mesh-gateway"
    "tags.datadoghq.com/version": "${chart_version}"

  service:
    type: NodePort
    nodePort: ${mesh_gateway_node_port}

  topologySpreadConstraints: |
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app: {{ template "consul.name" . }}
          release: "{{ .Release.Name }}"
          component: mesh-gateway
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app: {{ template "consul.name" . }}
          release: "{{ .Release.Name }}"
          component: mesh-gateway

# Let's get that sidecar to have a higher limit
consulSidecarContainer:
   resources:
      requests:
        memory: "25Mi"
      limits:
        memory: "100Mi"
```
