### ISSUE TITLE
12 node(s) didn't have free ports for the requested pod ports, consul not starting

### ISSUE THREAD

**Issue by codex70** [hashicorp/consul-k8s#1802]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

When using the latest version of the helm template (1.0.2) consul will not start when exposing ports

### Reproduction Steps

Steps to reproduce this issue, eg:

1. When running helm install with the following `values.yml`:
```
global:
  name: consul
  federation:
    enabled: true
    createFederationSecret: true
  tls:
    enabled: true
    enableAutoEncrypt: true
    verify: true
  acls:
    manageSystemACLs: true
    createReplicationToken: true
  gossipEncryption:
    secretName: consul-gossip-encryption-key
    secretKey: key

client:
  enabled: true
  exposeGossipPorts: true # exposes client gossip ports as hostPorts
server:
  exposeGossipAndRPCPorts: true # exposes the server gossip and RPC ports as hostPorts
  ports:
    serflan:
      port: 9301
  replicas: 3
  securityContext:
    runAsNonRoot: false
    runAsUser: 0

connectInject:
  enabled: true
  default: false
controller:
  enabled: true
meshGateway:
  enabled: true
```
2. The helm install fails with the following error:
```
Error: INSTALLATION FAILED: failed post-install: timed out waiting for the condition
```

3. Server pods are stuck in pending, client pods are either pending or Init:0/1
4. Occasionally 1 of the server pods will start as expected.
### Logs
Log messages vary slightly, but generally look like the following:
```
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  21s   default-scheduler  0/12 nodes are available: 1 node(s) didn't match pod anti-affinity rules, 12 node(s) didn't have free ports for the requested pod ports, 8 node(s) had no available volume zone. preemption: 0/12 nodes are available: 4 No preemption victims found for incoming pod, 8 Preemption is not helpful for scheduling.
```

### Expected behavior
Consul deploys as expected.

### Environment details
- Kubernetes version: v1.24.1 (also tested on 1.23.4)
- Cloud Provider: Oracle
- Cluster has 2 nodepools with 6 nodes in each pool

### Additional Context
3 PVCs appear to be created and bound correctly
There is nothing else running on this kubernetes cluster, Consul is the first thing that I'm trying to install.

Gossip encryption secret is created before deploying using the following command.
```
kubectl create secret generic consul-gossip-encryption-key --from-literal=key=$(consul keygen) -n consul

```

NOTE: the configuration worked without issue with helm chart version: 0.48.0 and kubernetes 1.23.4

**Comment by codex70** [comment]
This does look like it might be some sort of clash between the server and the client agents. If I disable the clients, consul seems to start, but when I try connecting vault with consul as backend storage I get a connection refused error:
```
[WARN]  storage migration check error: error="Get \"https://X.X.X.X:8501/v1/kv/vault/core/migration\": dial tcp X.X.X.X:8501: connect: connection refused"
```

**Comment by david-yu** [comment]
Hi @codex70 , client agents are only available for service discovery use cases and for when using Vault as a storage backend. Consul K8s 1.0.x and above no longer support clients being enabled when `connectInject.enabled` is set to true. We also recommend using a separate Consul K8s cluster for Vault storage backend or using integrated storage with Vault.

**Comment by codex70** [comment]
Hi @david-yu , that's exactly the scenario I have, I need both vault backend storage and service discovery as well as connectInject.

Creating a separate cluster for Vault is going to be difficult, we use vault for storing a lot of secrets related to deployment of applications, auto generating secrets and storing them in the vault so as not to put them in code etc. The only option in that case would be to use integrated storage with Vault.

Also, if we are using Consul for service discovery as well as connectInject, how would that look?

**Comment by david-yu** [comment]
In your case, I would look at going to integrated storage if you are looking to use the latest version of Consul K8s. Or you could stick with 0.49.x which we'll support specifically for Consul 1.13.x and below. 

In the future, the Vault K8s team is looking to work on some enhancements to support Vault Storage backend with Consul K8s without any Consul Clients being available.

**Comment by david-yu** [comment]
Hope you have an answer in the interim. I've notified the Vault team about your use case. Could you file a feature request on https://github.com/hashicorp/vault-k8s to describe your use case and how you'd like Vault K8s to use Consul K8s without Consul clients being deployed? Sorry I don't have a better answer here. Will close this issue for now.

**Comment by codex70** [comment]
Hi @david-yu, I'll definitely open a feature request for the vault, however that still leaves me confused as to how I implement service discovery with new version of Consul. If there are no agents, how do you do service discovery from clients?

Perhaps I'm missing something obvious, so do you have any recommendations, or could you point me to some documentation that would help me to be able to deploy a mixed environment with connect inject for some services, but others relying on more traditional service discovery, and combining the two?

**Comment by david-yu** [comment]
You can still deploy clients as a daemonset with clients.enabled set to `true` as that still works with Consul 1.14: https://github.com/hashicorp/consul-k8s/blob/6ec4db232515017b160689f4fcf82e0346747230/charts/consul/values.yaml#L1180. With the new version of Consul K8s, however mesh is not compatible with clients any longer and you'll need to leverage Catalog sync to do service discovery on Kubernetes. For Vault K8s they also will move away from using client agents and will leverage libraries we provide in the future to perform service discovery without agents.

**Comment by codex70** [comment]
Hi @david-yu, so I need to have 
```
clients enabled: false
```
If I want to enable connectInject.

How do I enable access to the API? Without clients enabled I get `connection refused` when I try to access port 8501.

Without access to the API on port 8501 I am no longer able to do service discovery.

**Comment by codex70** [comment]
Hi @david-yu, it looks like the issue I opened is actually related to:
```
client:
  enabled: true
  exposeGossipPorts: true # exposes client gossip ports as hostPorts
server:
  exposeGossipAndRPCPorts: true # exposes the server gossip and RPC ports as hostPorts
```
I don't think expose gossip ports is needed any more, and by removing those lines from my configuration everything now works with the new version of consul, including multi cluster federation, api gateways and service discovery. Before exposing gossip ports was causing the issue where nodes did not have free ports.

I can also confirm that I did not need to make any changes to the vault configuration, that continued to work for me as it did before (although I understand this is not fully aligned with the new way of working).

It is probably worth bearing this in mind for anyone who is migrating a configuration or deployment from 0.4X.X to 1.X

I am going to run some more testing to make sure this is now working fully as expected.
