### ISSUE TITLE
Having issues upgrading to 1.0.2

### ISSUE THREAD

**Issue by narendrapatel** [hashicorp/consul-k8s#1809]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue
We are trying to upgrade from 0.49.0 to 1.0.2 but in the process of the same we get the below error:
```
{"@level":"error","@message":"connection error","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:44:18.396129Z","error":"failed to switch to Consul server \"xx.xx.xx.xx:8503\": target sub-connection is not ready (state=TRANSIENT_FAILURE)"}
```
We get the above log in both the consul-server-acl-init and consul-connect-injector pods.
We are using External Consul Servers.
Checked out the issue mentioned in https://github.com/hashicorp/consul-k8s/issues/1742 but we've already configured `tlsServerName` and set the grpcPort to `8503`. Verified that I can telnet to 8503 from the K8s cluster.

### Logs
<details>
  <summary>consul-server-acl-init</summary>

```
{"@level":"debug","@message":"backoff","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:36:16.066669Z","retry after":480091793}
{"@level":"info","@message":"trying to connect to a Consul server","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:36:16.547271Z"}
{"@level":"trace","@message":"Watcher.nextServer","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:36:16.547334Z","addrs":"[xx.xx.xx.xx:8503]"}
{"@level":"debug","@message":"Resolved DNS name","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:36:16.574023Z","ip-addrs":[{"IP":"xx.xx.xx.xx","Zone":""}],"name":"consul01.internal"}
{"@level":"info","@message":"discovered Consul servers","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:36:16.574067Z","addresses":[{"IP":"xx.xx.xx.xx","Port":8503,"Zone":""}]}
{"@level":"info","@message":"current prioritized list of known Consul servers","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:36:16.574085Z","addresses":[{"IP":"xx.xx.xx.xx","Port":8503,"Zone":""}]}
{"@level":"trace","@message":"Watcher.connect","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:36:16.574096Z","addr":{"IP":"xx.xx.xx.xx","Port":8503,"Zone":""}}
{"@level":"debug","@message":"switching to Consul server","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:36:16.574105Z","address":{"IP":"xx.xx.xx.xx","Port":8503,"Zone":""}}
{"@level":"trace","@message":"Watcher.switchServer","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:36:16.574113Z","to":{"IP":"xx.xx.xx.xx","Port":8503,"Zone":""}}
{"@level":"trace","@message":"clientConnWrapper.NewSubConn","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:36:16.574201Z","addrs":[{"Addr":"xx.xx.xx.xx:8503","ServerName":"","Attributes":null,"BalancerAttributes":null,"Type":0,"Metadata":null}]}
{"@level":"trace","@message":"balancer.UpdateSubConnState","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:36:16.574520Z","sc":{},"state":{"ConnectivityState":1,"ConnectionError":null}}
{"@level":"trace","@message":"balancer.UpdateSubConnState","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:36:16.576784Z","sc":{},"state":{"ConnectivityState":3,"ConnectionError":{}}}
{"@level":"trace","@message":"balancer.UpdateSubConnState","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:36:17.577808Z","sc":{},"state":{"ConnectivityState":0,"ConnectionError":{}}}
{"@level":"trace","@message":"balancer.UpdateSubConnState","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:36:17.578055Z","sc":{},"state":{"ConnectivityState":1,"ConnectionError":null}}
{"@level":"trace","@message":"balancer.UpdateSubConnState","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:36:17.580541Z","sc":{},"state":{"ConnectivityState":3,"ConnectionError":{}}}
{"@level":"trace","@message":"balancer.UpdateSubConnState","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:36:19.014529Z","sc":{},"state":{"ConnectivityState":0,"ConnectionError":{}}}
{"@level":"trace","@message":"balancer.UpdateSubConnState","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:36:19.014694Z","sc":{},"state":{"ConnectivityState":1,"ConnectionError":null}}
{"@level":"trace","@message":"balancer.UpdateSubConnState","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:36:19.017428Z","sc":{},"state":{"ConnectivityState":3,"ConnectionError":{}}}
{"@level":"trace","@message":"balancer.UpdateSubConnState","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:36:21.362309Z","sc":{},"state":{"ConnectivityState":0,"ConnectionError":{}}}
{"@level":"trace","@message":"balancer.UpdateSubConnState","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:36:21.362495Z","sc":{},"state":{"ConnectivityState":1,"ConnectionError":null}}
{"@level":"trace","@message":"balancer.UpdateSubConnState","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:36:21.365237Z","sc":{},"state":{"ConnectivityState":3,"ConnectionError":{}}}
{"@level":"trace","@message":"balancer.UpdateSubConnState","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:36:25.020758Z","sc":{},"state":{"ConnectivityState":0,"ConnectionError":{}}}
{"@level":"trace","@message":"balancer.UpdateSubConnState","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:36:25.021017Z","sc":{},"state":{"ConnectivityState":1,"ConnectionError":null}}
{"@level":"trace","@message":"balancer.UpdateSubConnState","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:36:25.023275Z","sc":{},"state":{"ConnectivityState":3,"ConnectionError":{}}}
{"@level":"trace","@message":"balancer.UpdateSubConnState","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:36:26.597537Z","sc":{},"state":{"ConnectivityState":4,"ConnectionError":null}}
{"@level":"debug","@message":"gRPC resolver failed to update connection address","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:36:26.597672Z","error":"bad resolver state"}
{"@level":"error","@message":"connection error","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:36:26.597707Z","error":"failed to switch to Consul server \"xx.xx.xx.xx:8503\": target sub-connection is not ready (state=TRANSIENT_FAILURE)"}
{"@level":"debug","@message":"backoff","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:36:26.597766Z","retry after":677009809}
```

</details>

<details>
  <summary>consul-connect-injector</summary>

```
{"@level":"debug","@message":"backoff","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:44:05.893003Z","retry after":2450616849}
{"@level":"info","@message":"trying to connect to a Consul server","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:44:08.343776Z"}
{"@level":"trace","@message":"Watcher.nextServer","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:44:08.343977Z","addrs":"[xx.xx.xx.xx:8503]"}
{"@level":"debug","@message":"Resolved DNS name","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:44:08.377803Z","ip-addrs":[{"IP":"xx.xx.xx.xx","Zone":""}],"name":"consul01.internal"}
{"@level":"info","@message":"discovered Consul servers","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:44:08.377849Z","addresses":[{"IP":"xx.xx.xx.xx","Port":8503,"Zone":""}]}
{"@level":"info","@message":"current prioritized list of known Consul servers","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:44:08.377868Z","addresses":[{"IP":"xx.xx.xx.xx","Port":8503,"Zone":""}]}
{"@level":"trace","@message":"Watcher.connect","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:44:08.377878Z","addr":{"IP":"xx.xx.xx.xx","Port":8503,"Zone":""}}
{"@level":"debug","@message":"switching to Consul server","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:44:08.377887Z","address":{"IP":"xx.xx.xx.xx","Port":8503,"Zone":""}}
{"@level":"trace","@message":"Watcher.switchServer","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:44:08.377897Z","to":{"IP":"xx.xx.xx.xx","Port":8503,"Zone":""}}
{"@level":"trace","@message":"clientConnWrapper.NewSubConn","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:44:08.377953Z","addrs":[{"Addr":"xx.xx.xx.xx:8503","ServerName":"","Attributes":null,"BalancerAttributes":null,"Type":0,"Metadata":null}]}
{"@level":"trace","@message":"balancer.UpdateSubConnState","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:44:08.378182Z","sc":{},"state":{"ConnectivityState":1,"ConnectionError":null}}
{"@level":"trace","@message":"balancer.UpdateSubConnState","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:44:08.381138Z","sc":{},"state":{"ConnectivityState":3,"ConnectionError":{}}}
{"@level":"trace","@message":"balancer.UpdateSubConnState","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:44:09.382125Z","sc":{},"state":{"ConnectivityState":0,"ConnectionError":{}}}
{"@level":"trace","@message":"balancer.UpdateSubConnState","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:44:09.382347Z","sc":{},"state":{"ConnectivityState":1,"ConnectionError":null}}
{"@level":"trace","@message":"balancer.UpdateSubConnState","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:44:09.385924Z","sc":{},"state":{"ConnectivityState":3,"ConnectionError":{}}}
{"@level":"trace","@message":"balancer.UpdateSubConnState","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:44:10.748187Z","sc":{},"state":{"ConnectivityState":0,"ConnectionError":{}}}
{"@level":"trace","@message":"balancer.UpdateSubConnState","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:44:10.748364Z","sc":{},"state":{"ConnectivityState":1,"ConnectionError":null}}
{"@level":"trace","@message":"balancer.UpdateSubConnState","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:44:10.750945Z","sc":{},"state":{"ConnectivityState":3,"ConnectionError":{}}}
{"@level":"trace","@message":"balancer.UpdateSubConnState","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:44:13.689827Z","sc":{},"state":{"ConnectivityState":0,"ConnectionError":{}}}
{"@level":"trace","@message":"balancer.UpdateSubConnState","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:44:13.690017Z","sc":{},"state":{"ConnectivityState":1,"ConnectionError":null}}
{"@level":"trace","@message":"balancer.UpdateSubConnState","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:44:13.692605Z","sc":{},"state":{"ConnectivityState":3,"ConnectionError":{}}}
{"@level":"trace","@message":"balancer.UpdateSubConnState","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:44:18.396051Z","sc":{},"state":{"ConnectivityState":4,"ConnectionError":null}}
{"@level":"debug","@message":"gRPC resolver failed to update connection address","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:44:18.396105Z","error":"bad resolver state"}
{"@level":"error","@message":"connection error","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:44:18.396129Z","error":"failed to switch to Consul server \"xx.xx.xx.xx:8503\": target sub-connection is not ready (state=TRANSIENT_FAILURE)"}
{"@level":"debug","@message":"backoff","@module":"consul-server-connection-manager","@timestamp":"2022-12-20T10:44:18.396142Z","retry after":1942014773}
```

</details>

### Environment details
<details>
  <summary>Environment variables for consul-server-acl-init</summary>

```
env:
- name: NAMESPACE
  valueFrom:
    fieldRef:
      apiVersion: v1
      fieldPath: metadata.namespace
- name: POD_NAME
  valueFrom:
    fieldRef:
      apiVersion: v1
      fieldPath: metadata.name
- name: CONSUL_ADDRESSES
  value: consul01.internal
- name: CONSUL_GRPC_PORT
  value: "8503"
- name: CONSUL_HTTP_PORT
  value: "8501"
- name: CONSUL_DATACENTER
  value: dc1
- name: CONSUL_API_TIMEOUT
  value: 5s
- name: CONSUL_USE_TLS
  value: "true"
- name: CONSUL_CACERT_FILE
  value: /consul/tls/ca/tls.crt
- name: CONSUL_TLS_SERVER_NAME
  value: server.dc1.consul
```

</details>
<details>
  <summary>Environment variables for consul-connect-injector</summary>

```
env:
- name: NAMESPACE
  valueFrom:
    fieldRef:
      apiVersion: v1
      fieldPath: metadata.namespace
- name: POD_NAME
  valueFrom:
    fieldRef:
      apiVersion: v1
      fieldPath: metadata.name
- name: CONSUL_ADDRESSES
  value: consul01.internal
- name: CONSUL_GRPC_PORT
  value: "8503"
- name: CONSUL_HTTP_PORT
  value: "8501"
- name: CONSUL_DATACENTER
  value: dc1
- name: CONSUL_API_TIMEOUT
  value: 5s
- name: CONSUL_USE_TLS
  value: "true"
- name: CONSUL_CACERT_FILE
  value: /consul/tls/ca/tls.crt
- name: CONSUL_TLS_SERVER_NAME
  value: server.dc1.consul
- name: CONSUL_LOGIN_AUTH_METHOD
  value: test-consul-k8s-component-auth-method
- name: CONSUL_LOGIN_DATACENTER
  value: dc1
- name: CONSUL_LOGIN_META
  value: component=connect-injector,pod=$(NAMESPACE)/$(POD_NAME)

```

</details>

<details>
  <summary>values.yaml</summary>

```
---
global:
  name: test-consul
  image: "hashicorp/consul:1.14.2"
  logLevel: "trace"
  datacenter: dc1
  imageConsulDataplane: "hashicorp/consul-dataplane:1.0.0"
  imageK8S: "hashicorp/consul-k8s-control-plane:1.0.2"
  logJSON: true
  tls:
    enabled: true
    enableAutoEncrypt: true
    httpsOnly: false
    caCert:
      secretName: consul-ca-certs
    caKey:
      secretName: consul-ca-certs
  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: consul-acl-bootstrap-token
      secretKey: acl-bootstrap-token
  metrics:
    enabled: true
    enableAgentMetrics: true
server:
  enabled: false
externalServers:
  enabled: true
  hosts: &servers ["consul01.internal", "consul02.internal", "consul03.internal"]
  httpsPort: 8501
  grpcPort: 8503
  tlsServerName: server.dc1.consul
  k8sAuthMethodHost: https://xx.xx.xx.xx
connectInject:
  consulNode:
    meta:
      side: k8s
  priorityClassName: "core-critical"
  enabled: true
  initContainer:
    resources:
      requests:
        memory: "150Mi"
        cpu: "50m"
      limits:
        memory: "150Mi"
        cpu: "50m"
  resources:
    requests:
      memory: "100Mi"
      cpu: "1"
    limits:
      memory: "100Mi"
      cpu: "1"
  sidecarProxy:
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "100Mi"
        cpu: "100m"
```

</details>
<details>
  <summary>Consul server config</summary>

```
{
    "acl": {
        "default_policy": "deny",
        "down_policy": "extend-cache",
        "enabled": true,
        "tokens": {
            "agent": "73554c8d-596e-3e42-be95-c7e35d8b97db",
            "default": "0d344dde-8074-4db0-9fba-af915300a6e9"
        }
    },
    "auto_encrypt": {
        "allow_tls": true
    },
    "bootstrap": true,
    "client_addr": "0.0.0.0",
    "connect": {
        "enabled": true
    },
    "data_dir": "/opt/consul",
    "datacenter": "dc1",
    "log_level": "INFO",
    "node_meta": {
        "side": "vm"
    },
    "node_name": "consul01.internal",
    "ports": {
        "https": 8501
    },
    "retry_join": [
        "consul01.internal",
        "consul02.internal",
        "consul03.internal"
    ],
    "server": true,
    "telemetry": {
        "disable_hostname": true,
        "prometheus_retention_time": "1h"
    },
    "tls": {
        "defaults": {
            "ca_file": "/opt/consul/tls/consul-agent-ca.pem",
            "cert_file": "/opt/consul/tls/dc-server-consul-0.pem",
            "key_file": "/opt/consul/tls/dc-server-consul-0-key.pem",
            "verify_incoming": true,
            "verify_outgoing": true
        },
        "https": {
            "verify_incoming": false
        },
        "internal_rpc": {
            "verify_server_hostname": true
        }
    },
    "ui_config": {
        "enabled": true,
        "metrics_provider": "prometheus",
        "metrics_proxy": {
            "base_url": "http://thanos:10904"
        }
    }
}
```
</details>

Kubernetes version: Facing issue both on out QA(v1.24) and Test(v1.25) cluster.
Kubernetes Platform: GCP GKE
(Some values have been redacted)

**Comment by david-yu** [comment]
@narendrapatel This looks like a transient failure are you experiencing any operational issues on the cluster that may suggest this log message is something is not working correctly?

**Comment by narendrapatel** [comment]
Hi @david-yu,
Yes the deployment fails and the consul-server-acl-init does not complete and the consul-connect-injector pods don't turn healthy causing the entire functionality to go down, disrupting all K8s cluster operations.

**Comment by david-yu** [comment]
Hi @narendrapatel could enable trace level logs to see what's perhaps going on the data plane container? There are perhaps some underlying issues that would tell us more what is going on.

**Comment by narendrapatel** [comment]
Hi @david-yu 
Didn't see the data plane container starting up. The deployment of 1.0.2 itself fails with the consul-server-acl-init not completing and consul-connect-injector not turning healthy and crashing. So we can't move forward with injection of pods and so don't have data plane container.
Have provided trace level logs for consul-server-acl-init and consul-connect-injector though.

**Comment by narendrapatel** [comment]
Hi @david-yu 
As mentioned in the ticket description we are using external consul servers.
With 1.0.x all consul k8s components directly call the consul server and it seems its done over TLS. Wanted to check if this is supported for external.
I've gone through https://github.com/hashicorp/consul-k8s/issues/1742 and have included all config mentioned. Have shared the values.yaml and consul server config in the starting comment. If TLS is supported for external then could there be some issue with my config? Not very sure with the gRPC changes needed from 1.14.x.

**Comment by narendrapatel** [comment]
Hi, is it possible for some one from consul team to have a look at this issue. We are stuck on this one for more than 2 weeks badly affecting service mesh induction efforts.

**Comment by morganbasset** [comment]
Hi, I have exactly the same error. My configuration is similar to yours, external server. 
I have create an issue here https://discuss.hashicorp.com/t/k8s-job-server-acl-init-failed-to-switch-to-consul-server/48010 
No solution for the moment.
Do you have any idea ?

**Comment by david-yu** [comment]
Hi @narendrapatel I would file a support ticket to get this bumped in priority. We prioritize issues on GitHub differently as we don't have an SLA to GitHub issues.

**Comment by narendrapatel** [comment]
@david-yu thanks. That would be really helpful.

**Comment by morganbasset** [comment]
Hi @narendrapatel, I have tested this, both grpc on 8502 and grpc_tls on 8503 are enabled. 
While looking in consul server log, I have seen an error like this : 

agent: [core][Channel #1 SubChannel #372] grpc: addrConn.createTransport failed to connect to {                                                     
                                            "Addr": "dc1-x.x.x.x:8300",                                                                                                                  
                                            "ServerName": "consulX.XXX",                                                                                                                      
                                            "Attributes": null,                                                                                                                               
                                            "BalancerAttributes": null,                                                                                                                       
                                            "Type": 0,                                                                                                                                        
                                            "Metadata": null                                                                                                                                  
                                          }. Err: connection error: desc = "transport: Error while dialing dial tcp x.x.x.x:0->x.x.x.x:8300: operation was canceled"

This previous error and the error in deployment "consul-consul-server-acl-init" appear at the same time. Dial tcp from zero port seem really strange.

**Comment by morganbasset** [comment]
Ok, I have found the problem.
@narendrapatel Did you set on your external server "cert_file" and "key_file" with the certificate use by https connection ?
I did and it work

**Comment by david-yu** [comment]
Hi @narendrapatel I meant you should file a support ticket to get this bumped in priority if you are a customer of HCP Consul.

**Comment by narendrapatel** [comment]
HI @david-yu, don't have HCP.  Using OSS consul.

**Comment by david-yu** [comment]
Hi @narendrapatel I think one hint is that the `externalServers.hosts` value has changed so the only valid entries you can have are a DNS name, an ip or exec string since we now use https://github.com/hashicorp/go-netaddrs

We did update our docs to include this snippet here

>The externalServers.hosts value must be provided and should be set to a DNS, an IP, or an exec= string with a command returning Consul IPs. Please see [this documentation](https://github.com/hashicorp/go-netaddrs) on how the exec= string works. Other values in the externalServers section are optional. Please refer to [Helm Chart configuration](https://developer.hashicorp.com/consul/docs/k8s/helm#h-externalservers) for more details.

I suspect this is the root of your problem.

**Comment by morganbasset** [comment]
Hi, my tls server configuration look like this : 
```
"ports": {
    "https": 8501,
    "grpc": 8502,
    "grpc_tls": 8503
  },
  "tls": [
    {
      "defaults": [
        {
          "ca_file": "/etc/consul.d/consul-agent-ca.pem",
          "cert_file": "/etc/consul.d/dll-server-consul-0.pem",
          "key_file": "/etc/consul.d/dll-server-consul-0-key.pem",
          "verify_outgoing": true,
          "verify_incoming": false
        }
      ],
      "internal_rpc": [
        {
          "verify_server_hostname": false,
          "tls_min_version": "TLSv1_3"
        }
      ],
      "https": [
        {
          "cert_file": "/etc/ssl/my.crt",
          "key_file": "/etc/ssl/my.key",
          "verify_incoming": false
        }
      ],
      "grpc": [
        {
        "use_auto_cert": false,
          "cert_file": "/etc/ssl/my.crt",
          "key_file": "/etc/ssl/my.key"
        }
      ]
    }
  ]
```

Helm chart values look like this 

```
client:
  affinity: null
  annotations: null
  containerSecurityContext:
    aclInit: null
    client: null
    tlsInit: null
  dataDirectoryHostPath: null
  dnsPolicy: null
  enabled: true
  exposeGossipPorts: false
  extraConfig: |
    {}
  extraContainers: []
  extraEnvironmentVars: {}
  extraLabels: null
  extraVolumes: []
  grpc: true
  hostNetwork: true
  image: null
  join:
    - consul1.yourdomain.com
    - consul2.yourdomain.com
    - consul3.yourdomain.com
  nodeMeta:
    host-ip: ${HOST_IP}
    pod-name: ${HOSTNAME}
  nodeSelector: null
  priorityClassName: ''
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 100
  serviceAccount:
    annotations: null
  tolerations: ''
  updateStrategy: null
connectInject:
  aclBindingRuleSelector: serviceaccount.name!=default
  aclInjectToken:
    secretKey: null
    secretName: null
  affinity: null
  annotations: null
  cni:
    cniBinDir: /opt/cni/bin
    cniNetDir: /etc/cni/net.d
    enabled: false
    logLevel: null
    multus: false
    namespace: null
    resourceQuota:
      pods: 5000
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 75m
        memory: 75Mi
    securityContext:
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0
    updateStrategy: null
  consulNamespaces:
    consulDestinationNamespace: default
    mirroringK8S: false
    mirroringK8SPrefix: ''
  consulNode:
    meta: null
  default: true
  disruptionBudget:
    enabled: true
    maxUnavailable: null
    minAvailable: null
  enabled: true
  envoyExtraArgs: null
  extraLabels: null
  failurePolicy: Fail
  image: null
  imageConsul: null
  initContainer:
    resources:
      limits:
        cpu: 50m
        memory: 150Mi
      requests:
        cpu: 50m
        memory: 25Mi
  k8sAllowNamespaces: *
  k8sDenyNamespaces: []
  logLevel: ''
  metrics:
    defaultEnableMerging: false
    defaultEnabled: '-'
    defaultMergedMetricsPort: 20100
    defaultPrometheusScrapePath: /metrics
    defaultPrometheusScrapePort: 20200
  namespaceSelector: |
    matchExpressions:
      - key: "kubernetes.io/metadata.name"
        operator: "NotIn"
        values: ["kube-system","local-path-storage"]
  nodeSelector: null
  overrideAuthMethodName: ''
  priorityClassName: ''
  replicas: 1
  resources:
    limits:
      cpu: 50m
      memory: 50Mi
    requests:
      cpu: 50m
      memory: 50Mi
  serviceAccount:
    annotations: null
  sidecarProxy:
    concurrency: 2
    resources:
      limits:
        cpu: null
        memory: null
      requests:
        cpu: null
        memory: null
  tolerations: null
  transparentProxy:
    defaultEnabled: true
    defaultOverwriteProbes: true
externalServers:
  enabled: true
  grpcPort: 8503
  hosts:
    - consul1.yourdomain.com
    - consul2.yourdomain.com
    - consul3.yourdomain.com
  httpsPort: 8501
  k8sAuthMethodHost: https://KUBERNETES_API_ADDRESS:6443
  skipServerWatch: false
  tlsServerName: null
  useSystemRoots: true
global:
  acls:
    bootstrapToken:
      secretKey: key
      secretName: bootstrap-token
    createReplicationToken: false
    manageSystemACLs: true
    nodeSelector: null
    partitionToken:
      secretKey: null
      secretName: null
    replicationToken:
      secretKey: null
      secretName: null
    tolerations: ''
  adminPartitions:
    enabled: false
    name: default
  consulAPITimeout: 5s
  datacenter: dc1
  domain: consul
  enableConsulNamespaces: false
  enablePodSecurityPolicies: false
  enabled: false
  enterpriseLicense:
    enableLicenseAutoload: true
    secretKey: null
    secretName: null
  federation:
    createFederationSecret: false
    enabled: false
    k8sAuthMethodHost: null
    primaryDatacenter: null
    primaryGateways: []
  gossipEncryption:
    autoGenerate: false
    secretKey: key
    secretName: consul-gossip-encryption-key
  image: hashicorp/consul:1.14.2
  imageConsulDataplane: hashicorp/consul-dataplane:1.0.0
  imageK8S: hashicorp/consul-k8s-control-plane:1.0.2
  imagePullSecrets: []
  logJSON: false
  logLevel: info
  metrics:
    agentMetricsRetentionTime: 1m
    enableAgentMetrics: false
    enableGatewayMetrics: true
    enabled: false
  name: null
  openshift:
    enabled: false
  peering:
    enabled: false
  recursors: []
  secretsBackend:
    vault:
      adminPartitionsRole: ''
      agentAnnotations: null
      ca:
        secretKey: ''
        secretName: ''
      connectCA:
        additionalConfig: |
          {}
        address: ''
        authMethodPath: kubernetes
        intermediatePKIPath: ''
        rootPKIPath: ''
      connectInject:
        caCert:
          secretName: null
        tlsCert:
          secretName: null
      connectInjectRole: ''
      consulCARole: ''
      consulClientRole: ''
      consulServerRole: ''
      controller:
        caCert:
          secretName: null
        tlsCert:
          secretName: null
      controllerRole: ''
      enabled: false
      manageSystemACLsRole: ''
  tls:
    caCert:
      secretKey: tls.crt
      secretName: consul-ca-cert
    caKey:
      secretKey: tls.key
      secretName: consul-ca-cert
    enableAutoEncrypt: true
    enabled: true
    httpsOnly: true
    serverAdditionalDNSSANs: []
    serverAdditionalIPSANs: []
    verify: true
```

The problem has been solved by setting my https certificate in the grpc certificate zone in consul server config. Hope it will help you
