### ISSUE TITLE
Prometheus scraping errors in injected consul-sidecar container

### ISSUE THREAD

**Issue by liad5h** [hashicorp/consul-k8s#1813]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue
When I configure configure the Consul sidecar to run a merged metrics server, I see the following logs in the `consul-sidecar` container:

```
2022-12-21T08:22:50.757Z [INFO]  Command configuration: enable-service-registration=false service-config="" consul-binary=consul sync-period=10s log-level=info enable-metrics-merging=true merged-metrics-port=20100 service-metrics-port=80 service-metrics-path=/stats/prometheus
2022-12-21T08:22:50.757Z [INFO]  Metrics is enabled, creating merged metrics server.
2022-12-21T08:22:50.757Z [INFO]  Running merged metrics server.
2022-12-21T08:23:15.657Z [ERROR] Received non-2xx status code scraping service metrics: code=404 response=""
2022-12-21T08:24:15.657Z [ERROR] Received non-2xx status code scraping service metrics: code=404 response=""
2022-12-21T08:25:15.583Z [ERROR] Received non-2xx status code scraping service metrics: code=404 response=""
```

The log is repeated every 1 minute - on every prometheus scrape.

By default, `connectInject.metrics.defaultPrometheusScrapePath` is set to `/metrics`.
I tried setting it to `/stats/prometheus` according to https://developer.hashicorp.com/consul/docs/v1.12.x/k8s/connect/observability/metrics but I still get the same behavior.

I believe that this error appears because scraping is done (also?) on port 80 (application port) which does not have a `/metrics` nor `/stats/prometheus` route.

### Reproduction Steps

Inject the sidecar container into a pod and check the logs of the `consul-sidecar` container.

### Logs

Added at issue description.

### Expected behavior

This error should be addressed and hopefully be more detailed.

### Environment details

Chart version 0.45.0 (Consul 1.12.2)
AWS EKS 1.21

<details>
  <summary>Helm Values</summary>

```
global:
  name: consul
  datacenter: us-east-1-qa
  enabled: false
  gossipEncryption:
    secretName: consul-gossip
    secretKey: key
  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: consul-bootstrap-acl
      secretKey: token
  metrics:
    enabled: true
    enableAgentMetrics: true
    agentMetricsRetentionTime: "1m"
    defaultPrometheusScrapePath: "/metrics"
    enableGatewayMetrics: false
client:
  enabled: true
  grpc: true
  exposeGossipPorts: true
  resources:
    requests:
      memory: "100Mi"
      cpu: "10m"
    limits:
      memory: "250Mi"
      cpu: "100m"
  extraConfig: |
    {
      "telemetry": {
        "disable_hostname": true
      }
    }

#

server:
  enabled: true
  replicas: 3
  exposeGossipAndRPCPorts: false
  connect: true
  extraConfig: |
    {
      "performance": {
        "raft_multiplier": 1
      },
      "telemetry": {
        "disable_hostname": true
      }
    }
#

  resources:
    requests:
      memory: "1Gi"
      cpu: "250m"
    limits:
      memory: "2Gi"
      cpu: "1000m"

#

prometheus:
  enabled: false

connectInject:
  enabled: true
  replicas: 2
  default: false
  metrics:
    defaultEnabled: true
    defaultEnableMerging: true
    defaultPrometheusScrapePath: "/stats/prometheus"
  resources:
    requests:
      memory: "50Mi"
      cpu: "50m"
    limits:
      memory: "250Mi"
      cpu: "300m"
controller:
  enabled: true
ui:
  enabled: true
  metrics:
    enabled: true
    provider: "prometheus"
    baseURL: http://prom-prometheus-server.prometheus.svc.cluster.local:443
  service:
    type: ClusterIP
```

</details>

### Additional Context

I tried working around this by adding the following annotations to my deployment:

```
consul.hashicorp.com/merged-metrics-port: "20100"
consul.hashicorp.com/service-metrics-path: /stats/prometheus
```

I also tried setting `consul.hashicorp.com/prometheus-scrape-port: "20100"` but that failed due to port binding error.
