### ISSUE TITLE
consul k8s CLI - GKE Autopilot: context deadline exceeded

### ISSUE THREAD

**Issue by HofmannZ** [hashicorp/consul-k8s#1818]
#### Question

We've ran consul-k8s on GKE of the past year, and works great! We're trying to spin up a new cluster with GKE Autopilot but getting the following error message back when running the install `rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource Secret "consul-auth-method" in namespace "consul": Get "https://172.16.0.2/api/v1/namespaces/consul/secrets/consul-auth-method": context deadline exceeded`

We've been poking around to find the cause but also wondering if anyone has seen this before?

### Helm Configuration

Steps to reproduce this issue:

1. When running helm install with the following `values.yaml`:
```
# Configure global settings in this section.
global:
  name: consul
  # Gossip encryption
  gossipEncryption:
    autoGenerate: true
  # Enables TLS across the cluster to verify authenticity of the Consul servers and clients.
  tls:
    enabled: true
    enableAutoEncrypt: true
  # Bootstrap ACLs within Consul. This is highly recommended.
  acls:
    manageSystemACLs: true
  # Configures metrics for Consul service mesh
  metrics:
    enabled: true
    enableAgentMetrics: true

# Configure your Consul servers in this section.
server:
  # Specify three servers that wait until all are healthy to bootstrap the Consul cluster.
  replicas: 3
  # Specify the resources that servers request for placement. These values will serve a large environment.
  storage: 40Gi
  storageClass: premium-rwo
  resources:
    requests:
      memory: "2Gi"
      cpu: "250m"
    limits:
      memory: "2Gi"
      cpu: "250m"

# Enable and configure the Consul UI.
ui:
  metrics:
    baseURL: http://prometheus-frontend.metrics.svc.cluster.local

# Enable Consul connect pod injection
connectInject:
  replicas: 2
  cni:
    enabled: true
    logLevel: info
    cniBinDir: "/home/kubernetes/bin"
    cniNetDir: "/etc/cni/net.d"
  metrics:
    defaultEnableMerging: true
```
2. View error

### Environment details

- `consul-k8s` version: v1.0.2
- `values.yaml` used to deploy the helm chart: See above
- Kubernetes version: v1.24.7-gke.900
- Cloud Provider (If self-hosted, the Kubernetes provider utilized): GKE
