### ISSUE TITLE
Conul inject unable to start on openshift

### ISSUE THREAD

**Issue by putz612** [hashicorp/consul-k8s#1820]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

After installing the helm chart version consul-1.0.2 on openshift I am having an issue starting any pod using the consul injector.  Seems like I am missing something simple but I am all YAML'd out.  

### Reproduction Steps

1. When running helm install with the following `values.yml`:
```
    global:
      image: registry.connect.redhat.com/hashicorp/consul:1.14.3-ubi
      imageK8S: registry.connect.redhat.com/hashicorp/consul-k8s-control-plane:1.0.1-ubi
      datacenter: k8sdc1
      openshift:
        enabled: true
      imagePullSecrets:
        - name: image-pull-secret
    server:
      replicas: 1
      bootstrapExpect: 1
      disruptionBudget:
        enabled: true
        maxUnavailable: 0
      enabled: true
    client:
      enabled: true
      grpc: true
    dns:
      enabled: true
      enableRedirection: false
    connectInject:
      enabled: true
      default: false
    controller:
      enabled: true
    ui:
      enabled: true
```
1. View error

Error creating: pods "static-server-6f64b45544-" is forbidden: unable to validate against any security context constraint: [provider "uid1000": Forbidden: not usable by user or serviceaccount, provider "anyuid": Forbidden: not usable by user or serviceaccount, spec.initContainers[0].securityContext.runAsUser: Invalid value: 0: must be in the ranges: [1001030000, 1001039999], spec.initContainers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed, spec.initContainers[0].securityContext.capabilities.add: Invalid value: "NET_ADMIN": capability may not be added, spec.containers[1].securityContext.runAsUser: Invalid value: 5995: must be in the ranges: [1001030000, 1001039999], provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "noobaa": Forbidden: not usable by user or serviceaccount, provider "noobaa-endpoint": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "consul-consul-client": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "rook-ceph": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "rook-ceph-csi": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]

### Expected behavior

Start a pod with the injector running

### Environment details
❯ oc version
Client Version: 4.12.0-202208031327
Kustomize Version: v4.5.4
Server Version: 4.10.43
Kubernetes Version: v1.23.12+8a6bfe4

**Comment by putz612** [comment]
Here is my test yaml deployment, only difference is I am using annotations vs default.  Also the example for openshift has `image: image:  hashicorp/http-echo:latest` vs `image:  hashicorp/http-echo:latest`
```
❯ cat server.yaml
apiVersion: v1
kind: Service
metadata:
  # This name will be the service name in Consul.
  name: static-server
spec:
  selector:
    app: static-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: static-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-server
  template:
    metadata:
      name: static-server
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        onsul.hashicorp.com/service-tags: static-server
      labels:
        app: static-server
    spec:
      containers:
        - name: static-server
          image: hashicorp/http-echo:latest
          args:
            - -text="hello world"
            - -listen=:8080
          ports:
            - containerPort: 8080
              name: http
      # If ACLs are enabled, the serviceAccountName must match the Consul service name.
      serviceAccountName: static-server
```
