### ISSUE TITLE
syncCatalog won't work if deployed to a cluster without Consul Server

### ISSUE THREAD

**Issue by jose-ledesma** [hashicorp/consul-k8s#1847]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

Enabling `syncCatalog` won't work if there are no Consul Servers deployed in the cluster. From the `values.yaml` [documentation from the Helm Chart](https://github.com/hashicorp/consul-k8s/blob/1821f08477724394b9819de04b5a43ade5b996b7/charts/consul/values.yaml#L1632): 
```
# This process assumes that a Consul agent is available on the host IP.
# This is done automatically if clients are enabled. If clients are not
# enabled then set the node selection so that it chooses a node with a
# Consul agent.
syncCatalog:
```

Nonetheless, the `sync-catalog-deployment`[ loads the env vars](https://github.com/hashicorp/consul-k8s/blob/1821f08477724394b9819de04b5a43ade5b996b7/charts/consul/templates/sync-catalog-deployment.yaml#L81) from 
`consul.consulK8sConsulServerEnvVars` which sets `CONSUL_ADDRESSES` [pointing to the Kubernetes Service](https://github.com/hashicorp/consul-k8s/blob/1821f08477724394b9819de04b5a43ade5b996b7/charts/consul/templates/_helpers.tpl#L289) created when you deploy Consul Servers

### Reproduction Steps
Deploy Consul Clients to a Kubernetes Cluster enabling `syncCatalog` without deploying Consul Servers in the very same cluster

### Logs
```
$ kubectl logs consul-agent-consul-sync-catalog-6f67c4cc8-ldgw5
2023-01-23T12:15:34.951Z [INFO]  consul-server-connection-manager: trying to connect to a Consul server
2023-01-23T12:15:34.953Z [ERROR] consul-server-connection-manager: connection error: error="failed to discover Consul server addresses: failed to resolve DNS name: consul-agent-consul-server.consul.svc: lookup consul-agent-consul-server.consul.svc on xxxxxx:53: no such host"
```
### Expected behavior

syncCatalog is able to work on Kubernetes Clusters without the Consul Server deployd

### Environment details

consul-k8s: 1.0.2
values.yaml:
```
global:
  domain: "xxdomainxx"
  enabled: false
  datacenter: "xxdatacenterxx"
  tls:
    enabled: true
    verify: false
    enableAutoEncrypt: true
    caCert:
      secretName: "consul-ca-cert"
      secretKey: "tls.crt"
  gossipEncryption:
    secretName: "consul-gossip-key"
    secretKey: 'key'

client:
  enabled: true
  exposeGossipPorts: true


  join:
    - 'provider=k8s kubeconfig=/consul/userconfig/kubeconfig-consul/kubeconfig label_selector="app=consul,component=server" namespace=consul'

connectInject:
  enabled: false

syncCatalog:
  enabled: true
  toConsul: false # We don't want K8S services created in Consul
  toK8S: true
  k8sPrefix: consul-
```
