### ISSUE TITLE
Incorrect/Incomplete Prometheus Annotations are Applied when `tls.httpsOnly=true`

### ISSUE THREAD

**Issue by itaytalmi** [hashicorp/consul-k8s#1856]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

When `tls.enabled` is set to `true` and `tls.httpsOnly` is set to `true`, port `8500` is unused, and Prometheus is unable to reach the Consul Servers via `/v1/agent/metrics` (connection is refused), and therefore, Consul Server data cannot be scraped at all.

Look here:
https://github.com/hashicorp/consul-k8s/blob/main/charts/consul/templates/server-statefulset.yaml#L119#L123
The `prometheus.io/port` annotation is hard-coded to `8500`. If `httpsOnly=true`, the port should be `8501`, and an additional annotation should be added: `"prometheus.io.scheme": "https"`. I have tested this locally and can confirm that it works.

### Reproduction Steps

I'm using this `values.yaml` file:

```
global:
  enabled: true
  name: consul
  datacenter: dc1
  gossipEncryption:
    autoGenerate: true
  tls:
    enabled: true
    enableAutoEncrypt: true
  metrics:
    enabled: true
    enableAgentMetrics: true
    enableGatewayMetrics: true

ui:
  enabled: true
  metrics:
    enabled: true
    provider: prometheus
    baseURL: http://kube-prometheus-stack-prometheus.observability:9090

connectInject:
  enabled: true
  metrics:
    defaultEnabled: true
    defaultPrometheusScrapePort: 20200
    defaultPrometheusScrapePath: /metrics
    defaultEnableMerging: false # Disable merging due to a bug preventing Prometheus from scraping metrics properly
    defaultMergedMetricsPort: 20100

server:
  enabled: true

controller:
  enabled: true
```

Then, the Prometheus targets appear as `Down` and the error is `Connection refused`.

### Expected behavior

See above.

### Environment details

Helm Chart version: `1.0.2`
Consul version: `1.14.2`
Kubernetes environment: `EKS 1.24`
Using the `kube-prometheus-chart` Helm Chart for Prometheus and Grafana. Chart version `44.3.0`. Prometheus version: `2.41.0`

### Additional Context

See above.
