### ISSUE TITLE
Persistent volume fails to provision when using using OpenEBS Local PV Hostpath

### ISSUE THREAD

**Issue by billgrant** [hashicorp/consul-k8s#1867]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

When using the `openebs-hostpath` storageclass in Kubernetes. Consul server pods get stuck in a pending state while attempting to create a consul cluster using the Consul Helm chart. The consul-connect-injector pod with get stuck in a restart loop. 

Here is are troubleshoot steps

```bash
kubectl get pods -n consul

NAME                                           READY   STATUS    RESTARTS      AGE
consul-connect-injector-749df9cb86-nk7lj       0/1     Running   2 (21s ago)   2m28s
consul-server-0                                0/1     Pending   0             2m28s
consul-server-1                                0/1     Pending   0             2m28s
consul-server-2                                0/1     Pending   0             2m27s
consul-server-acl-init-cleanup-jntc8           1/1     Running   0             2m28s
consul-server-acl-init-d62rc                   1/1     Running   0             2m28s
consul-webhook-cert-manager-7687cd6dd7-lflvh   1/1     Running   0             2m28s
```

```bash
kubectl logs consul-connect-injector-749df9cb86-nk7lj -n consul

2023-02-01T18:30:11.064Z [INFO]  consul-server-connection-manager: trying to connect to a Consul server
2023-02-01T18:30:11.079Z [ERROR] consul-server-connection-manager: connection error: error="failed to discover Consul server addresses: failed to resolve DNS name: consul-server.consul.svc: lookup consul-server.consul.svc on 10.96.0.10:53: no such host"
```

```bash
kubectl get pvc -n consul

NAME                          STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS       AGE
data-consul-consul-server-0   Pending                                      openebs-hostpath   4m18s
data-consul-consul-server-1   Pending                                      openebs-hostpath   4m18s
data-consul-consul-server-2   Pending                                      openebs-hostpath   4m17s
```

```bash
kubectl describe pvc data-consul-consul-server-0 -n consul
Name:          data-consul-consul-server-0
Namespace:     consul
StorageClass:  openebs-hostpath
Status:        Pending
Volume:
Labels:        app=consul
               chart=consul-helm
               component=server
               hasDNS=true
               release=consul
Annotations:   volume.beta.kubernetes.io/storage-provisioner: openebs.io/local
               volume.kubernetes.io/selected-node: k8s-node-3.example.net
               volume.kubernetes.io/storage-provisioner: openebs.io/local
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       consul-server-0
Events:
  Type     Reason                Age                  From                                                                                                Message
  ----     ------                ----                 ----                                                                                                -------
  Normal   WaitForFirstConsumer  5m12s                persistentvolume-controller                                                                         waiting for first consumer to be created before binding
  Normal   Provisioning          85s (x5 over 5m11s)  openebs.io/local_openebs-localpv-provisioner-6bc797844d-7z48n_4accd075-71bf-422a-a3ae-f3bd585914e8  External provisioner is provisioning volume for claim "consul/data-consul-consul-server-0"
  Warning  ProvisioningFailed    85s (x5 over 5m10s)  openebs.io/local_openebs-localpv-provisioner-6bc797844d-7z48n_4accd075-71bf-422a-a3ae-f3bd585914e8  failed to provision volume with StorageClass "openebs-hostpath": Internal error occurred: failed calling webhook "consul-connect-injector.consul.hashicorp.com": failed to call webhook: Post "https://consul-connect-injector.consul.svc:443/mutate?timeout=10s": dial tcp 10.102.145.29:443: connect: connection refused
  Normal   ExternalProvisioning  7s (x23 over 5m12s)  persistentvolume-controller                                                                         waiting for a volume to be created, either by external provisioner "openebs.io/local" or manually created by system administrator
```

`Values.yaml` used during helm install

```yaml
# Contains values that affect multiple components of the chart.
global:
 # The main enabled/disabled setting.
 # If true, servers, clients, Consul DNS and the Consul UI will be enabled.
 enabled: true
 # The prefix used for all resources created in the Helm chart.
 name: consul
 # The name of the datacenter that the agents should register as.
 datacenter: dc1
 # Enables TLS across the cluster to verify authenticity of the Consul servers and clients.
 tls:
   enabled: true
 # Enables ACLs across the cluster to secure access to data and APIs.
 acls:
   # If true, automatically manage ACL tokens and policies for all Consul components.
   manageSystemACLs: true
# Configures values that configure the Consul server cluster.
server:
 # Replicas is set to 3, but I only have 2 worker nodes.
 affinity: ""
 enabled: true
 # The number of server agents to run. This determines the fault tolerance of the cluster.
 replicas: 3
# Contains values that configure the Consul UI.
ui:
 enabled: true
 # Registers a Kubernetes Service for the Consul UI as a LoadBalancer.
 service:
   type: LoadBalancer
# Configures and installs the automatic Consul Connect sidecar injector.
connectInject:
  enabled: true
```

### Solution

OpenEBS spins up a pod in the `openebs` namespace to mount to the hostpath. The consul-connect-injector prevents this pod from spinning up. This means that the storage for the consul-server-pods will get to the bound state.

From the consul helm chart: https://github.com/hashicorp/consul-k8s/blob/main/charts/consul/values.yaml#L2138

```yaml
  # Selector for restricting the webhook to only specific namespaces.
  # Use with `connectInject.default: true` to automatically inject all pods in namespaces that match the selector. This should be set to a multiline string.
  # See https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-namespaceselector
  # for more details.
  #
  # By default, we exclude the kube-system namespace since usually users won't
  # want those pods injected and also the local-path-storage namespace so that
  # Kind (Kubernetes In Docker) can provision Pods used to create PVCs.
  # Note that this exclusion is only supported in Kubernetes v1.21.1+.
  #
  # Example:
  #
  # ```yaml
  # namespaceSelector: |
  #   matchLabels:
  #     namespace-label: label-value
  # ```
  # @type: string
```

The issue with Kind is very similar to the OpenEBS problem. 

The solution is to add the following to your values.yaml

```yaml
# Configures and installs the automatic Consul Connect sidecar injector.
connectInject:
  enabled: true
  namespaceSelector: |
    matchExpressions:
      - key: "kubernetes.io/metadata.name"
        operator: "NotIn"
        values: ["kube-system","local-path-storage", "openebs"]
```

This prevents consul from injecting the pods in the openebs namespace.

### Environment details

- `consul-k8s` version: v1.0.3
- Kubernetes version: v1.26
- Cloud Provider VMware vSphere
- Vanilla k8s cluster built with `kubeadm1
- Networking CNI plugin in use: Calico
- LoadBalancer - MetalLB
- CSI - OpenEBS
