### ISSUE TITLE
connect inject Kubernetes jobs without an associated service object

### ISSUE THREAD

**Issue by alop** [hashicorp/consul-k8s#1899]
In our old k8s cluster, we use consul extensively, services register with 'connect-service' annotation, and consumers use those services with the 'connect-service-upstreams' annotation.

We're in the process of upgrading, and the latest consul seems to require anything that has 'inject: true' to have a service, regardless if it's a server or a consumer. So I have a post-install job that fails to launch unless it has a matching kubernetes service.

I've been testing different annotations from the docs and nothing seems to get to the old behavior of "Yes, inject the sidecars, and connect to the upstream services".

My "consumer" pod spec looks like:
```
apiVersion: v1
kind: Pod
metadata:
  name: abelopez-test
  annotations:
    consul.hashicorp.com/connect-inject: "true"
    consul.hashicorp.com/connect-service-upstreams: "imap:4999"
```
which used to work in older versions

```
2023-02-10T16:12:05.910Z [INFO]  Unable to find registered services; retrying
2023-02-10T16:12:06.911Z [INFO]  Unable to find registered services; retrying
2023-02-10T16:12:07.913Z [INFO]  Unable to find registered services; retrying
2023-02-10T16:12:07.913Z [INFO]  Check to ensure a Kubernetes service has been created for this application. If your pod is not starting also check the connect-inject deployment logs.
2023-02-10T16:12:08.915Z [INFO]  Unable to find registered services; retrying
```

consul-inject container: consul_1.10.1_0.49.2_chart

**Comment by golgotow** [comment]
Is any workaround to live with this ? 

we tried to POC consul as replacement for other mesh, but with this limitation is useless for us

**Comment by alop** [comment]
@golgotow Ended up creating a "dummy" service for anything that needs to connect

**Comment by david-yu** [comment]
@alop Were you able to get your Job eventually deployed on the mesh? If so, could you share an example of a working yaml with Job? We're looking into this.

**Comment by david-yu** [comment]
Just to follow up this seems to be a working YAML for a job. We currently do require a service for everything to keep track of pods that are registered against Kubernetes catalog. As far as Jobs, I think an argument could be made whether a job should actually be part of a service since it won't really utilize a service for load balancing incoming traffic across pods. That is fair. 

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-job
  namespace: service-mesh
---
apiVersion: v1
kind: Service
metadata:
  name: test-job
  namespace: service-mesh
spec:
  selector:
    app: test-job
  ports:
    - port: 80
---
apiVersion: batch/v1
kind: Job
metadata:
   name: test-job
   namespace: service-mesh
   labels:
     app: test-job
spec:
  template:
    metadata:
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/transparent-proxy": "false"
      labels:
        app: test-job
    spec:
      containers:
      - name: test-job
        image: alpine:latest
        ports:
        - containerPort: 80
        command:
          - /bin/sh
          - -c
          - |
            echo "Started test job"
            sleep 10
            echo "Started test job"
      restartPolicy: Never
```
