### ISSUE TITLE
server-acl-init generates incomplete API Gateway Controller policy

### ISSUE THREAD

**Issue by krarey** [hashicorp/consul-k8s#1911]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

When `global.adminPartitions.enabled = true` is defined in Helm values, the policy generated for the API Gateway Controller is missing `operator = "write"` permissions, rendering the gateway controller unable to create new namespaces.

The following conditional misses this permission in the event admin partitions have been enabled: https://github.com/hashicorp/consul-k8s/blob/767f242a291a550cd4d00801f3fe1f0ac0a28fb7/control-plane/subcommand/server-acl-init/rules.go#L146-L153

### Reproduction Steps

* Deploy Consul Enterprise on Kubernetes with the following features enabled:
```yaml
global:
  image: "hashicorp/consul-enterprise:1.14.3-ent"
  enableConsulNamespaces: true
  adminPartitions:
    enabled: true
    name: "default"
  acls:
    manageSystemACLs: true
connectInject:
  enabled: true
  consulNamespaces:
    mirroringK8S: true
apiGateway:
  enabled: true
  image: hashicorp/consul-api-gateway:0.5.1
  imageEnvoy: envoyproxy/envoy:v1.23.1
```

* Create a new API gateway in a Kubernetes namespace that does not yet exist in Consul
```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: apigw
  namespace: apigateway
spec:
  gatewayClassName: consul-api-gateway
  listeners:
  - protocol: HTTP
    port: 8080
    name: http
    allowedRoutes:
      namespaces:
        from: All
```

* Observe the API Gateway Controller log output, it will enter a fail/retry loop encountering ACL denial errors attempting to create the new namespace.

### Logs

```
2023-02-14T21:33:43.453Z [WARN] gatewayclient/middleware.go:39: consul-api-gateway-server.k8s.Gateway: received non-Kubernetes error, delaying requeue:
error=
| 1 error occurred:
| \t* Unexpected response code: 403 (Permission denied)
|
```
