### ISSUE TITLE
Is it supported register HostIP for service with NodePort type?

### ISSUE THREAD

**Issue by pavel-z1** [hashicorp/consul-k8s#1930]
Hi

I have installed consul charm 1.0.4 with consul app 1.14.4
My consul-k8s config:
```
global:
  enabled: false
  name: k8s-beta
  logLevel: trace
  domain: consul
  datacenter: dc01
  gossipEncryption:
    autoGenerate: false
    secretName: k8s-beta-gossip-encryption-key
    secretKey: key
  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: bootstrap-token
      secretKey: token
  federation:
    enabled: false
  tls:
    enabled: false
externalServers:
  enabled: true
  hosts: ["consul-01.internal", "consul-02.internal", "consul-03.internal"]
  k8sAuthMethodHost: 'https://k8s-node-01.internal:6443'
  httpsPort: 80
  grpcPort: 8502
client:
  enabled: true
  join: ["consul-01.internal", "consul-02.internal", "consul-03.internal"]
  exposeGossipPorts: true
  extraConfig: |
    {
      "acl": {
        "default_policy": "deny",
        "enable_token_persistence": true,
        "enabled": true
      }
    }
server:
  enabled: false
connectInject:
  enabled: true
  logLevel: trace
  default: false
  transparentProxy:
    defaultEnabled: false
controller:
  enabled: true
meshGateway:
  enabled: false
```

With this service i have registered service in the Consul cluster with PodIP instead of NodeIP and PodPort instead of HostPort
```
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    run: my-nginx
```

I expect that service with NodePort type will be registered with correct endpoint (host IP and host port).
What configuration needs to be set to get correct host IP and host Port?
