### ISSUE TITLE
If container does not specify port, port 0 is registered

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul-k8s#195]
If a pod doesn't have a port set, e.g.

```yaml
spec:
  containers:
    # This name will be the service name in Consul.
    - name: static-server
      image: hashicorp/http-echo:latest
      args:
        - -text="hello world"
        - -listen=:8080
#      ports:
#        - containerPort: 8080
#           name: http
```

Then we register it as running on port `0`. This breaks connect because the envoy proxy can't route to port 0 but there are no error logs so it's hard to debug.

Instead we should either return an error during the mutating webhook call for that pod so it doesn't get scheduled and users can use `kubectl describe` to see a status event that states the error (pod has no containers with ports set).

**Comment by lkysow** [comment]
Note that not all services need to have ports. For example if it's only a client.

**Comment by tkwy-rick** [comment]
What i noticed in this example:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: static-server
---
apiVersion: v1
kind: Pod
metadata:
  name: static-server
  annotations:
    'consul.hashicorp.com/connect-inject': 'true'
spec:
  containers:
    # This name will be the service name in Consul.
    - name: static-server
      image: hashicorp/http-echo:latest
      args:
        - -text="hello world"
        - -listen=:8080
      ports:
        - containerPort: 8080
          name: http
    # If ACLs are enabled, the serviceAccountName must match the Consul service name.
  serviceAccountName: static-server
  ```
  
  When ports is enabled its trying to execute the following command in the `consul-connect-inject-init` init container:
  
  ```
  ......
  # Generate the envoy bootstrap code /bin/consul connect envoy \ -proxy-id="${PROXY_SERVICE_ID}" \ -prometheus-scrape-path="/metrics" \ -prometheus-backend-port="20100" \ -token-file="/consul/connect-inject/acl-token" \ -bootstrap > /consul/connect-inject/envoy-bootstrap.yaml # Copy the Consul binary cp /bin/consul /consul/connect-inject/consul
  ```
  
  Please take note of the `-prometheus-scrape-path` this is triggered by the ports definition. And in the logs of the init container it fails with: `flag provided but not defined: -prometheus-scrape-path`
  
  Any idea why it's adding it to that command?
