### ISSUE TITLE
Injecting proxy by default not working

### ISSUE THREAD

**Issue by krancour** [hashicorp/consul-k8s#20]
I've confirmed this behavior on both AKS and minikube.

If I install using the master branch of the Helm chart (which uses consul-k8s v0.2.0), having configured values to enable injection by default (i.e. without requiring annotations) like so:

```
# ConnectInject will enable the automatic Connect sidecar injector.
connectInject:
  enabled: true
  image: null # image for consul-k8s that contains the injector
  default: true # true will inject by default, otherwise requires annotation
```

Auto-injection fails and pods never even get created. Inspecting the deployment, I find this message as the last status condition:

```
message: 'Internal error occurred: Internal error occurred: jsonpatch add operation
        does not apply: doc is missing path: /metadata/annotations/consul.hashicorp.com~1connect-inject-status'
```

If I add the following annotation, everything works exactly as expected, but I was hoping to avoid this since I'd probably prefer that use of Consul Connect be enforced by policy rather than by developer choice.

```
annotations:
        "consul.hashicorp.com/connect-inject": "true"
```
