### ISSUE TITLE
Unable to get traffic splitter working across 2 versions

### ISSUE THREAD

**Issue by srikiz** [hashicorp/consul-k8s#2015]
#### Question
Installed consul-k8s 1.15.0. Please see helm configuration section for the values.yaml
Consul pods running okay and deployed helloworld and sleep pod and able to see the sidecar getting injected okay.

I don't see the traffic split happening when I configure a service-splitter with weights of 100 and 0.  Tried with both `consul.hashicorp.com/service-meta-version` and `consul.hashicorp.com/service-tags` but both doesn't seem to be working.

```
kubectl get pods -o wide
NAME                             READY   STATUS    RESTARTS   AGE   IP              NODE              NOMINATED NODE   READINESS GATES
helloworld-v1-699cd7fff5-jmstr   2/2     Running   0          45h   172.16.30.97    k8s-sbx-car2-w4   <none>           <none>
helloworld-v2-7dd5b7747-qwgmc    2/2     Running   0          45h   172.16.8.193    k8s-sbx-car2-w2   <none>           <none>
sleep-74b8f94b49-vhrvs           2/2     Running   0          45h   172.16.49.165   k8s-sbx-car2-w3   <none>           <none>
```

- helloworld and sleep pod yaml references below.

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helloworld
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
    service: helloworld
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: helloworld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-v1
  labels:
    app: helloworld
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      version: v1
  template:
    metadata:
      annotations:
        consul.hashicorp.com/service-meta-version: v1
        consul.hashicorp.com/service-tags: v1
        consul.hashicorp.com/connect-inject: 'true'
      labels:
        app: helloworld
        version: v1
    spec:
      serviceAccountName: helloworld
      containers:
      - name: helloworld
        image: docker.io/istio/examples-helloworld-v1
        resources:
          requests:
            cpu: "100m"
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        imagePullPolicy: IfNotPresent #Always
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        ports:
        - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-v2
  labels:
    app: helloworld
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      version: v2
  template:
    metadata:
      annotations:
        consul.hashicorp.com/service-meta-version: v2
        consul.hashicorp.com/service-tags: v2
      labels:
        app: helloworld
        version: v2
    spec:
      serviceAccountName: helloworld
      containers:
      - name: helloworld
        image: docker.io/istio/examples-helloworld-v2
        resources:
          requests:
            cpu: "100m"
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        imagePullPolicy: IfNotPresent #Always
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        ports:
        - containerPort: 5000
```

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sleep
---
apiVersion: v1
kind: Service
metadata:
  name: sleep
  labels:
    app: sleep
    service: sleep
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: sleep
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-service-upstreams: 'helloworld:5000'
      labels:
        app: sleep
    spec:
      terminationGracePeriodSeconds: 0
      serviceAccountName: sleep
      containers:
      - name: sleep
        image: curlimages/curl
        command: ["/bin/sleep", "infinity"]
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        volumeMounts:
        - mountPath: /etc/sleep/tls
          name: secret-volume
      volumes:
      - name: secret-volume
        secret:
          secretName: sleep-secret
          optional: true
```

- service defaults configuration

```
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: helloworld
spec:
  protocol: "http"
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: sleep
spec:
  protocol: "http"
---
```

- service router config

```
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceRouter
metadata:
  name: helloworld
spec:
  routes:
    - match:
        http:
          pathPrefix: "/"
      destination:
        service: "helloworld"

```

- service resolver config

```
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: helloworld
spec:
  defaultSubset: v1
  subsets:
    v1:
      filter: 'Service.Meta.version == v1'
    v2:
      filter: 'Service.Meta.version == v2'

```

- service splitter config
```
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceSplitter
metadata:
  name: helloworld
spec:
  splits:
    - weight: 100
      serviceSubset: v1
    - weight: 0
      serviceSubset: v2

```
### CLI Commands (consul-k8s, consul-k8s-control-plane, helm)

```
./consul-k8s proxy list -A
Namespace: all namespaces

Namespace       Name                            Type
default         helloworld-v1-699cd7fff5-jmstr  Sidecar
default         helloworld-v2-7dd5b7747-qwgmc   Sidecar
default         sleep-74b8f94b49-vhrvs          Sidecar
```

```
kubectl get servicedefaults
NAME         SYNCED   LAST SYNCED   AGE
helloworld   True     45h           45h
sleep        True     45h           45h
```

```
kubectl get serviceresolvers
NAME         SYNCED   LAST SYNCED   AGE
helloworld   True     45h           45h
```
```
kubectl get servicerouters
NAME         SYNCED   LAST SYNCED   AGE
helloworld   True     45h           45h
```
```
kubectl get servicesplitters
NAME         SYNCED   LAST SYNCED   AGE
helloworld   True     45h           45h
```
```
 ./consul-k8s proxy read sleep-74b8f94b49-vhrvs
Envoy configuration for sleep-74b8f94b49-vhrvs in namespace default:

==> Clusters (5)
Name                    FQDN                                                                            Endpoints               Type            Last Updated
consul-dataplane        consul-dataplane                                                                127.0.0.1:38588         STATIC          2023-03-13T10:28:56.447Z
local_app               local_app                                                                       127.0.0.1:0             STATIC          2023-03-13T10:28:56.772Z
original-destination    original-destination                                                                                    ORIGINAL_DST    2023-03-13T10:28:56.814Z
v1                      v1.helloworld.default.dc1.internal.ce089753-09df-4055-9456-24a27de5bc36.consul  172.16.30.97:20000      EDS             2023-03-13T10:28:56.859Z
v2                      v2.helloworld.default.dc1.internal.ce089753-09df-4055-9456-24a27de5bc36.consul  172.16.8.193:20000      EDS             2023-03-13T10:28:56.728Z


==> Endpoints (4)
Address:Port            Cluster                 Weight  Status
127.0.0.1:38588         consul-dataplane        1.00    HEALTHY
172.16.30.97:20000      v1                      1.00    HEALTHY
127.0.0.1:0             local_app               1.00    HEALTHY
172.16.8.193:20000      v2                      1.00    HEALTHY

==> Listeners (3)
Name            Address:Port            Direction       Filter Chain Match      Filters                 Last Updated
public_listener 172.16.49.165:20000     INBOUND         Any                     HTTP: * -> local_app/   2023-03-13T10:28:56.936Z
helloworld      127.0.0.1:5000          OUTBOUND        Any                     HTTP:                   2023-03-13T10:28:56.941Z

==> Routes (1)
Name            Destination Cluster     Last Updated
public_listener local_app/              2023-03-13T10:28:56.934Z

==> Secrets (0)
Name    Type    Last Updated
```

- Able to see the service config / resolver / router / splitter updated in consul

```
kubectl get pods -n consul
NAME                                          READY   STATUS    RESTARTS   AGE
consul-connect-injector-6c4c8b79dc-jjcgd      1/1     Running   0          46h
consul-server-0                               1/1     Running   0          46h
consul-webhook-cert-manager-b9cfd4c6c-dbm2k   1/1     Running   0          46h
prometheus-server-854f4ccdfd-bdq4l            2/2     Running   0          46h
```

- Exec into the consul server and able to read those updated configuration

```
kubectl exec -it consul-server-0 -n consul -- /bin/sh

/ $ consul config read -kind service-router -name helloworld
{
    "Kind": "service-router",
    "Name": "helloworld",
    "Routes": [
        {
            "Match": {
                "HTTP": {
                    "PathPrefix": "/"
                }
            },
            "Destination": {
                "Service": "helloworld"
            }
        }
    ],
    "Meta": {
        "consul.hashicorp.com/source-datacenter": "dc1",
        "external-source": "kubernetes"
    },
    "CreateIndex": 64856,
    "ModifyIndex": 64856
}

```

```
/ $ consul config read -kind proxy-defaults -name global
{
    "Kind": "proxy-defaults",
    "Name": "global",
    "TransparentProxy": {},
    "Config": {
        "protocol": "http"
    },
    "MeshGateway": {},
    "Expose": {},
    "AccessLogs": {},
    "Meta": {
        "consul.hashicorp.com/source-datacenter": "dc1",
        "external-source": "kubernetes"
    },
    "CreateIndex": 64652,
    "ModifyIndex": 64652
}

```
```
/ $ consul config read -kind service-splitter -name helloworld
{
    "Kind": "service-splitter",
    "Name": "helloworld",
    "Splits": [
        {
            "Weight": 100,
            "ServiceSubset": "v1"
        },
        {
            "Weight": 0,
            "ServiceSubset": "v2"
        }
    ],
    "Meta": {
        "consul.hashicorp.com/source-datacenter": "dc1",
        "external-source": "kubernetes"
    },
    "CreateIndex": 65083,
    "ModifyIndex": 65083
}

```

```
/ $ consul config read -kind service-resolver -name helloworld
{
    "Kind": "service-resolver",
    "Name": "helloworld",
    "DefaultSubset": "v1",
    "Subsets": {
        "v1": {
            "Filter": "Service.Meta.version == v1"
        },
        "v2": {
            "Filter": "Service.Meta.version == v2"
        }
    },
    "Meta": {
        "consul.hashicorp.com/source-datacenter": "dc1",
        "external-source": "kubernetes"
    },
    "CreateIndex": 64887,
    "ModifyIndex": 64887
}
```

```
/ $ consul config read -kind service-defaults -name helloworld
{
    "Kind": "service-defaults",
    "Name": "helloworld",
    "Protocol": "http",
    "TransparentProxy": {},
    "MeshGateway": {},
    "Expose": {},
    "Meta": {
        "consul.hashicorp.com/source-datacenter": "dc1",
        "external-source": "kubernetes"
    },
    "CreateIndex": 64738,
    "ModifyIndex": 64738
}
```

Seeing some error logs in consul though the objects are getting created above.

```
023-03-13T09:43:20.787Z [ERROR] agent.http: Request error: method=GET url=/v1/config/service-router/helloworld?dc=dc1 from=172.16.49.152:36048 error="Config entry not found for \"service-router\" / \"helloworld\""
2023-03-13T09:45:18.802Z [ERROR] agent.http: Request error: method=GET url=/v1/config/service-router/helloworld?dc=dc1 from=172.16.49.152:36048 error="Config entry not found for \"service-router\" / \"helloworld\""
2023-03-13T09:47:46.445Z [ERROR] agent.http: Request error: method=GET url=/v1/config/service-resolver/helloworld?dc=dc1 from=172.16.49.152:36048 error="Config entry not found for \"service-resolver\" / \"helloworld\""
2023-03-13T09:48:04.329Z [ERROR] agent.http: Request error: method=GET url=/v1/config/service-resolvers from=127.0.0.1:36014 error="invalid config entry kind: service-resolvers"
2023-03-13T10:08:54.904Z [ERRO
```

### Helm Configuration

```
 helm list -n consul
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
consul  consul          6               2023-03-14 13:15:09.728074727 +0000 UTC deployed        consul-1.1.0    1.15.0

```
```
global:
  name: consul
ui:
  enabled: true
  metrics_provider: prometheus
  metrics_proxy:
    base_url: "http://prometheus-server"
prometheus:
  enabled: true
connectInject:
  enabled: true
  default: true
  cni:
    enabled: true
    logLevel: info
    cniBinDir: "/opt/cni/bin"
    cniNetDir: "/etc/cni/net.d"
  namespaceSelector: |
    matchLabels:
      connect-inject: "enabled"

```

- Ran a config dump from the sleep pod and I am able see the dynamic config with weights showing up. Not sure why weight shows up as 10000 instead of 100?

```
kubectl exec -it sleep-74b8f94b49-vhrvs -- curl -X POST http://localhost:19000/config_dump

 "dynamic_route_configs": [
      {
        "version_info": "aacd3cecfe102e81f8b50cb0bf48cb6fb347b4a13939ad8de098f1cf03284ccc",
        "route_config": {
          "@type": "type.googleapis.com/envoy.config.route.v3.RouteConfiguration",
          "name": "helloworld",
          "virtual_hosts": [
            {
              "name": "helloworld",
              "domains": [
                "*"
              ],
              "routes": [
                {
                  "match": {
                    "prefix": "/"
                  },
                  "route": {
                    "weighted_clusters": {
                      "clusters": [
                        {
                          "name": "v1.helloworld.default.dc1.internal.ce089753-09df-4055-9456-24a27de5bc36.consul",
                          "weight": 10000
                        },
                        {
                          "name": "v2.helloworld.default.dc1.internal.ce089753-09df-4055-9456-24a27de5bc36.consul",
                          "weight": 0
                        }
                      ],
                      "total_weight": 10000
                    }
                  }
                },
                {
                  "match": {
                    "prefix": "/"
                  },
                  "route": {
                    "weighted_clusters": {
                      "clusters": [
                        {
                          "name": "v1.helloworld.default.dc1.internal.ce089753-09df-4055-9456-24a27de5bc36.consul",
                          "weight": 10000
                        },
                        {
                          "name": "v2.helloworld.default.dc1.internal.ce089753-09df-4055-9456-24a27de5bc36.consul",
                          "weight": 0
                        }
                      ],
                      "total_weight": 10000
                    }
                  }
                }
              ]
            }
          ],
          "validate_clusters": true
        },
        "last_updated": "2023-03-13T10:28:56.944Z"
      }
    ]
  },

```

### Current understanding and Expected behavior

The expectation was hitting helloworld service should route requests to only the helloworld-v1 pod based on the traffic split configuration above. But it does hit helloworld-v2 as seen below as well.

```
kubectl exec -it deploy/sleep -- curl -s http://helloworld:5000/test100 > /dev/null
Defaulted container "sleep" out of: sleep, consul-dataplane, consul-connect-inject-init (init)

 kubectl exec -it deploy/sleep -- curl -s http://helloworld:5000/test100 > /dev/null
Defaulted container "sleep" out of: sleep, consul-dataplane, consul-connect-inject-init (init)

 kubectl exec -it deploy/sleep -- curl -s http://helloworld:5000/test100 > /dev/null
Defaulted container "sleep" out of: sleep, consul-dataplane, consul-connect-inject-init (init)

kubectl logs deploy/helloworld-v2
Defaulted container "helloworld" out of: helloworld, consul-dataplane, consul-connect-inject-init (init)
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
172.16.49.165 - - [15/Mar/2023 07:47:01] "GET /test100 HTTP/1.1" 404 -
172.16.49.165 - - [15/Mar/2023 07:47:02] "GET /test100 HTTP/1.1" 404 -


kubectl logs deploy/helloworld-v1
Defaulted container "helloworld" out of: helloworld, consul-dataplane, consul-connect-inject-init (init)
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
172.16.49.165 - - [15/Mar/2023 07:47:03] "GET /test100 HTTP/1.1" 404 -
```

### Environment details

```
- consul-k8s: 1.15.0
- k8s version - 1.24.3 (on-premise)
- Network plugin  - calico
```
