### ISSUE TITLE
Server rolling update with acl-init dependency

### ISSUE THREAD

**Issue by joshRooz** [hashicorp/consul-k8s#2109]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

When attempting to enable snapshot agent on an existing cluster using `helm upgrade` with `server.updatePartition` set to a value greater than zero, snapshot agent fails to start successfully. It appears that this is due to a missing binding rule on the `consul-k8s-component-auth-method` for the snapshot-agent. 

Since `updatePartition` is set to a value greater than zero the acl-init job does not run to create the necessary binding rule. 

Attempting to override the auth method with an explicitly defined token was not successful.

### Reproduction Steps

1. Initial cluster creation 
    ```sh
    helm install consul --namespace consul hashicorp/consul --version 1.0.6 --values values.yaml
    ```
  
    <details><summary>Helm values</summary>
 
    ```
    global:
      name: consul
      peering:
        enabled: true
      adminPartitions:
        enabled: true
      image: hashicorp/consul-enterprise:1.14.6-ent
      gossipEncryption:
        autoGenerate: true
      tls:
        enabled: true
      enableConsulNamespaces: true
      acls:
        manageSystemACLs: true
      enterpriseLicense:
        secretName: consul-license
        secretKey: consul.hclic
    
    server:
      replicas: 3
      updatePartition: 0

    meshGateway:
      enabled: true
      replicas: 1
      service:
        type: ClusterIP
    ```
    </details>
1. Create snapshot agent config secret
    ```sh
    kubectl create secret generic --namespace consul \
      consul-snapshot-agent \
      --from-file=config=snapshot-agent-config.json
    ```
1. Enable snapshot agent via rolling update targeting one server pod
    ```sh
    helm upgrade consul --namespace consul hashicorp/consul --version 1.0.6 --values values.yaml \
      --set server.snapshotAgent.enabled=true \
      --set server.snapshotAgent.configSecret.secretName=consul-snapshot-agent \
      --set server.snapshotAgent.configSecret.secretKey=config \
      --set server.updatePartition=2
    ```

### Logs

```
# pod: consul-server-2

# container: consul 
2023-05-04T21:33:32.007Z [ERROR] agent.http: Request error: method=POST url=/v1/acl/login from=127.0.0.1:36070 error="rpc error making call: Permission denied"

# container: consul-snapshot-agent
2023-05-04T21:33:32.008Z [ERROR] snapshot: Error logging in to Consul; retrying: err="Unexpected response code: 403 (rpc error making call: Permission denied)"
```

### Expected behavior

Ability to deploy snapshot agent without taking the cluster offline.
