### ISSUE TITLE
PeeringAcceptor CRD with manually added server address

### ISSUE THREAD

**Issue by fredrikwarfvinge** [hashicorp/consul-k8s#2111]
#### Question

I have 2 kubernetes clusters separated over a network. Both are airgapped and any connections between them are set up to use the service mesh. If I add peering through the UI, I can add the server address of the main cluster in the "Server addresses" field. 

Here I can point it to a load balanced endpoint for the service mesh and everything works. However, if I try to do the same using kubernetes manifests I can't find a way to add the server-addresses when I create the PeeringAcceptor resource. 

My question is simply, is there a way for me to add the address manually to the secret generated by the creation of the PeeringAcceptor resource? 

This is my PeeringAcceptor resource and from checking the CRD definition I cannot add more:
```yaml
apiVersion: consul.hashicorp.com/v1alpha1
kind: PeeringAcceptor
metadata:
  name: cluster-02 ## The name of the peer you want to connect to
spec:
  peer:
    secret:
      name: "cluster-02-peering-token"
      key: "data"
      backend: "kubernetes"
```
The secret that is created contains fields for both ManualServerAddresses as well as ServerAddresses. The ManualServerAddresses has the value of null, and the ServerAddresses has gotten the internal kubernetes IP. I would like to be able on creation to set this value to my pre-determinable external FQDN. 

### Helm Configuration

You need two clusters, adjust the datacenter and ingress names accordingly

1. When running helm install with the following `values.yaml`:
```
global:
      name: consul
      datacenter: dc1
      gossipEncryption:
        autoGenerate: true
      tls:
        enabled: true
        enableAutoEncrypt: true
        verify: true
        httpsOnly: true
      acls:
        manageSystemACLs: true
        createReplicationToken: true
      peering:
        enabled: true
    connectInject:
      enabled: true
      replicas: 2
      image: null
      default: false
      transparentProxy:
        defaultEnabled: true
        defaultOverwriteProbes: true
    server:
      enabled: true
    ui:
      ingress:
        annotations: |
          'nginx.ingress.kubernetes.io/backend-protocol': "HTTPS"
        enabled: true
        ingressClassName: "nginx"
        hosts:
        - host: consul.example.com
        tls:
        - hosts:
          - consul.example.com
          secretName: tls-certificate
    syncCatalog:
      enabled: true
    meshGateway:
      enabled: true
      service:
        port: 443
        additionalSpec: |
          "loadBalancerIP": add the loadbalancer IP here
 ```

After deployment of the Helm Chart, setup Consul to use the service mesh for all peering:
```yaml
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: Mesh
metadata:
  name: mesh
spec:
  peering:
    peerThroughMeshGateways: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ProxyDefaults
metadata:
  name: global
spec:
  meshGateway:
    mode: local
```

Then set up peering using the PeeringAcceptor and PeeringDialer resources. 

### Current understanding and Expected behavior

Currently I haven't been able to find a way through the kubernetes manifests to add the external FQDN that resolves to the service mesh when setting up the PeeringAcceptor resource and secret. 

If it's possible already I'd like to be directed how to, and if it isn't I'd like for it to be a future feature. 

### Environment details

- `consul-k8s` version: 1.14.4

- Kubernetes version: v1.24.6
- Cloud Provider: RKE2
- Networking CNI plugin in use: Cilium 

Any other information you can provide about the environment/deployment.
The setup is fully air gapped. The clusters can route using internal public IP addresses that point to the service mesh on each cluster using a FQDN.

**Comment by fredrikwarfvinge** [comment]
I found a solution for this. 
In the consul helm chart, setup your meshGateway like this:
```yaml
meshGateway:
  wanAddress:
    source: "Static"
    static: "FQDN of gateway"
```
This causes the CRD to automatically pick up the FQDN you've setup for the mesh gateways and manifest based peering works out of the box.
