### ISSUE TITLE
consul: MountVolume.SetUp failed for volume "bootstrap-token" : secret "consul-bootstrap-acl-token" not found

### ISSUE THREAD

**Issue by sahotay** [hashicorp/consul-k8s#2182]
### Overview of the Issue

1. When running helm install with the following `values.yml`:
```
USER-SUPPLIED VALUES:
client:
  enabled: true
  extraConfig: |
    {"log_level": "DEBUG"}
  extraEnvironmentVars:
    AWS_STS_REGIONAL_ENDPOINT: regional
    HTTP_PROXY: <<PROXY_VALUES>>
    HTTPS_PROXY: <<PROXY_VALUES>>
    NO_PROXY: <<PROXY_VALUES>>
  extraLabels:
    networking/allow-vpc-access: "true"
  extraVolumes:
  - load: true
    name: consul-server-tls
    type: secret
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi
connectInject:
  enabled: false
global:
  acls:
    bootstrapToken:
      secretKey: token
      secretName: consul-bootstrap-acl-token
    manageSystemACLs: true
  consulSidecarContainer:
    resources:
      limits:
        cpu: 20m
        memory: 50Mi
      requests:
        cpu: 20m
        memory: 25Mi
  datacenter: dev-ae1
  domain: consul
  enablePodSecurityPolicies: false
  enabled: true
  extraLabels:
    networking/allow-vpc-access: "true"
  gossipEncryption:
    autoGenerate: false
    secretKey: ""
    secretName: ""
  image: hashicorp/consul:1.15.0
  imageK8S: hashicorp/consul-k8s-control-plane:1.1.0
  name: consul
server:
  extraConfig: |
    {"log_level": "DEBUG"}
  extraEnvironmentVars:
    AWS_STS_REGIONAL_ENDPOINT: regional
    HTTP_PROXY: <<PROXY_VALUES>>
    HTTPS_PROXY: <<PROXY_VALUES>>
    NO_PROXY: <<PROXY_VALUES>>
  extraLabels:
    networking/allow-vpc-access: "true"
  extraVolumes:
  - load: true
    name: consul-server-tls
    type: secret
  replicas: 3
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi
  serverCert:
    secretName: null
  storage: 20Gi
  storageClass: null
ui:
  service:
    annotations: |
      "external-dns.alpha.kubernetes.io/hostname": consul.mydomain.com
      "external-dns.alpha.kubernetes.io/access": "private"
      "service.beta.kubernetes.io/aws-load-balancer-type": "nlb"
      "service.beta.kubernetes.io/aws-load-balancer-internal": "true"
      "service.beta.kubernetes.io/aws-load-balancer-backend-protocol": "tcp"
      "service.beta.kubernetes.io/aws-load-balancer-ssl-ports": "443"
      "service.beta.kubernetes.io/aws-load-balancer-ssl-cert": <<ACM CERT ARN>>
      service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
      "service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol": "tcp"
    enabled: true
    port:
      http: 443
      https: 443
    type: LoadBalancer
```

1. View errors
consul-server-acl-init-q4tld:
```
Warning  FailedMount  26s (x7 over 57s)  kubelet            MountVolume.SetUp failed for volume "bootstrap-token" : secret "consul-bootstrap-acl-token" not found
```
consul-server-0
 Warning  Failed                  19s (x12 over 2m17s)  kubelet                  Error: secret "consul-bootstrap-acl-token" not found
![image](https://github.com/hashicorp/consul-k8s/assets/12233395/16351105-2b9e-44f8-b660-4abb80c6bfc9)

Note: I know there are a couple of issues similar to this but either none of the solutions worked for me or those issues are closed.
