### ISSUE TITLE
Is Dataplane compatible with Consul KV?

### ISSUE THREAD

**Issue by adawalli** [hashicorp/consul-k8s#2289]
#### Question
We have been using Consul for many years with our most important being the K/V store - long before the `manageSystemAcls` option was a thing. 

Fast-forward and I am moving my entire consul cluster onto kubernetes (instead of where we only had Consul clients in k8s before).

I have been dancing around the docs concerning inject, consul dataplane, and ACL creation and in full disclosure, I feel like I must be missing something obvious.

##### What I expect to be able to do
- Deploy Consul through Helm  with manageSystemACLs set to true (this works of course)
- Automatically get a sidecar with the dataplane attached to a core service (this works)
- Use the Token from the side car with consul or consul-template to fetch KV secrets (can't get this to work)

##### Why do I want to do it this way?
I want consul to automagically create/destroy tokens based on service accounts in k8s so that I don't end up with a ton of tokens. From what I can tell, inject + dataplane does this nicely. However, I can't tell the best way to talk back to a consul agent (from what I understand, we should be theoretically able to drop running the consul client as a daemonset on all k8s nodes) - but of course, I am left with only servers  (and no apparent access to the sidecar token), and the sidecar....which I'm not sure I can hit the consul API through

##### What else have I tried?
Running consul as an `initContainer` with something like the following

```yaml
    spec:
      serviceAccountName: my-service-account
      initContainers:
      - name: consul
        image: consul:latest
        command: ['consul']
        args:
          - login
          - -bearer-token-file=/var/run/secrets/kubernetes.io/serviceaccount/token
          - -method=consul-k8s-component-auth-method
          - -token-sink-file=/consul/token
        env:
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: CONSUL_HTTP_ADDR
            value: $(HOST_IP):8500
        volumeMounts:
        - mountPath: /consul
          name: consul
```
This works, but it's gross for two reasons. This sidecar seems to duplicate functionality that is all over the place through consul containers (e.g., injected pods). It also leaves behind a token that lasts forever **for every pod that I ever run**

Of course, I could do things the old school way and create a token by hand commit this to a k8s first class secret - but my soul dies just a little as I think of this method - since the k8s auth (e.g., binding, role, poliy) in consul works so nicely.

Can you please help me understand what I missing here? It can't be as hard as I am making it...right?
