### ISSUE TITLE
Port collision when trying to enable both in-cluster and external clients

### ISSUE THREAD

**Issue by ArtursL** [hashicorp/consul-k8s#2355]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

I have deployed consul servers and clients in Kubernetes with helm and would like to allow external clients to connect to the cluster.  So I have set `server.exposeGossipAndRPCPorts`  to `true`, which would expose port 8502 on the host: https://github.com/hashicorp/consul-k8s/blob/8f474854c4a58e5b11290fb79b8ae434a430962e/charts/consul/templates/server-statefulset.yaml#L463
However, this conflicts with the port already exposed by the client daemonset: https://github.com/hashicorp/consul-k8s/blob/8f474854c4a58e5b11290fb79b8ae434a430962e/charts/consul/templates/client-daemonset.yaml#L440

This causes the server pod to be unschedulable.
### Reproduction Steps

1. Deploy client and server with values like these
```yaml
server:
  connect: false
  exposeGossipAndRPCPorts: true # exposes the server gossip and RPC ports as hostPorts
  ports:
    serflan:
      # Note that this needs to be different than 8301, to avoid conflicting with the client gossip hostPort
      port: 9301

client:
  enabled: true
  grpc: false # Disabled since Consul Connect is not used
```

### Logs

Output from `kubectl events`:
```
Warning   FailedScheduling   Pod/consul-server-1                                  0/5 nodes are available: 2 node(s) didn't have free ports for the requested pod ports, 3 node(s) had taint {CriticalAddonsOnly: true}, that the pod didn't tolerate.
```

### Expected behavior

The chart should allow choosing a custom grpc port for the client and server, or to disable it altogether if grpc is not needed.

### Environment details

- `consul-k8s` version: v1.1.2

**Comment by guytet** [comment]
Are you able to connect an external client to the k8s consul cluster at all ? I'm following similar instructions, but my LAN clients cannot register with the consul nodes running within k8s. 
This, after enabling:
```yaml
server:
  connect: false
  exposeGossipAndRPCPorts: true # exposes the server gossip and RPC ports as hostPorts
  ports:
    serflan:
      # Note that this needs to be different than 8301, to avoid conflicting with the client gossip hostPort
      port: 9301
 ```
