### ISSUE TITLE
Multi-dc for consul clusters

### ISSUE THREAD

**Issue by metanovii** [hashicorp/consul-k8s#236]
Hi, what about consul multi-dc? Can i create cluster in k8s and spare his with other cluster, like "consul join -wan"?

**Comment by lkysow** [comment]
Hi Pablo, this depends on if your servers in cluster A can access the servers in cluster B. If so, then you can set retry_join_wan config in your helm chart:
```yaml
server:
  extraConfig: |
    { "retry_join_wan": ["ip1", "ip2", "ip3"] }
```
