### ISSUE TITLE
issue with consul-k8s get-consul-client-ca

### ISSUE THREAD

**Issue by ltagliamonte-dd** [hashicorp/consul-k8s#255]
i'm trying to use `consul-k8s get-consul-client-ca` to init sync-catalog.
i've started a test container that mounts the consul CA cert:
```
apiVersion: v1
kind: Pod
metadata:
  namespace: infra
  name: test-sync
spec:
  volumes:
  - name: tls-ca-cert
    secret:
      secretName: consul-agent-ca-cert
  hostNetwork: false
  containers:
  - name: consul-sync
    image: hashicorp/consul-k8s:0.13.0
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 24h; done"]
    volumeMounts:
      - name: tls-ca-cert
        mountPath: /consul/tls/ca
```

In an `exec` session I'm running:
```
consul-k8s get-consul-client-ca -output-file=/consul/tls/ca/client.crt -tls-server-name=server.us-west-2.staging.<MYDOMAIN> -server-addr=consul-discovery.<MYDOMAIN>.com -log-level=trace -server-port=8501 -
ca-file=/consul/tls/ca/ca-cert
```

the operation fails with:
```
2020-05-01T22:22:12.922Z [ERROR] Error retrieving CA roots from Consul: err="Get https://consul-discovery<MYDOMAIN>.com:8501/v1/agent/connect/ca/roots: remote error: tls: bad certificate"
```

the consul cluster cert has been created using:
```
consul tls ca create -days=3650
```

Please advise @ishustava @lkysow
