### ISSUE TITLE
Error "fetching supported dataplane features" in server ACL init job

### ISSUE THREAD

**Issue by erincandescent** [hashicorp/consul-k8s#2620]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue
I'm attempting to deploy consul-k8s with external servers. I have previously had consul-k8s deployed and working, but after deleting it, can't re-deploy it.

In particular, the issue I am encountering is that the server-acl-init-job: 
```
2023-07-21T15:02:20.146Z [INFO]  Found bootstrap token in secrets backend: secret=consul
2023-07-21T15:02:20.146Z [INFO]  consul-server-connection-manager: trying to connect to a Consul server
2023-07-21T15:02:20.146Z [INFO]  consul-server-connection-manager: discovered Consul servers: addresses=[100.64.0.1:8502]
2023-07-21T15:02:20.146Z [INFO]  consul-server-connection-manager: current prioritized list of known Consul servers: addresses=[100.64.0.1:8502]
2023-07-21T15:02:20.264Z [ERROR] consul-server-connection-manager: connection error: error="fetching supported dataplane features: rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR"
```

The consul-server-connection-manager errors then repeat forever.

If I disable TLS and do a packet capture, I see a GRPC request to the Consul server, but indeed no response - the server just resets the grpc stream.

Given the issue here looks to me to be on the Consul side, i'm not sure which repo to raise this in. Any debuging advice would be very welcome; setting `-log-level=trace` and `GRPC_GO_LOG_VERBOSITY_LEVEL = "99"; GRPC_GO_LOG_SEVERITY_LEVEL = "info";` on every component didn't really help.

### Reproduction Steps

values.yaml:
```yaml
global:
  # Disable defaults, so we can enable bits we want
  enabled: false

  # Set Helm prefix
  name: consul

  # Match what servers are using
  image: hashicorp/consul:1.15.3
  datacenter: eu

  gossipEncryption:
    autoGenerate: false
    secretName: "consul"
    secretKey: "gossip-key"

  tls:
    enabled: true # Optional
    httpsOnly: false
    enableAutoEncrypt: true
    caCert:
      secretName: "consul"
      secretKey: "ca"

  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: "consul"
      secretKey: "bootstrap-token"

  metrics:
    enabled: true

client:
  enabled: true # Optional
  join: ["100.64.0.1", "100.64.0.2", "100.64.0.4"]

dns:
  enabled: true # Optional
  clusterIP: "100.65.127.53"

syncCatalog:
  enabled: true # Optional
  default: false
  nodePortSyncType: "InternalOnly"

connectInject:
  enabled: false

externalServers:
  enabled: true
  hosts: ["100.64.0.1", "100.64.0.2", "100.64.0.4"]
  tlsServerName: "server.eu.consul"
  k8sAuthMethodHost: "https://100.65.127.1/"
  grpcPort: 8503
```
(Optional comments mark components which I have experimentally determined don't seem to have any imapct)

Server configuration files:
```json
﻿﻿{
  "acl": {
    "default_policy": "allow",
    "enable_token_persistence": true,
    "enabled": true
  },
  "addresses": {
    "dns": "{{ GetInterfaceIP \"wg0\" }} 127.0.0.1",
    "grpc": "{{ GetInterfaceIP \"wg0\" }} 127.0.0.1",
    "grpc_tls": "{{ GetInterfaceIP \"wg0\" }} 127.0.0.1",
    "http": "{{ GetInterfaceIP \"wg0\" }} 127.0.0.1",
    "https": "{{ GetInterfaceIP \"wg0\" }} 127.0.0.1"
  },
  "auto_encrypt": {
    "allow_tls": true,
    "tls": false
  },
  "client_addr": "127.0.0.1",
  "data_dir": "/var/lib/consul",
  "datacenter": "eu",
  "encrypt_verify_incoming": true,
  "encrypt_verify_outgoing": true,
  "log_level": "trace",
  "ports": {
    "grpc": 8502,
    "grpc_tls": 8503,
    "http": 8500,
    "https": 8501
  },
  "retry_join": [
    "100.64.0.1",
    "100.64.0.2",
    "100.64.0.4"
  ],
  "server": true,
  "services": [],
  "telemetry": {
    "prometheus_retention_time": "3600s"
  },
  "tls": {
    "defaults": {
      "ca_file": "/run/credentials/consul.service/consul-agent-ca.pem",
      "cert_file": "/run/credentials/consul.service/consul-server.pem",
      "key_file": "/run/credentials/consul.service/consul-server-key.pem.enc",
      "verify_incoming": false,
      "verify_outgoing": true
    },
    "internal_rpc": {
      "verify_incoming": false,
      "verify_server_hostname": false
    }
  },
  "ui_config": {
    "enabled": true
  }
}
```

### Logs
See above.

Nothing at all useful/relevant in the server logs, even on trace.

### Environment details

Kubernetes v1.25, k3s

```
$ consul version
Consul v1.15.3
Build Date 1970-01-01T00:00:01Z
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
```

consul-k8s helm chart v1.1.3
