### ISSUE TITLE
Helm Chart 1.2.0 Gateway API CRD API group mismatch

### ISSUE THREAD

**Issue by nbrns** [hashicorp/consul-k8s#2651]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

I did a fresh install of Consul via Helm on EKS using the 1.2.0 Helm Chart. I'm just introducing the Gateway API to our stack, so I enabled the `apiGateway` configurations.
However, when trying to upgrade/install, there is a CRD mismatch.

Referring to the [docs](https://developer.hashicorp.com/consul/docs/api-gateway/upgrades), the Gateway API is now native to Consul, thus I'd expect that there is no need to install CRDs first.

Further, the CRDs in the Helm Chart mismatch the CRDs provided in the consul-gateway-api repo:

Helm: https://github.com/hashicorp/consul-k8s/blob/v1.2.0/charts/consul/templates/crd-gatewayclassconfigs.yaml#L9e
CRDs in consul-gateway-api repo: https://github.com/hashicorp/consul-api-gateway/blob/main/config/crd/bases/api-gateway.consul.hashicorp.com_gatewayclassconfigs.yaml#L7

Which is the correct api group? `gatewayclassconfigs.consul.hashicorp.com` or `gatewayclassconfigs.api-gateway.consul.hashicorp.com`?

### Reproduction Steps

Steps to reproduce this issue, eg:

1. When running helm install with the following `values.yml`:
```
global:
  name: consul
  gossipEncryption:
    autoGenerate: true
  tls:
    enableAutoEncrypt: true
    enabled: true
server:
  replicas: 3
connectInject:
  enabled: true
  default: false
  transparentProxy:
    defaultEnabled: true
apiGateway:
  enabled: true
  image: "hashicorp/consul-api-gateway:0.5.4"
  managedGatewayClass:
    serviceType: LoadBalancer
    # broken atm, see https://github.com/hashicorp/consul-k8s/issues/2590
    # copyAnnotations:
    #   service:
    #     annotations: |
    #       - service.beta.kubernetes.io/aws-load-balancer-type
    #       - service.beta.kubernetes.io/aws-load-balancer-scheme
    #       - service.beta.kubernetes.io/aws-load-balancer-nlb-target-type
```
2. View error
```
helm upgrade --install consul hashicorp/consul  -f .\values.consul.yaml
Error: UPGRADE FAILED: resource mapping not found for name: "consul-api-gateway" namespace: "" from "": no matches for kind "GatewayClassConfig" in version "api-gateway.consul.hashicorp.com/v1alpha1"
ensure CRDs are installed first
```

### Logs

See `helm upgrade` logs above.

### Expected behavior

Setup of Consul with a preconfigured `GatewayClassConfig`.
Further: Clarification on correct API group.
