### ISSUE TITLE
Failed to connect inject with Envoy

### ISSUE THREAD

**Issue by jojohappy** [hashicorp/consul-k8s#27]
Hi,
  I try to install consul integrated with Kubernetes using consul-helm, and created a demo pod to test `Connect-inject`, but it was failed when it was `PodInitializing`.

The definition of pod is
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: static-server
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
spec:
  containers:
    - name: static-server
      image: hashicorp/http-echo:latest
      args:
        - -text="hello world"
        - -listen=:8080
      ports:
        - containerPort: 8080
          name: http
```

The error log is
```
Error registering service "static-server-proxy": Put http://<host_ip>:8500/v1/agent/service/register: dial tcp <host_ip>:8500: connect: connection refused
```
I saw that the `ip` requested was the kubernetes node ip address, but I did not setup the consul client daemonset to use `hostNetwork: true`, so I have a question why inject container setup the `CONSUL_HTTP_ADDR` as `HOST_IP`? After that I updated the daemonset to use `hostNetwork`, it worked well. 

I found the code, maybe we could optimize that. Or could you tell me whats wrong I did? Thank you.
https://github.com/hashicorp/consul-k8s/blob/0c6dede68a44d5d4ca48c5522b2e05f5ea1322a2/connect-inject/container_init.go#L70-L99
