### ISSUE TITLE
No matches for kind "GatewayClassConfig" in version "api-gateway.consul.hashicorp.com/v1alpha1"

### ISSUE THREAD

**Issue by matsyy** [hashicorp/consul-k8s#2715]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

When installing Helm Chart hashicorp/consul version 1.2.0 with an object of kind "GatewayClassConfig", the Kubernetes API does not know the "api-gateway.consul.hashicorp.com/v1alpha1" Custom Resource Definition.

### Reproduction Steps

1. When running `helm install --values helm/values.yaml consul hashicorp/consul --namespace consul --version "1.2.0"` with the following `values.yml`:

```
global:
  enabled: true
  name: consul
  image: hashicorp/consul:1.16.0
  datacenter: dc1
  tls:
    enabled: true
  acls:
    manageSystemACLs: true
  metrics:
    enabled: true
    enableAgentMetrics: true
    agentMetricsRetentionTime: "1m"
server:
  enabled: true
  replicas: 1
ui:
  enabled: true
  service:
    type: NodePort
  metrics:
    enabled: true
    provider: "prometheus"
    baseURL: http://prometheus-server.default.svc.cluster.local
connectInject:
  enabled: true
  metrics:
    defaultEnabled: true
apiGateway:
  enabled: true
  image: "hashicorp/consul-api-gateway:0.5.1"
  managedGatewayClass:
    serviceType: NodePort
    useHostPorts: true
```

1. View error:

```
Error: UPGRADE FAILED: resource mapping not found for name: "consul-api-gateway" namespace: "" from "": no matches for kind "GatewayClassConfig" in version "api-gateway.consul.hashicorp.com/v1alpha1"
ensure CRDs are installed first
```

### Expected behavior

Helm chart installs / upgrades successfully.

### Environment details

- Minikube version: v1.31.1
- Kubernetes version: v1.27.3

### Additional Context

I had a look at the templates and noticed that `https://github.com/hashicorp/consul-k8s/blob/v1.2.0/charts/consul/templates/api-gateway-gatewayclassconfig.yaml#L2` uses "api-gateway.consul.hashicorp.com/v1alpha1" kind.
But `https://github.com/hashicorp/consul-k8s/blob/v1.2.0/charts/consul/templates/crd-gatewayclassconfigs.yaml#L17` defines "consul.hashicorp.com" as the group.

Maybe I did not look at the right place because I am still new to all that stuff... Actually I was following a [Consul tutorial](https://developer.hashicorp.com/consul/tutorials/get-started-kubernetes/kubernetes-gs-ingress#enable-consul-ingress-features).

Thanks for the help

**Comment by david-yu** [comment]
As described in the tutorial for consul-k8s:1.2.0 and above you would need to only enable API Gateway via the connect inject stanza as opposed to the legacy standalone `apiGateway` stanza. I'll go ahead and close as I believe this has been raised a few times before. You can also see https://developer.hashicorp.com/consul/docs/api-gateway/upgrades#upgrade-to-native-consul-api-gateway for some more info on upgrading from consul-k8s:1.1.x as well. 

```
connectInject:
  enabled: true
  # Configures and installs the Consul API Gateway.
  apiGateway:
  # Configuration settings for the GatewayClass
  managedGatewayClass:
    # Defines the type of service created for gateways (e.g. LoadBalancer, ClusterIP, NodePort)
    # LoadBalancer is primarily used for cloud deployments.
    serviceType: LoadBalancer
```
