### ISSUE TITLE
How to configure sampling rate?

### ISSUE THREAD

**Issue by r4j4h** [hashicorp/consul-k8s#2760]
#### Question

I was able to engage distributed tracing to Jaeger via the zipkin collector and am happy in testing that it defaults to 100% with the demonstrated setting of `{}` in the [consul docs][] but for production I would like to tune this value, but I am not sure how as every way I have tried gives a type casting error.

In the [Consul docs][] as well as a [test case here][], everything shows usage of:
```
            "tracing": {
              "random_sampling": {}
            }
```

And the [envoy route components docs][] seem to agree that this should be configurable as a part of the Http connection manager and further configuration described in the [envoy tracing docs][], but in consul-k8s I seem to get casting errors.

[consul docs]: https://developer.hashicorp.com/consul/docs/connect/proxies/envoy
[envoy route components docs]: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-route
[envoy tracing docs]: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-tracing

[test case here]: https://github.com/hashicorp/consul-k8s/blob/main/cli/common/envoy/testdata/test_config_dump.json#L1651

Here are some of the ways I have tried to set it to sample at 1% instead of 100% along with the errors I have observed, starting with my first attempt at configuring the tracing object as an object and moving to a sub-object to find a further clue:

#### as int

Config: `"tracing":{"random_sampling":1},`
Error:
> [2023-08-11 01:50:52.983][1][warning][config] [./source/common/config/grpc_stream.h:196] DeltaAggregatedResources gRPC config stream closed since 78s ago: 14, failed to generate all xDS resources from the snapshot: failed to generate xDS resources for "type.googleapis.com/envoy.config.listener.v3.Listener": can't unmarshal Any nested proto type.googleapis.com/envoy.config.listener.v3.Listener: can't unmarshal Any nested proto type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager: json: cannot unmarshal number into Go value of type map[string]json.RawMessage

#### as string percentage

Config: `"tracing":{"random_sampling":"1%"},`
Error:
> [2023-08-11 01:50:52.983][1][warning][config] [./source/common/config/grpc_stream.h:196] DeltaAggregatedResources gRPC config stream closed since 78s ago: 14, failed to generate all xDS resources from the snapshot: failed to generate xDS resources for "type.googleapis.com/envoy.config.listener.v3.Listener": can't unmarshal Any nested proto type.googleapis.com/envoy.config.listener.v3.Listener: can't unmarshal Any nested proto type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager: json: cannot unmarshal string into Go value of type map[string]json.RawMessage

#### as float

Config: `"tracing":{"random_sampling":0.1},`
Error:
> 2023-08-11T01:59:58.219274920Z [2023-08-11 01:59:58.219][1][warning][config] [./source/common/config/grpc_stream.h:196] DeltaAggregatedResources gRPC config stream closed since 44s ago: 14, failed to generate all xDS resources from the snapshot: failed to generate xDS resources for "type.googleapis.com/envoy.config.listener.v3.Listener": can't unmarshal Any nested proto type.googleapis.com/envoy.config.listener.v3.Listener: can't unmarshal Any nested proto type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager: json: cannot unmarshal number into Go value of type map[string]json.RawMessage

### error with sub obj

Because these seemed to want to go to a `map[string]json.RawMessage` I tried nesting the object, which gave a promising lead with desiring `envoy.type.v3.Percent` but I cannot find the correct configuration for it to be able to cast it.

I will only show one of the tries, as they all gave the same error:

#### as percent string

Config: `"tracing":{"random_sampling":{"random_sampling":"1%"}},`
Error:
>  023-08-11T01:54:29.011429986Z 'grpc-message', 'failed to generate all xDS resources from the snapshot: failed to generate xDS resources for "type.googleapis.com/envoy.config.listener.v3.Listener": can't unmarshal Any nested proto type.googleapis.com/envoy.config.listener.v3.Listener: can't unmarshal Any nested proto type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager: unknown field "random_sampling" in envoy.type.v3.Percent'

**My question is** that I would like to know how to properly configure the Tracing sample rate, in particular the random_sampling option, although the other options might be handy as well. In particular, how do I properly define a envoy.type.v3.Percent through the YAML configurations?

### CLI Commands (consul-k8s, consul-k8s-control-plane, helm)

We are deploying the helm release through Flux v2, so generally no CLI commands are used.

### Helm Configuration

```
apiVersion: consul.hashicorp.com/v1alpha1
kind: ProxyDefaults
metadata:
  name: global
  namespace: consul
  annotations:
    'consul.hashicorp.com/migrate-entry': 'true'
spec:
  config:
    # Note that anything under config for ProxyDefaults will use the exact
    # same keys, e.g. JSON, not YAML syntax!
    #
    # JSON blocks MUST BE JSON ESCAPED!
    #
    # We do not have to have them quoted, but we cannot break them over multiple lines
    # because lines with indentation are not folded and this breaks Envoy's parser.
    #
    # To regenerate JSON blocks using jq:
    #         cat <<EOF | jq '. | @json'
    #         {
    #           "example": {
    #             "normal": "json"
    #           }
    #         }
    #         EOF
    #         "{\"example\":{\"normal\":\"json\"}}"
    #

    ## Enable tracing
    protocol: "http"
    # This envoy_tracing_json enables Distributed Tracing to Jaeger via Zipkin collector by defining a Tracer
    envoy_tracing_json: >-
      {"http":{"name":"envoy.tracers.zipkin","typedConfig":{"@type":"type.googleapis.com/envoy.config.trace.v3.ZipkinConfig","collector_cluster":"jaeger_9411","collector_endpoint_version":"HTTP_JSON","collector_endpoint":"/api/v2/spans","shared_span_context":true}}}
    # This envoy_listener_tracing_json enables Distributed Tracing to Jaeger via Zipkin collector by installing a Tracing Http filter
    envoy_listener_tracing_json: >-
      {"@type":"type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager.Tracing","provider":{"name":"envoy.tracers.zipkin","typed_config":{"@type":"type.googleapis.com/envoy.config.trace.v3.ZipkinConfig","collector_cluster":"jaeger_9411","collector_endpoint":"/api/v2/spans","collector_endpoint_version":"HTTP_JSON","shared_span_context":true}}}
    envoy_extra_static_clusters_json: >-
      {"connect_timeout":"3.000s","dns_lookup_family":"V4_ONLY","lb_policy":"ROUND_ROBIN","load_assignment":{"cluster_name":"jaeger_9411","endpoints":[{"lb_endpoints":[{"endpoint":{"address":{"socket_address":{"address":"jaeger-collector.observability","port_value":"9411","protocol":"TCP"}}}}]}]},"name":"jaeger_9411","type":"STRICT_DNS"}

    # *** This seems to be the non-intrusive way to add it, but I could be wrong ***
    envoy_public_listener_json: >-
      {"@type":"type.googleapis.com/envoy.config.listener.v3.Listener","name":"public_listener:0.0.0.0:20000","address":{"socket_address":{"address":"0.0.0.0","port_value":20000}},"filter_chains":[{"filters":[{"name":"envoy.filters.network.http_connection_manager","typed_config":{"@type":"type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager","stat_prefix":"public_listener","route_config":{"name":"public_listener","virtual_hosts":[{"name":"public_listener","domains":["*"],"routes":[{"match":{"prefix":"/"},"route":{"cluster":"local_app","timeout":"15m"}}]}]},"http_filters":[{"name":"envoy.filters.http.router","typed_config":{"@type":"type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"}}],"tracing":{"random_sampling":1},"forward_client_cert_details":"APPEND_FORWARD","set_current_client_cert_details":{"subject":true,"cert":true,"dns":true,"uri":true,"chain":true}}}],"transport_socket":{"name":"tls","typed_config":{"@type":"type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext","common_tls_context":{},"require_client_certificate":true}}}],"traffic_direction":"INBOUND"}
```

Steps to reproduce this issue,

1. Configure a Tracer (shouldn't matter what kind since its a "global"-ish envoy route config) with a `envoy_public_listener_json` that corresponds to how your consul envoy cluster configs look without it, ensuring  the `"tracing"` field is added.
2. Deploy a workload that uses the consul connect mesh
3. Enable envoy debug logs (consul debug level doesn't work for this)
  1. Open a port-forward to 19000 on the pod
  2. Exec `curl "localhost:19000/logging" -XPOST -G -dlevel=debug`
4. Try to send traffic to the pod
5. Observe envoy-sidecar logs to see if errors are printed about unknown fields

### Logs

I am more than happy to provide more logs, although I believe I have already narrowed down the relevant log lines above and don't want to make this issue too verbose unnecessarily.

### Current understanding and Expected behavior

I expected that upon configuration of sampling rate from 100% to 1% that I would see fewer traces than 1 for each request. Ideally something would be printed in recognition of the sample rate. Additionally an envoy config_dump should show the sample rate in the configuration.

(Instead I found the services errantly started as if they were okay, but would not properly route traffic and would emit the error logs above when it tried.)

### Environment details

- `consul-k8s` version: 0.49.8
- `values.yaml` used to deploy the helm chart:
  <details>
  <summary>`values.yaml` used to deploy the helm chart:</summary>
  
    ```
  client:
    extraConfig: |
      { "telemetry": { "prometheus_retention_time": "72h" } }
    grpc: true
    resources:
      limits:
        cpu: 100m
        memory: 350Mi
      requests:
        cpu: 100m
        memory: 100Mi
    connectInject:
      centralConfig:
        enabled: true
        proxyDefaults: |
          {}
      default: false
      enabled: true
      failurePolicy: Fail
      prepareDataplanesUpgrade: true
      resources:
        limits:
          cpu: 150m
          memory: 170Mi
        requests:
          cpu: 50m
          memory: 50Mi
      sidecarProxy:
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
      transparentProxy:
        defaultEnabled: false
        defaultOverwriteProbes: true
    controller:
      enabled: true
    global:
      acls:
        manageSystemACLs: true
      consulSidecarContainer:
        resources:
          limits:
            cpu: 50m
      datacenter: emr-dev-tiger
      enablePodSecurityPolicies: true
      gossipEncryption:
        autoGenerate: true
        secretKey: ''
        secretName: ''
      logLevel: debug
      metrics:
        enableAgentMetrics: true
        enabled: true
      tls:
        enableAutoEncrypt: true
        enabled: true
        serverAdditionalDNSSANs:
          - consul.secure.tiger.REDACTED.com
          - consul.tiger.REDACTED.com
        verify: true
    ingressGateways:
      enabled: false
      gateways: []
    server:
      enabled: true
      extraConfig: |
        { "telemetry": { "prometheus_retention_time": "72h" } }
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 200m
          memory: 200Mi
    syncCatalog:
      enabled: true
      namespaceSelector: |
        matchExpressions:
          - key: "kubernetes.io/metadata.name"
            operator: "NotIn"
            values: ["consul","kube-system","monitoring","ingress","external-secrets","sealed-secrets"]
      resources:
        limits:
          cpu: 50m
          memory: 100Mi
        requests:
          cpu: 50m
          memory: 50Mi
    terminatingGateways:
      enabled: false
      gateways: []
    ui:
      enabled: true
      ingress:
        annotations: |
          kubernetes.io/ingress.class: secure-nginx
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          cert-manager.io/cluster-issuer: letsencrypt-prod
        enabled: true
        hosts:
          - host: consul.secure.tiger.REDACTED.com
        tls:
          - hosts:
              - consul.secure.tiger.REDACTED.com
            secretName: consul-ui-ingress-tls
      metrics:
        baseURL: http://prometheus-operator-kube-p-prometheus.monitoring
          enabled: true
          provider: prometheus
        service:
          enabled: true
    ```

</details>

Additionally, please provide details regarding the Kubernetes Infrastructure, as shown below:
- Kubernetes version: v1.24
- Cloud Provider (If self-hosted, the Kubernetes provider utilized): EKS
- Networking CNI plugin in use: amazon-k8s-cni:v1.11.4-eksbuild.1
