### ISSUE TITLE
Consul control plane cannot connect to my cluster with acl enabled

### ISSUE THREAD

**Issue by mazha20** [hashicorp/consul-k8s#2870]
### Versions
helm - v3.11.2
kubectl - v1.26.6+k3s1
control-plane- 1.2.1

### Helm Configuration

```
global:
  enabled: false
  gossipEncryption:
     secretName: consul-gossip-encryption-key
     secretKey: key
  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: bootstrap-token
      secretKey: token
  
  datacenter: dc1
externalServers:
  enabled: true
  hosts: ["consul-address"]
  k8sAuthMethodHost: 'https://kubernetes-address:6443'
```

### Logs

<details>
<summary>consul-consul-k8s-component-auth-method not found</summary>
consul-server-connection-manager: trying to connect to a Consul server
2023-08-30T19:43:57.335Z [INFO]  consul-server-connection-manager: discovered Consul servers: addresses=[consul-address:8502]
2023-08-30T19:43:57.335Z [INFO]  consul-server-connection-manager: current prioritized list of known Consul servers: addresses=[consul-address:8502]
2023-08-30T19:43:57.341Z [ERROR] consul-server-connection-manager: ACL auth method login failed: error="rpc error: code = InvalidArgument desc = auth method \"consul-consul-k8s-component-auth-method\" not found"
2023-08-30T14:43:57.341212378-05:00 2023-08-30T19:43:57.341Z [ERROR] consul-server-connection-manager: connection error: error="rpc error: code = InvalidArgument desc = auth method \"consul-consul-k8s-component-auth-method\" not found"
unable to start Consul server watcher: context canceled

</details>

### Policy for bootstrap token is configured correctly and has permissions 
```
agent "" {
  policy = "read"
}

agent_prefix "" {
  policy = "read"
}

acl = "write"
operator = "write"
```

### Question

I feel that control-plane can't connect to my cluster because it can't create the appropriate auth-role.
Is this somehow related to the lack of secrets in the consul-consul-auth-method and consul-consul-connect-injector service accounts? 
If I disable acl in the cluster - the consul control plane can connect to my cluster again
