### ISSUE TITLE
Enabling audit logging causes configuration parse failure

### ISSUE THREAD

**Issue by krarey** [hashicorp/consul-k8s#2898]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

Enabling the `server.auditLogs` setting causes a crash loop for Consul Server pods due to invalid type conversion. The `rotate_max_files` and `rotate_bytes` settings must be integer-typed in JSON config, however the helm chart converts all values to string on line 207 here: https://github.com/hashicorp/consul-k8s/blob/af16373ee2a2fc8b6d9f2e8585d46a703ce0180d/charts/consul/templates/server-config-configmap.yaml#L193-L215

This leads to the following parse error at agent start:

```
==> failed to parse /consul/config/..2023_09_05_14_47_57.100611978/audit-logging.json: 2 error(s) decoding:

* 'audit.sink[My Sink].rotate_bytes' expected type 'int', got unconvertible type 'string', value: '2.5165824e+07'
* 'audit.sink[My Sink].rotate_max_files' expected type 'int', got unconvertible type 'string', value: '15'
```

### Reproduction Steps

1. Install with some variant of the following helm config:

```
global:
  name: consul
  image: hashicorp/consul-enterprise:1.16-ent
  imageK8S: hashicorp/consul-k8s-control-plane:1.2.1
  gossipEncryption:
    autoGenerate: true
  tls:
    enabled: true
  enableConsulNamespaces: true
  acls:
    manageSystemACLs: true
  enterpriseLicense:
    secretName: consul-license
    secretKey: key
server:
  updatePartition: 0
  auditLogs:
    enabled: true
    sinks:
      - name: My Sink
        type: file
        format: json
        path: /tmp/audit.json
        delivery_guarantee: best-effort
        rotate_duration: 24h
        rotate_max_files: 15
        rotate_bytes: 25165824
```
2. Observe logs upon deployment, as consul-server pods fail to start
