### ISSUE TITLE
Sync-Catalog: Configure health-check 

### ISSUE THREAD

**Issue by sagarj8n** [hashicorp/consul-k8s#29]
How do you configure the health check for the service that is automatically registered using the Consul sync Catalog.?

**Comment by madsonic** [comment]
strangely even the demo shows a dash for consul-ui
https://www.hashicorp.com/blog/consul-and-kubernetes-service-catalog-sync
I have some services that automatically shows passing health check while some showing merely a dash (as per the demo). Is there anything to do in particular to show health checks for synced services in kubernetes?

**Comment by arnodenuijl** [comment]
Just to chime in. I have a case where i need a health check here too. 

We are running a setup with consul and fabio (https://fabiolb.net/). Fabio is a reverse proxy that automatically (via consul tags) registers consul servers in the reverse proxy. 

I have consul-k8s setup via helm and when i deploy a service in kubernetes I see the service appearing in consul including the 'urlprefix-' tag (that fabio uses) that I added. The only problem is that fabio only registers services that have a health check. So since consul-k8s doesn't add an explicit health check the service doesn't appear in the reverse proxy.

```
---
apiVersion: v1
kind: Service
metadata:
  name: mynginx
  annotations:
    consul.hashicorp.com/service-tags: "urlprefix-/mynginx"
    consul.hashicorp.com/service-sync: "true"
    consul.hashicorp.com/service-name: "mynginx"
  labels:
    run: mynginx
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: mynginx
```
