### ISSUE TITLE
Can Consul Service Mesh support pod-to-pod connectivity?

### ISSUE THREAD

**Issue by r0ka** [hashicorp/consul-k8s#2997]
Hello everyone,

I have a specific use case that involves establishing pod-to-pod connectivity within our environment. 
Can you please advise  if Consul Service Mesh is capable of supporting such pod-to-pod connectivity scenarios.

Br,
Roma

**Comment by blake** [comment]
Hi @r0ka, Consul supports direct pod-to-pod communication when the `diailedDirectly` configuration option is enabled for the upstream service in its service defaults configuration. 

Below is an example config.

```yaml
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: upstream-service
spec:
  transparentProxy:
    dialedDirectly: true
```

See <https://developer.hashicorp.com/consul/docs/k8s/connect/transparent-proxy/enable-transparent-proxy#headless-services> and <https://developer.hashicorp.com/consul/docs/connect/config-entries/service-defaults#spec-transparentproxy> for more info.
