### ISSUE TITLE
Consul connector injector crashes randomly 

### ISSUE THREAD

**Issue by SAUDADE1999** [hashicorp/consul-k8s#3064]
Hello, im noticing that in some random amounts of time, my consul connector injector seems to crash.

Steps to reproduce this issue, eg:

1. When running helm install with the following `values.yml`:
```
global:
  name: consul
  datacenter: dc1
  dataDirectory: /consul/data
  logLevel: INFO
  enabled: true
server:
  replicas: 1
  bootstrapExpect: 1
  extraConfig: '{"addresses": {"http": "0.0.0.0"}}'
ui:
  enabled: true
  service:
    type: ClusterIP
  ingress:
    enabled: true
    hosts:
      - host: consul.localhost
        paths:
          - /
client:
  enabled: true
  grpc: true
dns:
  enabled: true
  port: 53
connectInject:
  enabled: true
acl:
  enabled: false
telemetry:
  prometheusRetentionTime: "1m"

```

1. View error

  --->

2023-10-09T16:19:08.198Z	ERROR	setup	unable to register field indexes	{"error": "no matches for kind \"GatewayClass\" in version \"gateway.networking.k8s.io/v1beta1\""}
github.com/hashicorp/consul-k8s/control-plane/subcommand/inject-connect.(*Command).Run
	/home/runner/work/consul-k8s/consul-k8s/control-plane/subcommand/inject-connect/command.go:490
github.com/mitchellh/cli.(*CLI).Run
	/home/runner/go/pkg/mod/github.com/mitchellh/cli@v1.1.0/cli.go:260
main.main
	/home/runner/work/consul-k8s/consul-k8s/control-plane/main.go:21
runtime.main
	/opt/hostedtoolcache/go/1.20.7/x64/src/runtime/proc.go:250
2023-10-09T16:19:08.198Z [INFO]  consul-server-connection-manager: stopping 

- `consul-k8s` version: v1.2.2
- k3s version v1.27.4+k3s1 (36645e73)
- go version go1.20.6

2. FIX

I fixed this error deleting the pod and letting the deployment do is magic work of restarting the pod.
It already happened a couple of times and I'm curious if there is any fix for this error.
Thank you for your time.
