### ISSUE TITLE
Helm install results in non-working consul

### ISSUE THREAD

**Issue by samip5** [hashicorp/consul-k8s#3095]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

When using Helm chart version 1.1.1, and consul-k8s 0.26.0, the end result is non-working Consul.

### Reproduction Steps

1. When running helm install with the following `values.yml`:
```
global:
  enabled: true
  logLevel: debug

  image: "registry.samipsolutions.fi/docker/hashicorp/consul:1.15.2"
  imageK8S: "registry.samipsolutions.fi/docker/hashicorp/consul-k8s:0.26.0"
  # Rate limiting be damned
  # imagePullSecrets:
  #  - name: regcred
  datacenter: dc1

  server:
    enabled: "true"
    replicas: 3
  service:
    enabled: true
    type: loadBalancer
  ports:
    serflan:
      port: 8301

  storage: 50Gi
  storageClass: longhorn
  ingress:
    enabled: true
    ingressClassName: internal-nginx
    pathType: Prefix
    hosts:
      - host: consul.nebula.skylab.fi
        paths:
          - /
    tls:
      - secretName: secret-consul-tls
      - hosts:
          - consul.nebula.skylab.fi
  hostNetwork: true
```
2. See that the `consul-consul-webhook-cert-manager` pod is stuck crashing due to not finding the `consul-k8s-control-plane` binary.

### Logs

```
$ k logs -n hashicorp consul-consul-webhook-cert-manager-8fd668fd8-f4x8x
/bin/sh: consul-k8s-control-plane: not found
```

### Expected behavior

It would provision Consul that's usable.

### Environment details

- `consul-k8s` version: 0.26.0

Additionally, please provide details regarding the Kubernetes Infrastructure, as shown below:
- Kubernetes version: v1.26.3+k3s1
- On-prem k3s
- Networking CNI plugin in use:  Cilium
- Some nodes are arm64, and some are amd64
