### ISSUE TITLE
Consul dataplane container args

### ISSUE THREAD

**Issue by andriktr** [hashicorp/consul-k8s#3201]
Hi, 
Since consul versio 1.14.x a there is no more agent in consul k8s. In our case we run consul servers outside the k8s cluster. I noticed that dataplane container (application sidecar) has the following args
```yaml
...
  - args:
    - -addresses
    - 10.162.34.52
    - -grpc-port=8503
    - -proxy-service-id-path=/consul/connect-inject/proxyid
    - -log-level=info
    - -log-json=false
    - -envoy-concurrency=2
    - -credential-type=login
    - -login-auth-method=consul-experimental-k8s-auth-method
    - -login-bearer-token-path=/var/run/secrets/kubernetes.io/serviceaccount/token
    - -ca-certs=/consul/connect-inject/consul-ca.pem
    - -graceful-port=20600
    - -shutdown-drain-listeners
    - -shutdown-grace-period-seconds=30
    - -graceful-shutdown-path=/graceful_shutdown
    - -telemetry-prom-scrape-path=/metrics
```
as u can see addresses arg has only one ip address. I assume that it simply takes first IP from helm values:

```yaml
...
externalServers:
  # If true, the Helm chart will be configured to talk to the external servers.
  # If setting this to true, you must also set `server.enabled` to false.
  enabled: true

  # An array of external Consul server hosts that are used to make
  # HTTPS connections from the components in this Helm chart.
  # Valid values include an IP, a DNS name, or an [exec=](https://github.com/hashicorp/go-netaddrs) string.
  # The port must be provided separately below.
  # Note: This slice can only contain a single element.
  # Note: If enabling clients, `client.join` must also be set to the hosts that should be
  # used to join the cluster. In most cases, the `client.join` values
  # should be the same, however, they may be different if you
  # wish to use separate hosts for the HTTPS connections.
  # @type: array<string>
  hosts: ["10.162.34.52","10.162.34.53","10.162.34.54"]

```
My question is what will happen if cluster nodes defined in dataplane arg will fail. How this will be handled and what impact it will have for the meshed application?

Thank you.
