### ISSUE TITLE
Consul Datadog Metrics Integration

### ISSUE THREAD

**Issue by natemollica-nm** [hashicorp/consul-k8s#3348]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

#### Is your feature request related to a problem? Please describe.

* In attempts to streamline implementation of metrics transmission to datadog via their Consul integration [documentation](https://docs.datadoghq.com/integrations/consul/?tab=containerized#containerized) proved to be somewhat of a difficult task without manual configuration requirements to both the helm chart and secrets.

For example:

```yaml
global:
    datadog:
      enabled: false
      dogstatsd:
        enabled: false
        socketTransportType: "UDS"
        dogstatsdAddr: "/var/run/datadog/dsd.socket"
        dogstatsdPort: 8125
        dogstatsdTags: ["source:consul","service:consul-server"]
      namespace: "datadog"
```

#### Feature Description

* Introduce `values.yaml` Consul helm overrides that automates some of the required integration management aspects with metrics transmission to datadog (either via dogstatsd or prometheus scraping).

#### Use Case(s)

* Service Mesh
* Service Discovery
* Consul Overall System Health Monitoring

#### Contributions

Yes, currently I'm working through this integration on a branch named `datadog-integration` following the [`CONTRIBUTION.md`](https://github.com/hashicorp/consul-k8s/blob/main/CONTRIBUTING.md#making-changes-to-consul-k8s) guide for repo forking.
