### ISSUE TITLE
API-Gateway configuration via connectInject.apiGateway stanza

### ISSUE THREAD

**Issue by andriktr** [hashicorp/consul-k8s#3417]
Hi, 
According helm chart values.yaml `apiGateway` configuration is deprecated and will be removed soon. So now we should use  connectInject.apiGateway stanza instead.  In this stanza I can't find configuration for api-gateway-controller pods and gateway instances. Can someone briefly explain the deferences between these two approaches?
Thank you.

```yaml
# [DEPRECATED] Use connectInject.apiGateway instead. This stanza will be removed with the release of Consul 1.17
# Configuration settings for the Consul API Gateway integration
apiGateway:
  # When true the helm chart will install the Consul API Gateway controller
  enabled: false

  # Image to use for the api-gateway-controller pods and gateway instances
  #
  # ~> **Note:** Using API Gateway <= 0.4 with external servers requires setting `client.enabled: true`.
  # @type: string
  image: null

  # The name (and tag) of the Envoy Docker image used for the
  # apiGateway. For other Consul compoenents, imageEnvoy has been replaced with Consul Dataplane.
  # @default: envoyproxy/envoy:<latest supported version>
```
