### ISSUE TITLE
Allow setting only the registry for docker images in the helm chart instead of full URI

### ISSUE THREAD

**Issue by komapa** [hashicorp/consul-k8s#3425]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

#### Is your feature request related to a problem? Please describe.

Yes. Let me explain :)

We are mirroring all of consul-k8s dependent images in our private registry in the following format:

```
      global:
        image: ${local.registry}/hub/hashicorp/consul-enterprise:${local.consul_version}
        imageK8S: ${local.registry}/hub/hashicorp/consul-k8s-control-plane:${local.consul_chart_version}
        imageConsulDataplane: ${local.registry}/hub/hashicorp/consul-dataplane:${local.consul_chart_version}
```

The immediate problem is that releases for 1.1.x do not track the same versioning in `consul-dataplane` project! `consul-k8s` is at 1.1.8 but `consul-dataplane` is at 1.1.7 and the above logic fails while it works perfectly for 1.2.x and 1.3.x series. 

#### Feature Description

It will be great if we can just specify:

```
global:
   registry: ${local.registry}/hub/hashicorp
```

and then you fill in with `consul-k8s-control-plane:1.1.8` and `consul-dataplane:1.1.7` the rest.

#### Use Case(s)

Using private registries
