### ISSUE TITLE
It appears that multiport cannot be used with the peering setting turned on.

### ISSUE THREAD

**Issue by homie-du** [hashicorp/consul-k8s#3551]
#### Question
Hello.
I'm trying to use the multi-port function, but it seems like I can't use the multi-port when the cluster-peering setting is activated.
Will this be resolved in the next version? In the environment I am operating in, I need to use both cluster-peering and multi-port.

### CLI Commands (consul-k8s, consul-k8s-control-plane, helm)
$ consul-k8s upgrade -f values.yaml

### Helm Configuration
```
global:
  experiments:
    - resource-apis
  peering:
    enabled: true
ui:
  enabled: false
manageSystemACLs: true
```

### Logs
```
When the value global.experiments.resourceAPIs is set, global.peering.enabled is currently unsupported.
```

### Environment details
consul:1.17.1
consul-k8s-control-plane:1.3.1

enabled (mesh-gw, peering)
