### ISSUE TITLE
CRDs: when I provide an `expose` section to proxy-defaults, it should use consul's default protocol rather than failing

### ISSUE THREAD

**Issue by ishustava** [hashicorp/consul-k8s#367]
## Description

I have the following proxy-defaults.yaml:

```yaml
apiVersion: consul.hashicorp.com/v1alpha1
kind: ProxyDefaults
metadata:
  name: global
spec:
  config:
    envoy_prometheus_bind_addr: 0.0.0.0:9200
  expose:
    checks: true
    paths:
      - path: /metrics
        localPathPort: 8080
        listenerPort: 9201
```

When I apply it to the cluster, I get the following error:

```
Error from server: error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"consul.hashicorp.com/v1alpha1\",\"kind\":\"ProxyDefaults\",\"metadata\":{\"annotations\":{},\"name\":\"global\",\"namespace\":\"default\"},\"spec\":{\"config\":{\"envoy_prometheus_bind_addr\":\"0.0.0.0:9200\"},\"expose\":{\"checks\":true,\"paths\":[{\"listenerPort\":9201,\"localPathPort\":8080,\"path\":\"/metrics\"}]}}}\n"}},"spec":{"expose":{"paths":[{"listenerPort":9201,"localPathPort":8080,"path":"/metrics"}]}}}
to:
Resource: "consul.hashicorp.com/v1alpha1, Resource=proxydefaults", GroupVersionKind: "consul.hashicorp.com/v1alpha1, Kind=ProxyDefaults"
Name: "global", Namespace: "default"
for: "proxy-defaults.yaml": admission webhook "mutate-proxydefaults.consul.hashicorp.com" denied the request: proxydefaults.consul.hashicorp.com "global" is invalid: spec.expose.paths[0].protocol: Invalid value: "": must be one of "http", "http2"
```

## Expected behavior

Since Consul has a default for the `expose.paths[].protocol` (`http`) I expected to see no error and for the controller to pass through to Consul and let it default to `http`.
