### ISSUE TITLE
Federation secret not generated

### ISSUE THREAD

**Issue by ChristopheBeke** [hashicorp/consul-k8s#3796]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

No federation secret is being installed on my AKS cluster.

### Reproduction Steps

 When running helm install with the following `values.yml`:
```
acls:
  createReplicationToken: true
  manageSystemACLs: true
client:
  enabled: true
connectInject:
  default: false
  enabled: true
  k8sAllowNamespaces:
  - services
  - consul
controller:
  enabled: true
federation:
  createFederationSecret: true
  enabled: true
global:
  datacenter: dc1
  name: consul
gossipEncryption:
  autoGenerate: true
meshGateway:
  enabled: true
server:
  enabled: true
tls:
  enabled: true

```

### Expected behavior

For the federation secret to be created in the namespace consul. 

### Environment details

Consul Version: 1.18.0
Chart Version: 1.4.0
AKS Version: 1.27.9

### Additional Context

Need the federation secret for federating multiple AKS clusters.
