### ISSUE TITLE
helm deploying consul reports an error

### ISSUE THREAD

**Issue by ForcemCS** [hashicorp/consul-k8s#4106]
I'm using helm to deploy consul and I'm getting the following message,I'm not sure if this is a problem with the web plugin (calico) or something else
```
  Warning  FailedCreatePodSandBox  9m8s (x546 over 18m)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "bbb2fb13957bed5e7ea18e921ed670d5a6ebd534242211f2bf3e90ff9d8576a8": plugin type="consul-cni" name="consul-cni" failed (add): error retrieving pod: Unauthorized
```

The yaml file is as follows：
```
# Contains values that affect multiple components of the chart.
global:
  # The main enabled/disabled setting.
  # If true, servers, clients, Consul DNS and the Consul UI will be enabled.
  enabled: true
  # The prefix used for all resources created in the Helm chart.
  name: consul
  # The consul image version.
  #image: hashicorp/consul:1.16.0
  # The name of the datacenter that the agents should register as.
  datacenter: dc1-local
  # Enables TLS across the cluster to verify authenticity of the Consul servers and clients.
  tls:
    enabled: true
  # Enables ACLs across the cluster to secure access to data and APIs.
  acls:
    # If true, automatically manage ACL tokens and policies for all Consul components.
    manageSystemACLs: true
  # Exposes Prometheus metrics for the Consul service mesh and sidecars.
  metrics:
    enabled: true
    # Enables Consul servers and clients metrics.
    enableAgentMetrics: true
    # Configures the retention time for metrics in Consul servers and clients.
    agentMetricsRetentionTime: "1m"
# Configures values that configure the Consul server cluster.
server:
  enabled: true
  # The number of server agents to run. This determines the fault tolerance of the cluster.
  replicas: 1
  #storageClass
  storageClass: 
# Contains values that configure the Consul UI.
ui:
  enabled: true
  # Defines the type of service created for the Consul UI (e.g. LoadBalancer, ClusterIP, NodePort).
  # NodePort is primarily used for local deployments.
  service:
    type: NodePort
  # Enables displaying metrics in the Consul UI.
  metrics:
    enabled: true
    # The metrics provider specification.
    provider: "prometheus"
    # The URL of the prometheus metrics server.
    baseURL: http://prometheus-k8s.monitoring.svc.cluster.local
# Configures and installs the automatic Consul Connect sidecar injector.
connectInject:
  enabled: true
  default: true
  namespaceSelector: |
    matchLabels:
      connect-inject : enabled
  cni:
    enabled: true
    logLevel: info
    cniBinDir: "/opt/cni/bin"
    cniNetDir: "/etc/cni/net.d"
```
