### ISSUE TITLE
two service sync to k8s, but only one show

### ISSUE THREAD

**Issue by tobewithyou1996** [hashicorp/consul-k8s#414]
#### Question
I have two different services. But I two service consul.hashicorp.com/service-name: is consistent, but I'm in the consul can only see one, my version is consul - k8s v0.10.1 consul version 1.3.1.

**Comment by ishustava** [comment]
Hey @tobewithyou1996 thanks for submitting an issue!

Could you share a bit more info about what is confusing? As far as I understand, you have two different services but the `consul.hashicorp.com/service-name` is the same for them? If the service name is the same, then the two services will show up as a single service in Consul.

If I misunderstood you, it would be helpful if you could share more details about how you are registering services, what you're seeing and what do you expect to see (yaml snippets would be much appreciated).

Thanks!

**Comment by tobewithyou1996** [comment]
Right, I have a and b two service, the consul.hashicorp.com/service-name inside is the same, normally, I can see a service in consul - name has two nodes. That's two K8S services, but I can only see one.

**Comment by tobewithyou1996** [comment]
a: ![image](https://user-images.githubusercontent.com/31532979/103067070-241b3900-45f5-11eb-9565-abd010a0b82b.png)
b: 
![image](https://user-images.githubusercontent.com/31532979/103067134-3eedad80-45f5-11eb-993c-70b59255a50f.png)
A and B have the same service-name but I was in an oncoming moment in time to see only one.
![image](https://user-images.githubusercontent.com/31532979/103067279-86743980-45f5-11eb-8f45-88ee5e0c4984.png)

**Comment by tobewithyou1996** [comment]
I found a strange phenomenon. First of all, in the face of the above abnormal phenomenon, my environment is: the pod corresponding to the service a selector is a, and the pod corresponding to the service B selector is B. A and B are not the same deployment, but two different deployment. But a and B are on the same node. Next, I bind the machine, that is, let a and B be located in different machines, so that I can see the two synchronized service information under my corresponding name on the consumer.
I think there is a problem in the logic between synchronizing information to consul `consul-k8s`.  that is, information from the same machine will be covered. I hope I can have a look at this aspect. If you need me to pass more details, I will reply.

**Comment by lkysow** [comment]
I don't think we support syncing two `Service` resources with the same `consul.hashicorp.com/service-name` annotation unfortunately.

I'm curious what your use-case is here?

**Comment by ishustava** [comment]
Hey @tobewithyou1996 

I've just tried it, and I think it works as expected. I see two instances for the service registered with Consul (one from each deployment). 

```
$ kubectl get pods -o wide
NAME                                         READY   STATUS    RESTARTS   AGE     IP           NODE                                      NOMINATED NODE   READINESS GATES
iryna-consul-6vzr9                           1/1     Running   0          6m59s   10.24.2.40   gke-shustava-default-pool-bad0f39a-f890   <none>           <none>
iryna-consul-ksdxn                           1/1     Running   0          6m59s   10.24.0.41   gke-shustava-default-pool-bad0f39a-wr0v   <none>           <none>
iryna-consul-ksj7w                           1/1     Running   0          6m59s   10.24.1.70   gke-shustava-default-pool-bad0f39a-08fj   <none>           <none>
iryna-consul-server-0                        1/1     Running   0          6m59s   10.24.1.72   gke-shustava-default-pool-bad0f39a-08fj   <none>           <none>
iryna-consul-server-1                        1/1     Running   0          6m59s   10.24.0.42   gke-shustava-default-pool-bad0f39a-wr0v   <none>           <none>
iryna-consul-server-2                        1/1     Running   0          6m59s   10.24.2.41   gke-shustava-default-pool-bad0f39a-f890   <none>           <none>
iryna-consul-sync-catalog-6d99d889c5-dx94w   1/1     Running   0          6m59s   10.24.1.71   gke-shustava-default-pool-bad0f39a-08fj   <none>           <none>
static-server-1-98d4c4b45-mt2kb              1/1     Running   0          16s     10.24.0.43   gke-shustava-default-pool-bad0f39a-wr0v   <none>           <none>
static-server-7c7889999f-nj5x9               1/1     Running   0          108s    10.24.1.73   gke-shustava-default-pool-bad0f39a-08fj   <none>           <none>
```
<img width="919" alt="Screen Shot 2021-01-27 at 4 06 44 PM" src="https://user-images.githubusercontent.com/10640505/106070699-d09b7f80-60b9-11eb-84aa-729ca84914f9.png">

These are my two services:
service 1:
<details>
```
apiVersion: v1
kind: Service
metadata:
  name: static-server
  annotations:
    'consul.hashicorp.com/service-sync': 'true'
    'consul.hashicorp.com/service-name': foo
spec:
  selector:
    app: static-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: static-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-server
  template:
    metadata:
      name: static-server
      labels:
        app: static-server
    spec:
      containers:
        - name: static-server
          image: ishustava/http-echo:latest
          command:
          - "/bin/sh"
          - "-ec"
          - |
            /http-echo -listen=:8080 -text="hello world"
          ports:
            - containerPort: 8080
              name: http
      serviceAccountName: static-server
```

</details>

service 2:
<details>
apiVersion: v1
kind: Service
metadata:
  name: static-server-1
  annotations:
    'consul.hashicorp.com/service-sync': 'true'
    'consul.hashicorp.com/service-name': foo
spec:
  selector:
    app: static-server-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: static-server-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-server-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-server-1
  template:
    metadata:
      name: static-server-1
      labels:
        app: static-server-1
    spec:
      containers:
        - name: static-server-1
          image: ishustava/http-echo:latest
          command:
          - "/bin/sh"
          - "-ec"
          - |
            /http-echo -listen=:8080 -text="hello world"
          ports:
            - containerPort: 8080
              name: http
      serviceAccountName: static-server-1
</details>

Is your confusion coming from the fact that the instances are on the same node regardless of the Kubernetes node where they're running? If so, this is expected when you're using catalog sync. The two instances will be registered with a single virtual node called `k8s-sync`. You could read more about it in our [docs](https://www.consul.io/docs/k8s/service-sync#kubernetes-to-consul).
