### ISSUE TITLE
consul k8s sync statically setting pod status to healthy

### ISSUE THREAD

**Issue by nabilmasri0** [hashicorp/consul-k8s#4207]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Overview

when syncing k8s services to consul the k8s healthcheck is always set to "healthy" regardless of the actual health status

### Recreation scenario
1. consul deployed with the following values
```
syncCatalog:
  enabled: true
  default: true
  toConsul: true
  k8sAllowNamespaces: ["ns"]
  toK8S: false
  addK8SNamespaceSuffix: false      
  consulWriteInterval: 5s
connectInject:
  enabled: false
```
2. Scale new pods
scale a certain deployment to more replicas, they will be added to consul with status healthy even before passing the k8s health check

### Context
the healthcheck status is set to passing regardless of the the actual endpoint status
https://github.com/hashicorp/consul-k8s/blob/main/control-plane/catalog/to-consul/resource.go#L797

the Endpoint object from discovery/v1 does expose an EndpointConditions object from which the actual status can be retrieved
