### ISSUE TITLE
ServiceResolver admission webhook doesn't match Consul API behavior

### ISSUE THREAD

**Issue by chrstein0** [hashicorp/consul-k8s#4526]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

When trying to create a `ServiceResolver` resource with failover datacenters, the admission controller returns the following error, even though the same `service-resolver` resource can be created through the Consul CLI or API successfully: [`cross-datacenter failover is only supported in the default partition`](https://github.com/hashicorp/consul-k8s/blob/v1.6.3/control-plane/api/v1alpha1/serviceresolver_types.go#L667-L670). 

This behavior is present in v1.3.9. I also tested this in v1.6.3 and had the same issue. The only related issue I could find is in the consul repo: https://github.com/hashicorp/consul/issues/21683

### Reproduction Steps

1. Create a new Helm release

```
helm upgrade consul-edge hashicorp/consul --install --kube-context k3d-local-consul \
--version 1.6.3 --create-namespace -n consul-local \
--set global.acls.manageSystemACLs=true \
--set connectInject.enabled=true \
--set syncCatalog.enabled=false \
--set server.replicas=3 \
--set global.tls.enabled=true \
--set ui.enabled=true \
--set global.datacenter=dc1
```

2. Try to apply the following resources

```yaml
# consul.yml
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: k8s-mesh-test-server
spec:
  protocol: http
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: k8s-mesh-test-server
spec:
  destination:
    name: k8s-mesh-test-server
  sources:
  - name: k8s-mesh-test-client
    action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: k8s-mesh-test-server
spec:
  subsets:
    k8s-mesh-test-server-northamerica:
      filter: "Service.Meta.failureset == northamerica"
    k8s-mesh-test-server-europe:
      filter: "Service.Meta.failureset == europe"
  failover:
    k8s-mesh-test-server-northamerica:
      datacenters: ['use1-4-0', 'usw2-2-0']
    k8s-mesh-test-server-europe:
      datacenters: ['euw1-1-0', 'euc1-1-0']
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceRouter
metadata:
  name: k8s-mesh-test-server
spec:
  routes:
    - match:
        http:
          header:
            - name: x-failoverset
              exact: 'northamerica'
      destination:
        service: k8s-mesh-test-server
        serviceSubset: k8s-mesh-test-server-northamerica
    - match:
        http:
          header:
            - name: x-failoverset
              exact: 'europe'
      destination:
        service: k8s-mesh-test-server
        serviceSubset: k8s-mesh-test-server-europe
```

```
kubectl -n consul-local apply -f consul.yml

servicedefaults.consul.hashicorp.com/k8s-mesh-test-server created
serviceintentions.consul.hashicorp.com/k8s-mesh-test-server created
servicerouter.consul.hashicorp.com/k8s-mesh-test-server created
Error from server: error when creating "consul.yml": admission webhook "mutate-serviceresolver.consul.hashicorp.com" denied the request: serviceresolver.consul.hashicorp.com "k8s-mesh-test-server" is invalid: [spec.failover[k8s-mesh-test-server-europe].datacenters: Invalid value: []string{"euw1-1-0", "euc1-1-0"}: cross-datacenter failover is only supported in the default partition, spec.failover[k8s-mesh-test-server-northamerica].datacenters: Invalid value: []string{"use1-4-0", "usw2-2-0"}: cross-datacenter failover is only supported in the default partition]
````

3. Verify the resources exist

```
# Open a new terminal and run...
kubectl -n consul-local port-forward consul-edge-consul-server-1 8501

# Go back to original terminal and run...
CONSUL_HTTP_TOKEN=$(kubectl -n consul-local get secret consul-edge-consul-bootstrap-acl-token -o json | jq -r .data.token | base64 --decode)

# service-defaults
curl -s -k --header "X-Consul-Token: ${CONSUL_HTTP_TOKEN}" https://localhost:8501/v1/config/service-defaults | jq
[
  {
    "Kind": "service-defaults",
    "Name": "k8s-mesh-test-server",
    "Protocol": "http",
    "TransparentProxy": {},
    "MeshGateway": {},
    "Expose": {},
    "Meta": {
      "consul.hashicorp.com/source-datacenter": "dc1",
      "external-source": "kubernetes"
    },
    "Hash": 8311495337118033813,
    "CreateIndex": 43,
    "ModifyIndex": 43
  }
]

# service-intentions
curl -s -k --header "X-Consul-Token: ${CONSUL_HTTP_TOKEN}" https://localhost:8501/v1/config/service-intentions | jq
[
  {
    "Kind": "service-intentions",
    "Name": "k8s-mesh-test-server",
    "Sources": [
      {
        "Name": "k8s-mesh-test-client",
        "Action": "allow",
        "Precedence": 9,
        "Type": "consul"
      }
    ],
    "Meta": {
      "consul.hashicorp.com/source-datacenter": "dc1",
      "external-source": "kubernetes"
    },
    "Hash": 5004903626656845290,
    "CreateIndex": 44,
    "ModifyIndex": 44
  }
]

# service-router
curl -s -k --header "X-Consul-Token: ${CONSUL_HTTP_TOKEN}" https://localhost:8501/v1/config/service-router | jq    
[]

# check the status of the ServiceRouter resource
kubectl get servicerouter -o json | jq '.items.[0].status'
{
  "conditions": [
    {
      "lastTransitionTime": "2025-04-23T16:57:05Z",
      "message": "writing config entry to consul: Unexpected response code: 500 (rpc error making call: service \"k8s-mesh-test-server\" does not have a subset named \"k8s-mesh-test-server-northamerica\")",
      "reason": "ConsulAgentError",
      "status": "False",
      "type": "Synced"
    }
  ],
  "lastSyncedTime": "2025-04-23T16:48:56Z"
}

# service-resolver
curl -s -k --header "X-Consul-Token: ${CONSUL_HTTP_TOKEN}" https://localhost:8501/v1/config/service-resolver | jq
[]

# make sure the resource doesn't exist in k8s
kubectl get serviceresolver -A
No resources found
```

4. Convert the `ServiceResolver` resource to json

```
# service-resolver.json
{
    "Kind": "service-resolver",
    "Name": "k8s-mesh-test-server",
    "Subsets": {
        "k8s-mesh-test-server-northamerica": {
            "Filter": "Service.Meta.failureset == northamerica"
        },
        "k8s-mesh-test-server-europe": {
            "Filter": "Service.Meta.failureset == europe"
        }
    },
    "Failover": {
        "k8s-mesh-test-server-northamerica": {
            "Datacenters": ["use1-4-0", "usw2-2-0"]
        },
        "k8s-mesh-test-server-europe": {
            "Datacenters": ["euw1-1-0", "euc1-1-0"]
        }
    }
}
```

5. Try to create service-resolver.json using the API

```
curl -s -k --header "X-Consul-Token: ${CONSUL_HTTP_TOKEN}" --request PUT --data @service-resolver.json https://localhost:8501/v1/config
true%

# see if it exists
curl -s -k --header "X-Consul-Token: ${CONSUL_HTTP_TOKEN}" https://localhost:8501/v1/config/service-resolver | jq
[
  {
    "Kind": "service-resolver",
    "Name": "k8s-mesh-test-server",
    "Subsets": {
      "k8s-mesh-test-server-europe": {
        "Filter": "Service.Meta.failureset == europe"
      },
      "k8s-mesh-test-server-northamerica": {
        "Filter": "Service.Meta.failureset == northamerica"
      }
    },
    "Failover": {
      "k8s-mesh-test-server-europe": {
        "Datacenters": [
          "euw1-1-0",
          "euc1-1-0"
        ]
      },
      "k8s-mesh-test-server-northamerica": {
        "Datacenters": [
          "use1-4-0",
          "usw2-2-0"
        ]
      }
    },
    "Hash": 16080747397586730606,
    "CreateIndex": 392,
    "ModifyIndex": 392
  }
]

# see if the service-router exists now as well
curl -s -k --header "X-Consul-Token: ${CONSUL_HTTP_TOKEN}" https://localhost:8501/v1/config/service-router | jq  
[
  {
    "Kind": "service-router",
    "Name": "k8s-mesh-test-server",
    "Routes": [
      {
        "Match": {
          "HTTP": {
            "Header": [
              {
                "Name": "x-failoverset",
                "Exact": "northamerica"
              }
            ]
          }
        },
        "Destination": {
          "Service": "k8s-mesh-test-server",
          "ServiceSubset": "k8s-mesh-test-server-northamerica"
        }
      },
      {
        "Match": {
          "HTTP": {
            "Header": [
              {
                "Name": "x-failoverset",
                "Exact": "europe"
              }
            ]
          }
        },
        "Destination": {
          "Service": "k8s-mesh-test-server",
          "ServiceSubset": "k8s-mesh-test-server-europe"
        }
      }
    ],
    "Meta": {
      "consul.hashicorp.com/source-datacenter": "dc1",
      "external-source": "kubernetes"
    },
    "Hash": 8130316311348268595,
    "CreateIndex": 394,
    "ModifyIndex": 394
  }
]

# verify the status of the k8s ServiceRouter resource
kubectl get servicerouter -o json | jq '.items.[0].status'
{
  "conditions": [
    {
      "lastTransitionTime": "2025-04-23T16:59:42Z",
      "status": "True",
      "type": "Synced"
    }
  ],
  "lastSyncedTime": "2025-04-23T16:59:42Z"
}
```

### Logs

See above

### Expected behavior

The `ServiceResolver` CRD should be able to create the same resources as the Consul API.

### Environment details

- `consul-k8s` version: v1.6.3 (also exists in v1.3.9)
- `values.yaml` used to deploy the helm chart: see above
- Kubernetes version: v1.30.6 (and k8s v1.26.15 w/ consul-k8s v1.3.9)
- Cloud Provider (If self-hosted, the Kubernetes provider utilized): EKS (k3d was used to easily create repro steps) 
- Networking CNI plugin in use: aws-cni
