### ISSUE TITLE
Enabling DogStatsD Disables Datadog Integration Metrics

### ISSUE THREAD

**Issue by vipulx44** [hashicorp/consul-k8s#4544]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

When enabling global.metrics.datadog.dogstatsd.enabled: true in the Consul Helm chart, the chart automatically sets the annotation:
```ad.datadoghq.com/consul.metrics_exclude: "true"```

This causes the Datadog Agent to skip all HTTP-based integration metric collection for the Consul container, disabling key metrics such as:

- consul.peers
- consul.catalog.services_up
- consul.catalog.total_nodes
- consul.catalog.services_count

These are core metrics provided by the [Datadog Consul integration](https://docs.datadoghq.com/integrations/consul/?tab=containerized#metrics).

### Reproduction Steps

Steps to reproduce this issue, eg:

1. Install Consul via Helm with DogStatsD enabled:
```
    metrics:
      enabled: true
      enableAgentMetrics: true
      enableHostMetrics: true
      disableAgentHostName: true
      datadog:
        enabled: true
        dogstatsd:
          enabled: true
          dogstatsdTags: ["source:consul", "consul_service:consul-server", "env:<env_name>"]
```
2. Observe that the Helm chart injects:
```ad.datadoghq.com/consul.metrics_exclude: "true"```
3. Result: Integration metrics are not received by datadog.

### Expected behavior

Enabling DogStatsD should not implicitly disable the default Datadog integration metrics. Users should be able to collect both:

1. Custom Consul metrics via DogStatsD
2. Integration metrics via HTTP endpoints

### Environment details

- Consul Helm chart version: [v1.6.2]
- Kubernetes: EKS 1.31
