### ISSUE TITLE
Injector is perpetually failing and restarting

### ISSUE THREAD

**Issue by spachava753** [hashicorp/consul-k8s#537]
### Overview of the Issue

The webhook injector is constantly failing after being deployed using the consul helm chart to a dev cluster. When deploying the helm chart on Minikube, the injector starts up fine. Comparing the logs from the minikube and dev cluster, I can't spot the problem. Another issue is I don't understand why the injector is trying to do a TLS handshake on random ports, `TLS handshake error from 10.244.1.1:34130`. Each time the injector container is restarted, it tries a different port. Could someone explain why its trying to do this and for what?

### Reproduction Steps

```shell
secret=$(consul keygen)

helm repo add hashicorp https://helm.releases.hashicorp.com

# deploy rancher's local path dynamic storageclass
kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml

# create the gossip key
kubectl create secret generic consul-gossip-encryption-key --from-literal=key=${secret} --dry-run=client -o yaml > consul-gossip-encryption-key.yml
kubectl apply -f consul-gossip-encryption-key.yml

# Install consul connect
helm install -f secure-consul-local-path.yml consul hashicorp/consul --version "0.31.1" --set 'server.extraConfig="{"log_level": "DEBUG"}"'
```

### Logs

<details>
  <summary>Injector logs</summary>

```
Listening on ":8080"...
2021/06/17 15:18:47 http: TLS handshake error from 10.244.1.1:34130: No certificate available.
Error loading TLS keypair: tls: failed to find any PEM data in certificate input
2021/06/17 15:18:48 http: TLS handshake error from 10.244.1.1:34138: No certificate available.
Error listening: http: Server closed
terminated received, shutting down
E0617 15:18:48.339431       1 controller.go:124] error syncing cache
E0617 15:18:48.339503       1 controller.go:124] error syncing cache
2021-06-17T15:18:49.539Z [INFO]  healthCheckResource: received stop signal, shutting down
```

</details>

### Expected behavior

I expected the injector to work. The rest of the components are running and ready.
```
NAME                                                          READY   STATUS     RESTARTS   AGE
consul-connect-injector-webhook-deployment-6696d86c77-7tkvm   0/1     Running    403        17h
consul-controller-5f96d874f4-6bknq                            1/1     Running    0          17h
consul-dk5bz                                                  1/1     Running    0          17h
consul-np4d6                                                  1/1     Running    0          17h
consul-server-0                                               1/1     Running    0          17h
consul-webhook-cert-manager-5745cbb9d-qmzsx                   1/1     Running    0          17h
```

### Environment details

If not already included, please provide the following:
- `consul-k8s` version:  1.9.4
- `consul-helm` version: 0.31.1
- `values.yaml` used to deploy the helm chart:
```yaml
global:
  name: consul
  enabled: true
  datacenter: dc1
  gossipEncryption:
    secretName: "consul-gossip-encryption-key"
    secretKey: "key"
  tls:
    enabled: true
    enableAutoEncrypt: true
    verify: true
  acls:
    manageSystemACLs: true
server:
  replicas: 1
  securityContext:
    runAsNonRoot: false
    runAsUser: 0
  storageClass: local-path
connectInject:
  enabled: true
controller:
  enabled: true
```
