### ISSUE TITLE
Consul's redirect-traffic command should run with the ACL token when ACLs are enabled

### ISSUE THREAD

**Issue by ishustava** [hashicorp/consul-k8s#570]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

When ACLs are enabled, currently the `redirect-traffic` command does not pass an ACL token that we get after running `consul login` inside the `consul-connect-inject-init` container. This did not fail in our acceptance tests because by default we're enabling DNS. When DNS is enabled, we will also attach a policy to the anonymous token that allows it to read any service. We will also do that when you're enabling multi-cluster federation. When those two features are not enabled, the init container will fail because the `redirect-traffic` command will get a 403 from consul when trying to read the proxy service.

### Reproduction Steps

Install the latest helm chart with ACL enabled and DNS disabled:
```
helm install consul \
--set dns.enabled=false \ 
--set global.name=consul \
--set global.acls.manageSystemACLs=true \
--set server.replicas=1 \
--set connectInject.enabled=true \
hashicorp/consul
```

Install static-server service:
```
---
apiVersion: v1
kind: Service
metadata:
  name: static-server
spec:
  selector:
    app: static-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: static-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-server
  template:
    metadata:
      name: static-server
      labels:
        app: static-server
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
    spec:
      containers:
        - name: static-server
          image: docker.mirror.hashicorp.services/hashicorp/http-echo:latest
          args:
            - -text="hello world"
            - -listen=:8080
          ports:
            - containerPort: 8080
              name: http
      terminationGracePeriodSeconds: 0
      serviceAccountName: static-server

```

See that the pod fails to come up because the init container errors

### Logs 
<details>
<summary>
kubectl logs -f deploy/static-server -c consul-connect-inject-init
</summary>

```
2021-07-26T20:13:25.336Z [INFO]  Consul login complete
2021-07-26T20:13:25.418Z [INFO]  Unable to find registered services; retrying
2021-07-26T20:13:26.420Z [INFO]  Unable to find registered services; retrying
2021-07-26T20:13:27.422Z [INFO]  Unable to find registered services; retrying
2021-07-26T20:13:28.424Z [INFO]  Unable to find registered services; retrying
2021-07-26T20:13:29.425Z [INFO]  Unable to find registered services; retrying
2021-07-26T20:13:30.427Z [INFO]  Unable to find registered services; retrying
2021-07-26T20:13:31.429Z [INFO]  Unable to find registered services; retrying
2021-07-26T20:13:32.519Z [INFO]  Registered service has been detected: service=static-server
2021-07-26T20:13:32.519Z [INFO]  Registered service has been detected: service=static-server-sidecar-proxy
2021-07-26T20:13:32.520Z [INFO]  Connect initialization completed
==> Failed to create configuration to apply traffic redirection rules: failed to fetch proxy service from Consul Agent: Unexpected response code: 403 (Permission denied)
```

</details>

### Expected behavior

It should work!

### Environment details
Helm chart `v0.32.1` using the default versions for consul, consul-k8s and envoy.

### Additional Context

We need set the token here if ACLs are enabled:

https://github.com/hashicorp/consul-k8s/blob/8946d1acf2423f0ceaa5357fb8d68fadeca250db/connect-inject/container_init.go#L314-L333

Similar to how we do it for `consul connect envoy -bootstrap` command:
https://github.com/hashicorp/consul-k8s/blob/8946d1acf2423f0ceaa5357fb8d68fadeca250db/connect-inject/container_init.go#L302-L304
