### ISSUE TITLE
How configure Terminating gateway to access to https service

### ISSUE THREAD

**Issue by Shige99011** [hashicorp/consul-k8s#583]
Hi, I have a question regarding Terminating gateway configuration.
Now, I'm configuring Terminating gateway to access to external service that is provided with _**https**_ protocol by self-signed certificate.
When try to call the service, the error happens as below:
```

$ curl -H "Host: api-service.ingress.consul" -v http://10.10.1.6/https-service/hello
*   Trying 10.10.1.6...
* TCP_NODELAY set
* Connected to 10.10.1.6 (10.10.1.6) port 80 (#0)
> GET /https-service/hello HTTP/1.1
> Host: api-service.ingress.consul
> User-Agent: curl/7.55.1
> Accept: */*
>
< HTTP/1.1 503 Service Unavailable
< Content-Length: 95
< Content-Type: text/plain
< Date: Fri, 30 Jul 2021 11:30:09 GMT
< Server: envoy
< X-Envoy-Upstream-Service-Time: 358
<
upstream connect error or disconnect/reset before headers. reset reason: connection termination* Connection #0 to host 10.10.1.6 left intact

```
It works for the external service that is provided with _**http**_ protocol.
How should Terminating gateway be configured for https service? (I'm not sure this is really caused by https, though)

the registration file for the external service:
```
{
  "Node": "Https Service",
  "Address": "https-service.com", 
  "NodeMeta": {
    "external-node": "true",
    "external-probe": "true"
  },
  "Service": {
    "ID": "https-service",
    "Service": "https-service",
    "Port": 52088
  }
}
```

The configuration for Terminating gateway:
```
apiVersion: consul.hashicorp.com/v1alpha1
kind: TerminatingGateway
metadata:
  name: terminating-gateway
spec:
  services:
    - name: https-service
```

Does it need to import the certificate of the server for https service?
if so, how should it be configured for Terminating gatway? 

My environment:
OS: ubuntu 20.04 on hyper-v
kubernetes: v1.21.3+k3s1
consul: v1.10.0
Consul helm chart: v0.32.1
(Consul helm chart was installed by command "helm install -f config.yaml consul hashicorp/consul --version "0.32.1"")
There is only one kubernetes node. 

Thanks for your help.

**Comment by blake** [comment]
Hi @Shige99011, in order to be able to connect to an HTTPS service, the [`CAFile`](https://www.consul.io/docs/connect/config-entries/terminating-gateway#cafile) parameter must be specified in the terminating gateway's configuration for the external service.

This is noted on docs for the terminating gateway config entry under the [TLS origination](https://www.consul.io/docs/connect/config-entries/terminating-gateway#tls-origination), and shown in the config example for securing the connecting using one-way TLS. Admittedly the docs don't sufficiently highlight this requirement, so its easy to overlook. I am fixing that as part of the changes in hashicorp/consul#10385.

The following configuration should work.

```yaml
apiVersion: consul.hashicorp.com/v1alpha1
kind: TerminatingGateway
metadata:
  name: us-west-gateway
spec:
  services:
    - name: billing
      caFile: /etc/ssl/certs/ca-certificates.crt
```

You may need to use a different `caFile` depending on the location of the default CA cert list for your OS, or if you are using private CA.

Hope this helps.

**Comment by Shige99011** [comment]
Thanks @blake for your reply. That's useful information.
I tried to specify the cert file by referring [this](https://discuss.hashicorp.com/t/terminating-gateway-cafile/20203) (I think this contains your suggestion as well). 

changed config.yaml after the secret creation:
```
terminatingGateways:
  enabled: true
  defaults:
    replicas: 1
  gateways:
    - name: terminating-gateway
      extraVolumes:
      - type: secret
        name: https-cert
```
the changed the manifest for terminating gateway:
```
apiVersion: consul.hashicorp.com/v1alpha1
kind: TerminatingGateway
metadata:
  name: terminating-gateway
spec:
  services:
    - name: https-service
      caFile: /consul/userconfig/https-cert/https-service-cert.pem

```

Then, error still happens as below:

```
C:\Users\shiobaya\.cert>curl -H "Host: api-service.ingress.consul" -v http://10.10.1.6/https-service/hello
*   Trying 10.10.1.6...
* TCP_NODELAY set
* Connected to 10.10.1.6 (10.10.1.6) port 80 (#0)
> GET /https-service/hello HTTP/1.1
> Host: api-service.ingress.consul
> User-Agent: curl/7.55.1
> Accept: */*
>
< HTTP/1.1 503 Service Unavailable
< Content-Length: 195
< Content-Type: text/plain
< Date: Sun, 01 Aug 2021 02:28:03 GMT
< Server: envoy
< X-Envoy-Upstream-Service-Time: 295
<
upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED* Connection #0 to host 10.10.1.6 left intact
```

But the error seems to mention SSL obviously. So I tried to simply call the service directly by using curl command with cert file. Then similar error has been returned:
```
$ curl --cert ./https-service-cert.pem https://test-service:8080/https-service/hello
curl: (77) schannel: next InitializeSecurityContext failed: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted.
```

From this, I guess this is caused by cert file itself. Is it correct? If so, I will  take a look into the cert file.

Thank you.
