### ISSUE TITLE
Allow container securityContext to be set by Helm chart

### ISSUE THREAD

**Issue by tarquin-the-brave** [hashicorp/consul-k8s#602]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

#### Is your feature request related to a problem? Please describe.

The output of the Helm chart fails to pass [`kubeaudit all`](https://github.com/Shopify/kubeaudit).

e.g. for the consul server statefulSet:

```
---------------- Results for ---------------

  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: RELEASE-NAME-consul-server
    namespace: default

--------------------------------------------

-- [error] CapabilityOrSecurityContextMissing
   Message: Security Context not set. The Security Context should be specified and all Capabilities should be dropped by setting the Drop list to ALL.
   Metadata:
      Container: consul

-- [error] AllowPrivilegeEscalationNil
   Message: allowPrivilegeEscalation not set which allows privilege escalation. It should be set to 'false'.
   Metadata:
      Container: consul

-- [warning] PrivilegedNil
   Message: privileged is not set in container SecurityContext. Privileged defaults to 'false' but it should be explicitly set to 'false'.                                     Metadata:
      Container: consul

-- [error] ReadOnlyRootFilesystemNil                                                                                                                                           Message: readOnlyRootFilesystem is not set in container SecurityContext. It should be set to 'true'.
   Metadata:                                                                                                                                                                      Container: consul
```

These can all be resolved by setting them in the [`container securityContext`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#securitycontext-v1-core) (which is different to the [`Pod securityContext`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#podsecuritycontext-v1-core)).

#### Feature Description

In the same manner as the Pod security context: expose fields in `values.yaml`, `containerSecurityContext`, under `client` and `server` sections and template in the given security context like so:

```
securityContext:
  {{- toYaml .Values.server.containerSecurityContext | nindent 12 }}
```

under the `container` field entry in the Pod specs for clients and servers.

As with the Pod securityContext, set secure defaults in `values.yaml`:

```
containerSecurityContext:
  privileged: false
  capabilities:
    drop:
      - ALL
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
```

**Question:** Are there any reasons why we _couldn't_ set any of the above for Consul client or server agents?

#### Use Case(s)

Wherever someone has the requirement for hardening the container securityContext

#### Contributions

I'm happy to make this change and submit a PR.

**Comment by kschoche** [comment]
Hi @tarquin-the-brave, thank you for filing this issue!
We've recently taken a look at this and come to the conclusion that yes it's a great idea and probably best practice to include securityContext's with every container. Right now we're still discussing internally what that would look like in terms of the minimum settings are for each securityContext.
We'd be happy to have some community involvement and hear about people's security/hardening requirements to help shape the decision!

**Comment by tarquin-the-brave** [comment]
Thanks @kschoche,

For us (Microsoft Cloud+AI, Azure for Operators) passing [`kubeaudit all`](https://github.com/Shopify/kubeaudit) is a fairly close analogue to our Pod spec hardening requirements.  This could be a reasonable easy thing to use in CI in this project.

The container securityContext I quote above, combine with the default Pod securityPolicy already provided by the Helm chart by default, and some AppArmour and SecComp annotations would be enough to satiate `kubeaudit all`.

Making our requirements roughly:

* containers runs as a non-root user that's not in the root group,
* containers must run with read only access to their root file system, using volumes for file needing write access,
* containers must not run privileged and Pod specs must prevent privilege escalation,
* capabilities must be generally dropped, with required capabilities explicitly added back in,
* and we also require some appArmour and secComp annotations, setting their respective profiles.

So for us being able to set the container securityContext is all that's missing to meet these requirements.

**Comment by lkysow** [comment]
NOTE: for servers we could expose a single `containerSecurityContext` but for clients there are also init containers: `client-acl-init`, `client-tls-init` that would need to be exposed.

Maybe:

```yaml
server:
  containerSecurityContexts:
    server:
      runAsNonRoot: true
      runAsGroup: 1000
      runAsUser: 100
      fsGroup: 1000

client:
  containerSecurityContexts:
    client: null
    aclInit: null
    tlsInit: null
```
