### ISSUE TITLE
Transparent Proxy CNI Plug-in: escalated privileges required on Consul containers

### ISSUE THREAD

**Issue by sankaranarayanan** [hashicorp/consul-k8s#635]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

The current implementation of Transparent Proxy on Consul K8s requires the init-container we run before Envoy and application containers start to have CAP_NET_ADMIN privileges. This may not be acceptable for more security-conscious customers. 

Writing our own CNI plugin for applying traffic redirection rules via iptables would enable us to delegate the actual running of the commands to kubelet instead of executing them in the init container.

---

Helm chart failed to install on aks, if azure-policy is enabled

**Steps to reproduce**
1. az aks enable-addons --addons azure-policy --name sampleCluster --resource-group samplegroups 
2. helm install consul hashicorp/consul -f config.yaml

Consul **config.yaml**

```yaml
global:
  name: consul
  datacenter: dc1
  image: hashicorp/consul:1.10.0
  metrics:
    enabled: true
    enableGatewayMetrics: true
controller:
  enabled: true
syncCatalog:
  enabled: true
  toConsul: true
  toK8S: false
  default: false
connectInject:
  enabled: true
  default: false
  envoyExtraArgs: "-l debug"
  metrics:
    defaultEnabled: true
    defaultEnableMerging: true
  transparentProxy:
    defaultEnabled: true
ui:
  enabled: true
  service:
    enabled: true
    type: LoadBalancer
ingressGateways:
  enabled: true
  defaults:
    replicas: 1
    service:
      type: LoadBalancer
      ports:
        - port: 80
meshGateway:
  enabled: true
  replicas: 1
```

**Error Log**
```
  Warning  FailedCreate      2s (x14 over 44s)  replicaset-controller  Error creating: admission webhook "validation.gatekeeper.sh" denied the request: [azurepolicy-psp-container-no-privilege-esc-30132221bc21e5b724da] Privilege escalation container is not allowed: ingress-gateway
[azurepolicy-psp-container-no-privilege-esc-30132221bc21e5b724da] Privilege escalation container is not allowed: consul-sidecar
[azurepolicy-psp-container-no-privilege-esc-30132221bc21e5b724da] Privilege escalation container is not allowed: copy-consul-bin
[azurepolicy-psp-container-no-privilege-esc-30132221bc21e5b724da] Privilege escalation container is not allowed: service-init
```
is there option to deploy consul with azure-policy enable in aks
