### ISSUE TITLE
helm:Consul helm 0.32.1 / consul 1.10.0 can't inject the service 

### ISSUE THREAD

**Issue by halbornteam** [hashicorp/consul-k8s#640]
### Overview of the Issue

We are on k8s 1.20 and provision the consul-connect for service mesh.  We have deployed the sample application as `static-client` and `static-server` which works properly. However, all of our services can't be started for automatic injection.  

It encounters the error 
>2021-07-16T07:31:52.194Z [ERROR] Unable to get Agent services: error="Unexpected response code: 403 (ACL not found)"
2021-07-16T07:31:53.197Z [ERROR] Unable to get Agent services: error="Unexpected response code: 403 (ACL not found)"
2021-07-16T07:31:54.204Z [INFO]  Unable to find registered services; retrying
2021-07-16T07:31:55.206Z [INFO]  Unable to find registered services; retrying
2021-07-16T07:31:56.210Z [INFO]  Unable to find registered services; retrying
2021-07-16T07:31:57.213Z [INFO]  Unable to find registered services; retrying

We have ACL enabled, and tried to redeploy our service.  The service name matches the service account name. 

### Reproduction Steps

helm -n test-consul install consul hashicorp/consul -f consu.yml

1. When running helm install with the following `values.yml`:
```
  gossipEncryption:
    # secretName is the name of the Kubernetes secret that holds the gossip
    # encryption key. The secret must be in the same namespace that Consul is installed into.
    secretName: "consul-gossip-encryption-key"
    # secretKey is the key within the Kubernetes secret that holds the gossip
    # encryption key.
    secretKey: "key"
  tls:
    # If true, the Helm chart will enable TLS for Consul
    # servers and clients and all consul-k8s components, as well as generate certificate
    # authority (optional) and server and client certificates.
    enabled: true

    enableAutoEncrypt: true
    serverAdditionalDNSSANs:
      - '*.consul'
      - '*.cluster.local'
      - '*.svc.cluster.local'
      - 'localhost.*'

    serverAdditionalIPSANs:
      - '127.0.0.1'
    verify: false
    httpsOnly: true

  acls:
    manageSystemACLs: true
 connect: true
connectInject:
  # True if you want to enable connect injection. Set to "-" to inherit from
  # global.enabled.
  enabled: true
  default: true 
```

1. View error

  --->

### Logs

kubectl -n bots logs -f pod_name consul-connect-inject-init

2021-07-16T07:44:32.721Z [INFO]  Check to ensure a Kubernetes service has been created for this application.
2021-07-16T07:44:33.723Z [INFO]  Unable to find registered services; retrying
2021-07-16T07:44:34.725Z [INFO]  Unable to find registered services; retrying
2021-07-16T07:44:35.730Z [INFO]  Unable to find registered services; retrying
2021-07-16T07:44:36.780Z [INFO]  Unable to find registered services; retrying
2021-07-16T07:44:37.784Z [INFO]  Unable to find registered services; retrying
2021-07-16T07:44:38.787Z [INFO]  Unable to find registered services; retrying
2021-07-16T07:44:39.790Z [INFO]  Unable to find registered services; retrying
2021-07-16T07:44:40.794Z [INFO]  Unable to find registered services; retrying
2021-07-16T07:44:41.799Z [INFO]  Unable to find registered services; retrying
2021-07-16T07:44:42.801Z [INFO]  Unable to find registered services; retrying
2021-07-16T07:44:42.801Z [INFO]  Check to ensure a Kubernetes service has been created for this application.
2021-07-16T07:44:43.812Z [INFO]  Unable to find registered services; retrying
2021-07-16T07:44:43.812Z [ERROR] Timed out waiting for service registration: error="did not find correct number of services: 0"

--->

### Expected behavior

It init sucessfully and register to consul.
