### ISSUE TITLE
helm:Federation failed in IPv6-only Kubernetes cluster

### ISSUE THREAD

**Issue by OpenetCK** [hashicorp/consul-k8s#646]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
 * Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
 * If you are interested in working on this issue or have submitted a pull request, please leave a **comment**

---

### Overview of the Issue

In the IPv6-only cluster, the HOST_IP is resolved to for example `fc00:f853:ccd:e793::2`.

Components such as mesh-gateway, connect-injector-webhook are not working because the environment variable of the containers mapped to the following:
```
          env:
            - name: CONSUL_HTTP_ADDR
              value: https://$(HOST_IP):8501
```

This leads to the error during the Consul startup:
```
Invalid Consul HTTP address: address fc00:f853:ccd:e793::2:8501: too many colons in address
```

Should it render to `https://[$(HOST_IP)]:8501` with the bracket on the HOST_IP if it is installed in the IPv6 only cluster

### Reproduction Steps

Install via Consul Helm chart in a IPv6 only cluster with federation enabled. For example the values file below are used
```
global:
  tls:
    enabled: true

  federation:
    enabled: true
    createFederationSecret: true

  acls:
    manageSystemACLs: true
    createReplicationToken: true

  gossipEncryption:
    secretName: consul-gossip-encryption-key
    secretKey: key

connectInject:
  enabled: true

meshGateway:
  enabled: true
  replicas: 1
```

### Logs

```
Invalid Consul HTTP address: address fc00:f853:ccd:e793::2:8501: too many colons in address
```

### Expected behavior

Able to install Consul in IPv6-only cluster

### Environment details

- `consul-k8s` version: 0.25.0
- `consul-helm` version: 0.31.1
