### ISSUE TITLE
helm: connection failure

### ISSUE THREAD

**Issue by HofmannZ** [hashicorp/consul-k8s#648]
Yesterday overnight some of our services started throwing the flowing error:

```
upstream connect error or disconnect/reset before headers. reset reason: connection failure
```

The odd thing is that the behaviour persists on a fresh cluster.

**Allow me to describe the current setup:**

We have one deployment (A) that proxies traffic from the internet through a gateway (G). The deployment (A) calls another deployment (B) over HTTP. Both deployments have the `protocol` in the respective ServiceDefaults set to `http2`. And the ServiceIntentions are set up so that G can call A and A can call B.

These two deployments and gateway work fine.

We also have another deployment (C), which is called by deployment (B) over gRPC. This deployment has the `protocol` in the ServiceDefaults set to `grpc`. And the ServiceIntentions are set up so that B can call C.

This used to work, but broke overnight. Any idea what may have caused this?

Config of deployment (B)
```yaml
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: deployment-b
  namespace: foo
spec:
  protocol: http2
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: deployment-b
  namespace: foo
spec:
  destination:
    name: deployment-b
  sources:
    - name: deployment-a
      action: allow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-b
  namespace: foo
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: deployment-b
  name: deployment-b
  namespace: foo
spec:
  type: ClusterIP
  selector:
    app: deployment-b
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-b
  name: deployment-b-deployment
  namespace: foo
spec:
  selector:
    matchLabels:
      app: deployment-b
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 75%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service: "deployment-b"
        consul.hashicorp.com/connect-service-upstreams: deployment-c:3001
      labels:
        app: deployment-b
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: deployment-b
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: deployment-b
        image: deployment-b:v1.0.0
        env:
        - name: DEPLOYMENT_C_ADDRESS
          value: localhost:3001
        livenessProbe:
          ...
        readinessProbe:
          ...
        resources:
          limits:
            cpu: 160m
            memory: 400Mi
          requests:
            cpu: 80m
            memory: 200Mi
      serviceAccountName: deployment-b
      terminationGracePeriodSeconds: 30
```

Config of deployment (C)
```yaml
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: deployment-c
  namespace: foo
spec:
  protocol: grpc
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: deployment-c
  namespace: foo
spec:
  destination:
    name: deployment-c
  sources:
    - name: deployment-b
      action: allow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-c
  namespace: foo
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: deployment-c
  name: deployment-c
  namespace: foo
spec:
  type: ClusterIP
  selector:
    app: deployment-c
  ports:
    - name: grpc
      port: 3000
      targetPort: 3000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-c
  name: deployment-c-deployment
  namespace: foo
spec:
  selector:
    matchLabels:
      app: deployment-c
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 75%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service: "deployment-c"
      labels:
        app: deployment-c
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: deployment-c
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: deployment-c
        image: deployment-c:v1.0.0
        livenessProbe:
          ...
        readinessProbe:
          ...
        resources:
          limits:
            cpu: 160m
            memory: 400Mi
          requests:
            cpu: 80m
            memory: 200Mi
      serviceAccountName: deployment-c
      terminationGracePeriodSeconds: 30

```
