### ISSUE TITLE
helm:GKE Ingress Failing Health Checks

### ISSUE THREAD

**Issue by tdgeery** [hashicorp/consul-k8s#649]
### Overview of the Issue

Setup basic consul deployment via helm with ingress and service enabled. 

### Reproduction Steps

Steps to reproduce this issue, eg:

1. When running helm install with the following `values.yml`:
```
global:
  datacenter: gcp
  enabled: true
  name: consul-vault-dev
ui:
  enabled: true
  ingress:
    annotations: |-
      kubernetes.io/ingress.class: "gce-internal"
      kubernetes.io/ingress.regional-static-ip-name: "{name}"
    enabled: true
    hosts:
    - host: {hostname}
      path: /*
  service:
    annotations: 'cloud.google.com/neg: ''{"ingress": true}'''
    enabled: true
    type: ClusterIP
```

### Logs

Include any relevant logs.

Browser: `no healthy upstream`

### Environment details

If not already included, please provide the following:
- `consul-helm` version: 0.31.1

Additionally, please provide details regarding the Kubernetes Infrastructure, if known:
- Cloud Provider (If self-hosted, the Kubernetes provider utilized): GKE

Any other information you can provide about the environment/deployment.

I believe this is because GKE doesn't recognize the readinessprobe command and does health check on path `/` instead of `/ui/`.. If I manually modify the health check to `/ui/` the Ingress and Service work perfectly.
