### ISSUE TITLE
helm:consul resource requests default to very low values

### ISSUE THREAD

**Issue by GuusDeGraeve** [hashicorp/consul-k8s#651]
### Overview of the Issue

The consul helm chart specifies very low values by default as Kubernetes resource requests. 

```
resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "100Mi"
      cpu: "100m"
```

These values seem way below the consul hardware requirement specs for production usage. Wouldn't it be better to either get rid of these default values and just do `resources: {}` like the vault helm chart does or change these values to be more in line with the hardware requirement specs?

### Reproduction Steps

Steps to reproduce this issue, eg:

1. Deploy the helm chart without specifying the resources value.
2. Look at the resource requests for the server pods (default to the ones listed above)
