### ISSUE TITLE
helm:Support for external Ingress controllers

### ISSUE THREAD

**Issue by ghost** [hashicorp/consul-k8s#664]
I'm not sure if this is a pattern that's already supported, which if it is then the documentation isn't very clear.

I'm running multiple GKE clusters. They all have ingress controllers. They're very good ingress controllers that are very clever at what they do when you're building in Google Cloud.

I'm also running Consul as a Service Mesh. It's a very good service mesh, and I particularly enjoy injecting specific services across resources in a secure, mTLS-ed manner.

I want to leverage the proxy that is injected into these pods to secure the connection between the GCE Ingress controller, and the pods - not exactly an uncommon pattern.

Lets say I have a deployment manifest of an API like so:

#### deployment.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prodigy-api
  labels:
    app: prodigy-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prodigy-api
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-service: "prodigy-api"
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-port: "http"
      name: prodigy-api
      labels:
        app: prodigy-api
    spec:
      containers:
        - image: registry.gitlab.com/cto-uk/prodigy-api:<VERSION>
          name: prodigy
          ports:
            - containerPort: 8000
              name: http
          readinessProbe:
            httpGet:
              scheme: HTTP
              port: http
              path: /health
```

I can expose this deployment with in a pattern that allows GCE to expose it for all its Layer 7 HTTP(S) magic:

#### service.yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    beta.cloud.google.com/backend-config: '{"ports":{"80":"default"}}'
    cloud.google.com/neg: '{"exposed_ports": {"80":{}}}'
  name: prodigy-api
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: prodigy-api
      port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: prodigy-api
  type: NodePort
```

Note the `cloud.google.com/neg` annotation - which means that GKE will create a Google NEG for the deployment, which can then be leveraged by the HTTP(S) Load Balancer (these concepts can get confusing all in I know)

I can then create a said HTTP(S) Load Balancer in the form of a GCE Ingress Controller:

#### ingress.yaml
```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: prodigy-api
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
    - secretName: cto-tls
    - hosts:
        - api.example.com
  rules:
    - host: api.example.com
      http:
        paths:
          - backend:
              serviceName: prodigy-api
              servicePort: 80
            path: /*
```

### The issue
How do I go about securing the connection between the GCE LB, and the pods themselves?

The pods have the Consul sidecar attached, and the Envoy proxy.

Service Sync means that I have a first class Kubernetes Service available to reference in the Ingress manifest (it even has the `cloud.google.com/neg` annotation!) but it has no selector and thus no port, so the manifest is incomplete.

Any advice on how to put this together, or if I'm barking up the wrong tree entirely. TIA
