### ISSUE TITLE
helm:Kubernetes Service object not deleted with `helm uninstall`

### ISSUE THREAD

**Issue by thecosmicfrog** [hashicorp/consul-k8s#672]
I've noticed the Kubernetes **Service** object for `consul` is not deleted with a `helm uninstall`, meaning we need to go in afterwards and issue `kubectl delete service consul`. Is this an intentional decision or a bug?

Steps to reproduce:

1. Create an override values.yaml file containing the following:
```yaml
global:
  datacenter: sandbox

  gossipEncryption:
    secretName: "consul"
    secretKey: "CONSUL_GOSSIP_ENCRYPTION_KEY"

  tls:
    enabled: true
    httpsOnly: true
    enableAutoEncrypt: true
    serverAdditionalDNSSANs: ["'consul.service.consul'"]

server:
  replicas: 3
  bootstrapExpect: 3
  storage: 20Gi

dns:
  clusterIP: 172.20.53.53

ui:
  enabled: true
  service:
    type: 'LoadBalancer'

syncCatalog:
  enabled: true
```

2. Install **consul-helm** using the above values.yaml file:
`$> helm upgrade --install consul hashicorp/consul --version 0.21.0 --values values-override.yaml`

3. Uninstall **consul-helm**:
`$> helm uninstall consul`

4. Wait a few minutes and run `kubectl get all --all-namespaces | grep consul". Output:
```
default    service/consul    ExternalName    <none>    consul.service.consul    <none>    10m
```

Conclusion: helm uninstall does not remove `consul` ExternalName Service object.
