### ISSUE TITLE
helm:Proxied UI Authentication (via Additional Containers "sidecars" in the Server Pod/s)

### ISSUE THREAD

**Issue by kpurdon** [hashicorp/consul-k8s#675]
I'd like to propose supporting additional containers as "sidecars" in the Pod serving the Consul UI in order to allow for sidecar-based authentication proxies. This is something I'd be happy to add and test, if it's acceptable.

I generally use [Google Cloud IAP](https://cloud.google.com/iap) to protect services (like the Consul UI) exposed to the public internet. In order to validate the IAP requests (for services that I cannot add authentication too myself) I use [kpurdon/iapap](https://github.com/kpurdon/iapap) to validate the IAP request. This simple proxy service (with IAP validation) is intended to be run as a sidecar in whatever Pod is serving the service I want to protect exposed via a NodePort service. Then an ingress w/ all the IAP requirements is pointed at the NodePort resulting in an IAP protected internal service.

Ingress (w/ IAP) -> NodePort -> Pod [ IAPAP (Validate IAP) -> SomeService ]

While my use case is specific to Cloud IAP, this proposal should allow supporting any authentication method that works by injecting a sidecar proxy service.

Specifically I'd like to be able to:
- Include additional containers in the `server` spec (e.g. adding sidecars)
- Specify a targetPort on the `ui.service` configuration (to point to the sidecar proxy)

This could look something like the following `values.yml`:

``` yml
server:
  additionalContainers:
    - name: iapap-consul-ui
      spec: |
        image: kpurdon/iapap
        ports:
          - name: http
            containerPort: 9999
            env:
              IAPAP_TARGET: "http://localhost:8500" # the consul ui
        ...

ui:
  enabled: true
  type: NodePort
  targetPort: 9999
  ...
```

Of course this would all be totally optional to use and would result in a zero net change to the current defaults.
