### ISSUE TITLE
IngressGateway not reflecting changes after deleting and re-creating the resource. State of the resource is not changing and still pointing to the old state

### ISSUE THREAD

**Issue by MageshSrinivasulu** [hashicorp/consul-k8s#695]
**Issue happening in** : IngressGateway
**Environment**: Minikube
**Reproducing the issue**: Was able to consistently reproduce the issue

I am creating the IngressGateway with the below manifest file. For accessing the _**voting-consul-voting-frontend**_ service through the consul _testing.com and voting-consul-voting-frontend.ingress.consul_ are configured in **_hosts_** file on **_/drivers/etc_** to resolve to the 127.0.0.1. Since I have created the public ip for the ingress gateway through _**minikube tunnel**_ command.

**Ingress Gateway :**

```yaml
apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: ingress-gateway
spec:
  listeners:
    - port: 8080
      protocol: http
      services:
        - name: voting-consul-voting-frontend
          hosts:
          - "testing.com"
```

**Service Default :** 

```yaml
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: voting-consul-voting-frontend
spec:
  protocol: http
```

Once above things are created. I established the intention between ingress-gateway and to my voting-consul-voting-frontend. I was able to access the UI through **_http://testing.com:8080_**

When I tried to changes the **_hosts_** tag to **_voting-consul-voting-frontend.ingress.consul_** by deleting and re-creating the manifest file. I am not able to access the service through  **_http://voting-consul-voting-frontend.ingress.consul:8080_** getting **_404 not found issue_**.

Interesting part is I am still able to access the UI with **_http://testing.com:8080_**. Which shows that previous state is held somewhere and any new changes to manifest file is not getting reflected. Not sure if this is happening only with minikube.

**Ingress Gateway with new host tag :**

```yaml
apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: ingress-gateway
spec:
  listeners:
    - port: 8080
      protocol: http
      services:
        - name: voting-consul-voting-frontend
          hosts:
          - "voting-consul-voting-frontend.ingress.consul"
```
