### ISSUE TITLE
connect-inject namespace selector not enabling pods for namespaces by label after creating namespaces after install  

### ISSUE THREAD

**Issue by david-yu** [hashicorp/consul-k8s#698]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Reproduction Steps

Steps to reproduce this issue, eg:

1. Deploy Consul 0.33 with the following helm yaml: 

```
global:
  name: consul
  datacenter: dc1
  tls:
    enabled: true
server:
  replicas: 1
ui:
  enabled: true
meshGateway:
  enabled: true
  replicas: 1
connectInject:
  enabled: true
  namespaceSelector: |
    matchLabels:
      connect-inject : enabled
controller:
  enabled: true
```
2. Create namespace  and label namespace (before or after install)

```
kubectl create ns foo
kubectl label namespace foo connect-inject=enabled
```
3. Deploy pods with associated K8s service objects

```
kubectl apply -f tcp-echo.yaml -n foo
kubectl apply -f sleep.yaml -n foo
```

4. Inspect pods to see that pods are not connect-inject using 
```
kubectl describe pod tcp-echo-xyz -n foo
```

### Expected behavior

Pods in selected namespace should be connect-injected

**Comment by lkysow** [comment]
The connect-inject annotation is not supported on namespaces currently. See https://www.consul.io/docs/k8s/connect#installation-and-configuration for how to enable connect.

Either use the annotation on the pod or set the default inject in the helm chart to true and then use the `k8sAllowNamespaces` and `k8sDenyNamespaces` helm values (https://www.consul.io/docs/k8s/connect#controlling-injection-via-namespace).

I'll move this to a feature request.

**Comment by david-yu** [comment]
Closing as `connectInject.default` should be set to `true` in conjunction with the namespace selector. Below is what happens when the following config is used and deploying the same pods to multiple namespaces. 

`config.yaml`

```
global:
  name: consul
  datacenter: dc1
  tls:
    enabled: true
server:
  replicas: 1
ui:
  enabled: true
meshGateway:
  enabled: true
  replicas: 1
connectInject:
  enabled: true
  default: true
  namespaceSelector: |
    matchLabels:
      connect-inject : enabled
controller:
  enabled: true
```

```bash
❯ k get pods -n foo
NAME                        READY   STATUS    RESTARTS   AGE
tcp-echo-866d7f8dcb-wxqnt   2/2     Running   0          70s

❯ k get pods -n bar
NAME                        READY   STATUS    RESTARTS   AGE
tcp-echo-866d7f8dcb-n7j8s   1/1     Running   0          59s
```
