### ISSUE TITLE
Helm Chart v0.33.0 fails to deploy server pods in OpenShift 4

### ISSUE THREAD

**Issue by krarey** [hashicorp/consul-k8s#705]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

When deploying helm chart v0.33.0 to OpenShift 4 (in my case, a local CodeReady Containers instance), the consul-server StatefulSet fails to deploy due to bad filesystem permissions. During container launch a script is attempting to create the directory /consul/extra-config, which fails as OpenShift forces containers to launch as unprivileged users: https://github.com/hashicorp/consul-k8s/blob/24be51c58461e71365ca39f113dae0379f7a1b7c/charts/consul/templates/_helpers.tpl#L23-L29

Red Hat recommends the containing directory be owned by GID 0, or the directory pre-provisioned in the container image to avoid this issue: https://docs.openshift.com/container-platform/4.7/openshift_images/create-images.html

### Reproduction Steps

1. When running helm install with the following `values.yml`:
```
global:
  enabled: true
  name: consul
  domain: consul
  datacenter: crc
  image: 'hashicorp/consul-enterprise:1.10.1-ent'
  tls:
    enabled: true
    enableAutoEncrypt: true
    httpsOnly: false
  acls:
    manageSystemACLs: true
    createReplicationToken: true
  metrics:
    enabled: true
    enableAgentMetrics: true
  gossipEncryption:
    secretName: consul-gossip-encryption-key
    secretKey: key
  openshift:
    enabled: true
server:
  enabled: true
  replicas: 1
  bootstrapExpect: 1
  connect: true
  enterpriseLicense:
    secretName: 'consul-license'
    secretKey: 'key'
ui:
  enabled: true
connectInject:
  enabled: true
controller:
  enabled: true
prometheus:
  enabled: true
```
1. `consul-server-0` pod will fail to run and enter a crash/backoff loop reporting permission denied attempting to create `/consul/extra-config`

**Comment by GlueMA** [comment]
I had to mount an additional volume for the extra-config directory (in DaemonSet and StatefulSet):
```
volumeMounts:
  - name: extra-config
    mountPath: /consul/extra-config
 
volumes:
    - name: extra-config
      emptyDir: {}

```
This way both clients and servers do start.

**Comment by david-yu** [comment]
Hi @GlueMA Thanks for the feedback! 

We just recently published our Openshift Certified UBI images for Openshift which you can browse through the following links:

- [hashicorp/consul ](https://catalog.redhat.com/software/containers/hashicorp/consul/612d01d49f14588c41ebf67c)
- [hashicorp/consul-enteprise]( https://catalog.redhat.com/software/containers/hashicorp/consul-enterprise/612d0116eb34b736524936b2)
- [hashicorp/consul-k8s](https://catalog.redhat.com/software/containers/hashicorp/consul-k8s/612d017fbd674341b5c5fcd8)
- [hashicorp/consul-k8s-control-plane](https://catalog.redhat.com/software/containers/61524326bc74e0be7ca66c58)

After running the `oc import-image` command you should be able to install Consul on Kubernetes on Openshift without any issues. 

```
oc import-image hashicorp/consul:1.10.3-ubi --from=registry.connect.redhat.com/hashicorp/consul:1.10.3-ubi --confirm
oc import-image hashicorp/consul-k8s-control-plane:0.34.0-ubi --from=registry.connect.redhat.com/hashicorp/consul-k8s-control-plane:0.34.0-ubi --confirm
helm install -f config.yaml consul hashicorp/consul --version "0.34.1" --wait
```

Example Helm config.yaml
```
global:
  name: consul
  datacenter: dc1
  image: registry.connect.redhat.com/hashicorp/consul:1.10.3-ubi 
  imageK8s: registry.connect.redhat.com/hashicorp/consul-k8s-control-plane:0.34.0-ubi
  imagePullSecrets:
    - name: <insert image pull secret for RedHat RegistryService account>
  openshift:
    enabled: true
    
server:
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    enabled: true
    maxUnavailable: 0
    
client:
  enabled: true
  grpc: true
    
ui:
  enabled: true 
    
connectInject:
  enabled: true
  default: true
    
controller:
  enabled: true
```

We'll be updating our OpenShift learn guide to reflect that new workflow for using UBI images as that is the preferred path for users on OpenShift. Let me know if that works for you!
