### ISSUE TITLE
Alt-domain missing from the Chart?

### ISSUE THREAD

**Issue by Svisstack** [hashicorp/consul-k8s#744]
Did I understand correctly that this helm chart for some reason does not have the possibility to set alt-domain[1] along with the primary DNS domain? 

[1] https://www.consul.io/docs/agent/options#_alt_domain

**Comment by lkysow** [comment]
Hi! You can set any unexposed settings via the `server.extraConfig` and `client.extraConfig` values:

```yaml
server:
  extraConfig: |
    {"alt_domain": "your-domain"}
```
