### ISSUE TITLE
Disabling or removing 'consul.hashicorp.com/service-sync' annotation does nothing

### ISSUE THREAD

**Issue by BarthV** [hashicorp/consul-k8s#76]
### What i'm trying to do
* Consul-k8s is running with `-k8s-default-sync=false`
* Starting with a synced service :
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    consul.hashicorp.com/service-meta-OWNER: foobar
    consul.hashicorp.com/service-name: my-kubernetes-hosted-svc
    consul.hashicorp.com/service-sync: "true"
    consul.hashicorp.com/service-tags: foo,bar
[...]
```

### What is the problem
When we set `consul.hashicorp.com/service-sync` to `"false"` or if we remove it (using kubectl edit) :
* Consul-k8s does nothing
* Service is still synchronized

### What it should be doing (IMO)
* Removing all registered instances for this service when we remove (or disable) this annotation

The only way I find to do so is to delete this service and create it again without this annotation.

Did I missed something or is it the intended behavior ?
Thx a lot :) !
