### ISSUE TITLE
sync-catalog: K8s to Consul: NodePort register service with POD IP address

### ISSUE THREAD

**Issue by descrepes** [hashicorp/consul-k8s#8]
Hi,

I'm deploying Consul with Helm on an AKS cluster.
Everything is working fine except the NodePort service sync.
Every K8S service is registered by default with the POD IP address and the NodePort.
Shouldn't all the services register with the Node IP address instead of the POD one ?

From now on i'm bypassing this with the annotation `consul.hashicorp.com/service-port` to force the registration with the port from the endpoint.
So a service is registered with all the endpoints.

Best regards

**Comment by dikderoy** [comment]
facing same issue on bare-metal

**Comment by lindenle** [comment]
@descrepes Can you explain the workaround you used in more detail? I tried adding the port but I am still seeing errors when it tries to add the nodes.

**Comment by descrepes** [comment]
@lindenle In fact consul register the service with POD_IP:NodePort which is wrong.
You have to use the annotation in the service definition to use the container port instead of the NodePort. Here is a small example using helm:

> service.yaml

```
apiVersion: v1
kind: Service
metadata:
  name: {{ template "morpho.fullname" . }}
  labels:
    app: {{ template "morpho.name" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
  selector:
    app: {{ template "morpho.name" . }}
    release: {{ .Release.Name }}
```

> values.yaml

```
service:
  type: NodePort
  port: 5000
  annotations:
    consul.hashicorp.com/service-tags: "traefik.enable=true,traefik.frontend.rule=Host: morpho.mycompany.com,traefik.frontend.passHostHeader=true"
    consul.hashicorp.com/service-port: "5000"
```
Hope it will help !
