### ISSUE TITLE
Unable to deploy sidecar proxy to a sample pod with consul 1.10 (works fine with 1.9)

### ISSUE THREAD

**Issue by mike-code** [hashicorp/consul-k8s#844]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

I am running a **private** kubernetes cluster on GKE. I deployed consul (app version 1.10.3, chart version 0.36.0) and I was able to access consul ui. I can see the servers and client agents (on each node) running. I disregard errors during bootstrap as these are most likely more warnings than errors, stating that something is not ready yet.

If I deploy consul `1.9.4`, with chart version `0.31.1` using the same `values.yaml`, the sample application will deploy properly. 

I'd very much appreciate guidance on how can I debug this kind of issue as I'm kinda running in circles now, not knowing  _what_ was meant to happen and where can I look for clues on _why_ it failed to happen.

### Reproduction Steps

After bootstrapping consul cluster (with `manageSystemACLs` set to `true`) I tried to deploy `hashicorp/http-echo:latest` pod with `'consul.hashicorp.com/connect-inject': 'true'` annotation (see yaml at the bottom of this issue). 

Unfortunately the pod won't deploy due to sidecars not being able to initialise correctly.

I can see four containers associated with the pod I'm trying to deploy 

```
NAME↑                           PF     IMAGE                                          READY      STATE                INIT
consul-connect-inject-init      ●      hashicorp/consul-k8s-control-plane:0.36.0      false      Running              true
copy-consul-bin                 ●      consul:1.10.3                                  true       Completed            true
envoy-sidecar                   ●      envoyproxy/envoy-alpine:v1.18.4                false      PodInitializing      false
static-server                   ●      hashicorp/http-echo:latest                     false      PodInitializing      false
```

I assume that `envoy-sidecar` is waiting for `consul-connect-inject-init` to become ready. I assume that because I don't see _any_ logs in `envoy-sidecar` whatsoever. However, the `consul-connect-inject-init` yield quite a few logs, which may not even be tightly bound (see logs section below).

In GCP log explorer I can't see any other relevant logs other than the ones presented below.

### Logs

<details>
  <summary>consul-connect-inject-init</summary>

```shell
[INFO[]  Consul login complete
[ERROR] Unable to get Agent services: error="Unexpected response code: 403 (ACL not found)"
[ERROR] Unable to get Agent services: error="Unexpected response code: 403 (ACL not found)"
# (above line repeated around 20 times)
# <block beings>
[INFO] Unable to find registered services; retrying
[INFO] Unable to find registered services; retrying
# (above line repeated around 10 times)
Check to ensure a Kubernetes service has been created for this application. If your pod is not starting also check the connect-inject deployment logs.
# <block ends>
# (above block repeated many many times)
2021-11-05T02:14:30.233Z [INFO[]  Unable to find registered services; retrying
2021-11-05T02:14:30.233Z [ERROR[] Timed out waiting for service registration: error="did not find correct number of services: 0"
```

</details>

<details>
  <summary>consul-consul-connect-injector-webhook-deployment-6cdc7697c8mgr:sidecar-injector</summary>

```shell
2021-11-05T02:12:24.703Z    INFO    controller.endpoints    retrieved    {"name": "static-server", "ns": "default"}
2021-11-05T02:12:24.757Z    INFO    handler.connect    received pod    {"name": "static-server", "ns": "default"}
```

</details>

### Expected behavior

I would expect the sidecar to initialise properly, just like it does with consul version `1.9.4`.

### Environment details

**values.yaml**

```yaml
global:
  image: "consul:1.10.3"
  datacenter: gcp
  recursors:
    - '1.1.1.1'
    - '8.8.8.8'
  acls:
    manageSystemACLs: true
  tls:
    enabled: false

server:
  replicas: 3

connectInject:
  enabled: true
  default: false
  replicas: 1
```

**sample.yaml**
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: static-server
---
apiVersion: v1
kind: Service
metadata:
  name: static-server
spec:
  selector:
    app: static-server
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: static-server
  annotations:
    'consul.hashicorp.com/connect-inject': 'true'
spec:
  containers:
    - name: static-server
      image: hashicorp/http-echo:latest
      args:
        - -text="hello world"
        - -listen=:8080
      ports:
        - containerPort: 8080
          name: http
  serviceAccountName: static-server
```

**Comment by kschoche** [comment]
Hey @mike-code thanks for filing this issue!
One of the things that has changed between Consul 1.9.x and Consul 1.10.x is the requirement to have a Kube service in front of your applications. I see that you've added one which is great, but it looks like you're just missing the label selector on your pod so the k8s service can pick it up and register the pod with Consul :

```
apiVersion: v1
kind: Pod
metadata:
  name: static-server
  labels:
    app: static-server
  annotations:
    'consul.hashicorp.com/connect-inject': 'true'
spec:
  containers:
    - name: static-server
      image: hashicorp/http-echo:latest
      args:
        - -text="hello world"
        - -listen=:8080
      ports:
        - containerPort: 8080
          name: http
  serviceAccountName: static-server
```

I'm sorry if the logs are a bit confusing in this particular case, and we do have an informative message which would have printed in the init container that the service appears to be missing:
```
2021-11-05T02:56:50.426Z [INFO]  Check to ensure a Kubernetes service has been created for this application. If your pod is not starting also check the connect-inject deployment logs.
```
..but it looks like this is only printed in the case where ACLs are disabled, I think we could definitely improve the error messages here!

One other thing that could have helped find this is if do a describe on the kube service itself and see that it has no Endpoints:
```
demo $ kubectl describe svc static-server
Name:              static-server
Namespace:         default
Labels:            <none>
Annotations:       cloud.google.com/neg: {"ingress":true}
Selector:          app=static-server
Type:              ClusterIP
IP Families:       <none>
IP:                10.8.7.80
IPs:               10.8.7.80
Port:              <unset>  80/TCP
TargetPort:        8080/TCP
Endpoints:         <none>   <------- here
Session Affinity:  None
Events:            <none>
```

Whereas after adding the label you'll see:
```
demo $ kubectl describe svc static-server
Name:              static-server
Namespace:         default
Labels:            <none>
Annotations:       cloud.google.com/neg: {"ingress":true}
Selector:          app=static-server
Type:              ClusterIP
IP Families:       <none>
IP:                10.8.7.80
IPs:               10.8.7.80
Port:              <unset>  80/TCP
TargetPort:        8080/TCP
Endpoints:         10.4.0.26:8080   <------ here
Session Affinity:  None
Events:            <none>
demo $
```
