### ISSUE TITLE
Consul-Sync pointing to same Consul deregisters all services on K8S-Sync Node

### ISSUE THREAD

**Issue by webmutation** [hashicorp/consul-k8s#860]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

If two or more instances of consul-sync are running and pointing to the same Consul external service, all the services get unregistered and it goes into a loop of unregistering, registering services.

### Reproduction Steps

1. Create two EKS cluster
2. Deploy the Consul Helm chart with the k8s-sync service
```
# Requires to set the external Consul catalog URL parameter manually in the deloyment...

global:
  enabled: false

client:
  enabled: false

externalServers:
  enabled: true
  hosts:
    - '1.1.1.1'

syncCatalog:
  enabled: true
  k8sDenyNamespaces: ["kube-system", "kube-public"]
```
3. kubectl edit deployment consul-consul-sync-catalog
4. change value to point to the external Consul cluster
```
   - name: CONSUL_HTTP_ADDR
     value: http://external-consul
```

And the unregistering of the services starts to occur... some services show up, then all services show up then all services disappear. And this loop goes on forever

### Expected behavior

Services should not disappear, additional cluster connecting to Consul, should simply have their services registered.
Services should not be unregistered.
This is probably because the special k8s-sync node is being deleted or recreated...
