### ISSUE TITLE
Apply proxy defaults  config on k8s present no matches for kind "ProxyDefaults"

### ISSUE THREAD

**Issue by shuiyunwudi** [hashicorp/consul-k8s#906]
#### Question
when i follow the reference [multi-cluster proxydefaults ](https://www.consul.io/docs/k8s/installation/multi-cluster/kubernetes#proxydefaults )  to apply proxy defaults, it show error like that:
```
kubectl apply -f proxy-defaults.yaml
error: unable to recognize "proxy-defaults.yaml": no matches for kind "ProxyDefaults" in version "consul.hashicorp.com/v1alpha1"
```
however, the reference point out **apiVersion - Must be set to consul.hashicorp.com/v1alpha1**, [proxy-defaults reference](https://www.consul.io/docs/connect/config-entries/proxy-defaults)

Anyone know the reason and how to solve it?

### Helm Configuration
proxy-defaults.yaml:
```
apiVersion: consul.hashicorp.com/v1alpha1
kind: ProxyDefaults
metadata:
  name: global
spec:
  meshGateway:
    mode: local
```

### Environment details
consul-helm: 0.26.0;
consul: 1.8.3;
consul-k8s: 0.20.0
