### ISSUE TITLE
ingress-nginx controller with transparent proxy returning 502s

### ISSUE THREAD

**Issue by byrneo** [hashicorp/consul-k8s#916]
#### Question

I've deployed consul-connect on EKS v1.18 and have validated mTLS and service intentions *between* services on my cluster. 

I'm now trying to expose a (meshed) service to the outside world via an ingress-nginx controller. I think I am close to getting this to work except that I'm getting `502` errors. I've been following [this](https://www.consul.io/docs/k8s/connect/ingress-controllers) and am aware of https://github.com/hashicorp/consul-k8s/issues/430 

My ingress-nginx controller pods have successfully initialised and been mutated to include envoy sidecars. I can see that consul successfully registers ingress-nginx as a service. All good.

Next, I provisioned a service intention to permit traffic from ingress-nginx to the backend service.

Traffic from the outside world reaches the cluster via an AWS NLB.

However, when i try to CURL the (meshed) service from outside the cluster (i.e. via the external LB / ingress) I get `502` errors.

Logs from the ingress reveal:

```shell
kubectl logs -f -l app.kubernetes.io/name=ingress-nginx -c controller -n ingress-nginx-consul

2021/12/08 21:04:15 [error] 38#38: *5203 upstream prematurely closed connection while reading response header from upstream, client: <redacted>, server: echo-server.<redacted>.com, request: "GET /foo HTTP/2.0", upstream: "http://100.96.138.86:3000/foo", host: "echo-server.<redacted>.com"
2021/12/08 21:04:15 [error] 38#38: *5203 upstream prematurely closed connection while reading response header from upstream, client: <redacted>, server: echo-server.<redacted>.com, request: "GET /foo HTTP/2.0", upstream: "http://100.96.133.174:3000/foo", host: "echo-server.<redacted>.com"
<redacted> - - [08/Dec/2021:21:04:15 +0000] "GET /foo HTTP/2.0" 502 150 "-" "curl/7.54.0" 46 0.006 [default-echo-server-80] [] 100.96.133.174:3000, 100.96.138.86:3000, 100.96.133.174:3000 0, 0, 0 0.000, 0.004, 0.004 502, 502, 502 fe56bfda342b7f523b77bd8fba113dbd
```

I've attempted a few things like adding annotations to the ingress-controller Pods to exclude the CIDR of the external LBs to no avail. The only annotations on the ingress-controller pods currently are:

```
consul.hashicorp.com/connect-inject: true
consul.hashicorp.com/connect-inject-status: injected
consul.hashicorp.com/connect-service-port: http
consul.hashicorp.com/transparent-proxy-exclude-inbound-ports: 443, 8443
```

The ingress config I'm using:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx-internal-consul
    kubernetes.io/tls-acme: "true"
  name: echo-server
  namespace: default
spec:
  rules:
  - host: echo-server.<redacted>.com
    http:
      paths:
      - backend:
          serviceName: echo-server
          servicePort: 80
        path: /
  tls:
  - hosts:
    - echo-server.<redacted>.com
    secretName: echo-server-tls
```

Any suggestions as to what I may be missing? I've searched around and have seen suggestions that ingress-nginx with a transparent proxy should work happily with consul-connect.

### Helm Configuration

Environment details are below. Note: I did build the consul control plane from https://github.com/hashicorp/consul-k8s per:  https://github.com/hashicorp/consul-k8s/issues/912#issuecomment-988831999

Running `0.37.0` of the helm chart with:

```yaml
global:
  name: consul
  datacenter: dcloud-dev-aws
  metrics:
    enabled: true
    enableAgentMetrics: true
  acls:
    manageSystemACLs: true
server:
  replicas: 1
ui:
  enabled: true
connectInject:
  enabled: true
  default: false
controller:
  enabled: true
prometheus:
  enabled: true
```

Note: I did perform a

**Comment by byrneo** [comment]
Just to close the loop on this. As per guidance [here](https://discuss.hashicorp.com/t/cannot-integrate-nginx-ingress-controller-with-consul-502-bad-gateway/27720/3)

I just needed to update the `ServiceDefault` CRD for the backend (meshed) service to include:

```yaml
spec:
  transparentProxy:
    dialedDirectly: true
```

and now it is successfully exposed to the outside world via ingress-nginx!
