### ISSUE TITLE
Failure to run Consul server pods with default security context

### ISSUE THREAD

**Issue by manedurphy** [hashicorp/consul-k8s#941]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

I want to deploy Consul into a Kubernetes cluster using Helm. It seems that the pods running Consul server cannot access certain files due to permission errors. 

### Reproduction Steps

Here is my config.

```yaml
global:
  name: consul
  datacenter: homelab
  acls:
    manageSystemACLs: true
  gossipEncryption:
    autoGenerate: true
  tls:
    enabled: true
    enableAutoEncrypt: true
    verify: true
server:
  replicas: 3
  securityContext:
    runAsNonRoot: true
    runAsUser: 100
    runAsGroup: 1000
ui:
  enabled: true
  service:
    type: "NodePort"
connectInject:
  enabled: true
  default: false
  replicas: 3
  logLevel: "debug"
  k8sAllowNamespaces: ["*"]
  k8sDenyNamespaces: []
  metrics:
    defaultEnabled: true
  transparentProxy:
    defaultEnabled: true
    defaultOverwriteProbes: true
controller:
  enabled: true
syncCatalog:
  enabled: false
```

In order to get this to work, I have to make these changes to the `securityContext`:

```yaml
global:
  name: consul
  datacenter: homelab
  acls:
    manageSystemACLs: true
  gossipEncryption:
    autoGenerate: true
  tls:
    enabled: true
    enableAutoEncrypt: true
    verify: true
server:
  replicas: 3
  securityContext:
    runAsNonRoot: false
    runAsUser: 0
ui:
  enabled: true
  service:
    type: "NodePort"
connectInject:
  enabled: true
  default: false
  replicas: 3
  logLevel: "debug"
  k8sAllowNamespaces: ["*"]
  k8sDenyNamespaces: []
  metrics:
    defaultEnabled: true
  transparentProxy:
    defaultEnabled: true
    defaultOverwriteProbes: true
controller:
  enabled: true
syncCatalog:
  enabled: false
```

### Logs

```bash
kubectl logs -n consul consul-server-0
==> failed to setup node ID: open /consul/data/node-id: permission denied
```

### Expected behavior

I expect that everything in `/consul` is owned by the `consul` group, but the following is seen when running as root user

```bash
ls -l /consul

drwxrwsrwx    3 root     consul        4096 Dec 25 17:46 config
drwxr-xr-x    4 root     root          4096 Dec 25 17:46 data
drwxr-xr-x    2 root     consul        4096 Dec 25 17:46 extra-config
drwxr-xr-x    4 root     root          4096 Dec 25 17:46 tls
```

I appreciate any insight on the matter

**Comment by t-eckert** [comment]
In order to have the Consul volume to be owned by the Consul group, `server.securityContext.fsGroup` must be set to `1000`. I can understand the intuition that because the default value in the `values.yaml` file is `1000`, that would be set in the config if omitted (as in your first config). However, in our Helm chart, the YAML segment is copied into the deployment YAML (not line by line) so the `server.securityContext.fsGroup` is never getting set in your first config. Please try adding that line and see if it fixes your problem. Alternatively, you can remove the entire segment for `server.securityContext` which will result in the default configuration being used:

[values.yaml:L619](https://github.com/hashicorp/consul-k8s/blob/434f4bdc559cd5e0e2a461886337e215a99b1c6c/charts/consul/values.yaml#L619)
``` yaml
  securityContext:
    runAsNonRoot: true
    runAsGroup: 1000
    runAsUser: 100
    fsGroup: 1000
```
