### ISSUE TITLE
Service discovery issue: Consul envoy sidecar having stale state.

### ISSUE THREAD

**Issue by amit106679** [hashicorp/consul-k8s#943]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

We are working on canary deployments using consul and Gloo. Our final service starts giving 503 randomly. When we investigated we found that the consul envoy sidecar in Gloo is not refreshing when we do canary deployment of the application. A workaround we found was to restart gateway-proxy of Gloo. The issue seems to be related to consul only since the envoy sidecar of Gloo has stale state.

### Reproduction Steps

Make 2 versions of an application. Apply new service resolver when doing canary deployment. Check Gloo's envoy sidecar.

### Expected behavior

Gloo sidecar refreshes state resolving the service properly.

**Comment by ishustava** [comment]
Hey @amit106679 

Could you provide more details in the reproduction steps, including how you've deployed consul and gloo and the service resolver configuration you've applied? It'd also be good to see how you've deployed your applications. 

Also, how did you determine that Envoy has stale state?

**Comment by amit106679** [comment]
Hi @ishustava ,
We have deployed consul and Gloo through helm. 
Service Resolver:
We deploy our application through helm too. This is the service resolver definition where we change the canary and stable versions:
```
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: {{ $.Release.Name }}
spec:
  subsets:
    stable:
      filter: "Service.Meta.version == v{{ $.Values.stableVersion }}"
    canary:
      filter: "Service.Meta.version == v{{ $.Values.canaryVersion }}"
```
