### ISSUE TITLE
ProxyDefaults for selected service

### ISSUE THREAD

**Issue by Poweranimal** [hashicorp/consul-k8s#949]
#### Question

Hi there,

I wonder if it's possible to set `ProxyDefaults` for a selected service only.

##### Context
I have a specific service for which I want to add these additional envoy configurations only:
`config/envoy_extra_static_clusters_json`
and
`config/envoy_extra_static_listeners_json`

I don't want to apply these extra configurations to all of my `connect-services`, only to a selected service.

How can one achive this?

I look forward to your support.

**Comment by t-eckert** [comment]
Hi @Poweranimal, thank you for your question.

To set Envoy configuration overrides for a specific service, you can use `ServiceDefaults`. You can select your service by name and supply a spec for defining the Envoy config on that service. This will apply to all instances of the service, but from my understanding of the question that is ok, you just want to apply settings to a particular service, not a particular instance.

[This learn guide](https://learn.hashicorp.com/tutorials/consul/service-mesh-traffic-management#service-defaults) will take you through setting up `ServiceDefaults`.

Please let us know if this solves your problem or if you need additional help.

**Comment by Poweranimal** [comment]
Hi @t-eckert ,
Thanks a lot for your response.

In consul's doc for [ServiceDefaults](https://www.consul.io/docs/connect/config-entries/service-defaults) there's no mentioning of being able to define proxy envoy configs.
Am I missing something?

**Comment by t-eckert** [comment]
No, unfortunately you are right. I was mistaken. I talked to the team and got more insight. On Kubernetes, we control proxy service registration through the Endpoints Controller. It is possible that a feature could be written to allow users to set proxy service config which could be passed to the Endpoints Controller to modify this. As it stands, setting Envoy configurations on a particular service is not possible.

I would encourage you to open a new issue with this as a feature request so that we may consider it for future releases.

**Comment by Poweranimal** [comment]
I'm going to open an issue describe the feature.
However, is there a workaround for the time being?

I tried to create an `initContainer` that alters the generated `envoy-bootstrap.yaml` file once it gets created by the injected `consul-connect-inject-init` container. Unfortunately it fails.

The setup looks like this:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo-distributed-distributor
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: distributor
      app.kubernetes.io/instance: tempo-distributed
      app.kubernetes.io/name: tempo-distributed
  template:
    metadata:
      annotations:
        checksum/config: b8a24d00a8b0df773a04a849a73fb00b8c8a549fa2327882e6bb42d971050354
        consul.hashicorp.com/connect-inject: "true"
      labels:
        app.kubernetes.io/component: distributor
        app.kubernetes.io/instance: tempo-distributed
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: tempo-distributed
        app.kubernetes.io/version: 1.2.1
        helm.sh/chart: tempo-distributed-0.12.2
        tempo-gossip-member: "true"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/component: distributor
                    app.kubernetes.io/instance: tempo-distributed
                    app.kubernetes.io/name: tempo-distributed
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 100
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/component: distributor
                  app.kubernetes.io/instance: tempo-distributed
                  app.kubernetes.io/name: tempo-distributed
              topologyKey: kubernetes.io/hostname
      containers:
        - args:
            - -target=distributor
            - -config.file=/conf/tempo.yaml
            - -mem-ballast-size-mbs=1024
          image: docker.io/grafana/tempo:1.2.1
          imagePullPolicy: IfNotPresent
          name: distributor
          ports:
            - containerPort: 7946
              name: http-memberlist
              protocol: TCP
            - containerPort: 3100
              name: http
            - containerPort: 4317
              name: otlp-grpc
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 1
          resources: {}
          volumeMounts:
            - mountPath: /conf
              name: tempo-conf
            - mountPath: /envoy
              name: extra-envoy-bootstrap
            - mountPath: /consul/connect-inject
              name: consul-connect-inject-data
      serviceAccountName: tempo-distributed-distributor
      volumes:
        - configMap:
            name: tempo-distributed
          name: tempo-conf
        - configMap:
            name: extra-envoy-bootstrap
          name: extra-envoy-bootstrap
      initContainers:
        - name: inject-extra-envoy-bootstrap
          image: alpine:3.15.0
          command:
            - /bin/ash
            - -ec
          args:
            - |-
              apk add jq
              until [ -f /consul/connect-inject/envoy-bootstrap.yaml ]; do sleep 1 ; done
              jq --slurpfile config /envoy/extra-envoy-bootstrap.json '.static_resources.clusters += $config[0].static_resources.clusters | .static_resources.listeners += $config[0].static_resources.listeners' /consul/connect-inject/envoy-bootstrap.yaml > /tmp/envoy-bootstrap.yaml
              mv /tmp/envoy-bootstrap.yaml /consul/connect-inject/envoy-bootstrap.yaml
```

However, this manifest fails due to the undefined volume `inject-extra-envoy-bootstrap`, which gets injected by the consul operator.

```
The Deployment "tempo-distributed-distributor" is invalid: spec.template.spec.containers[0].volumeMounts[2].name: Not found: "consul-connect-inject-data"
```
