### ISSUE TITLE
Consul Server Advertise Public IP

### ISSUE THREAD

**Issue by kholisrag** [hashicorp/consul-k8s#951]
#### Question

Hi team,

we want to expose our consul server inside kubernetes to public,
but we found that the ADVERTISE_IP in the helm template is just expose to pod ip / host ip, it can’t be configurable enough,

we try to add in the server.extraConfig section, but still failed to advertise it to public ip :

...
server:
  ...
  extraConfig: |
    {
      "advertise_addr": "{{ `{{` }} GetPublicIPs {{ `}}` }}",
      "bind_addr": "{{ `{{` }} GetPublicIPs {{ `}}` }}"
    }
...
is there any other way to advertise the consul server to public?, as we need to connect a public server (VPS/Baremetal/etc) to the consul server inside our EKS Cluster?

### Helm Configuration

...
server:
  ...
  extraConfig: |
    {
      "advertise_addr": "{{ `{{` }} GetPublicIPs {{ `}}` }}",
      "bind_addr": "{{ `{{` }} GetPublicIPs {{ `}}` }}"
    }
...

### Logs

- No error logs, its just indicate that the advertise ip still using private ip

```
==> Starting Consul agent...
           Version: '1.10.4'
           Node ID: 'fb739aa5-6613-d096-cf02-5856bd222b35'
         Node name: 'consul-server-0'
        Datacenter: 'global' (Segment: '<all>')
            Server: true (Bootstrap: false)
       Client Addr: [0.0.0.0] (HTTP: 8500, HTTPS: 8501, gRPC: -1, DNS: 8600)
      Cluster Addr: 10.11.53.174 (LAN: 8301, WAN: 8302)
           Encrypt: Gossip: true, TLS-Outgoing: true, TLS-Incoming: false, Auto-Encrypt-TLS: true
```

### Current understanding and Expected behavior

- the consul server use the public ip address from ` "{{ GetPublicIPs }}"`

### Environment details

values.yaml
```
fullnameOverride: consul
client:
  containerSecurityContext: {}
  enabled: false
  exposeGossipPorts: false
  extraConfig: |
    {}
  extraContainers: []
  extraEnvironmentVars: {}
  extraVolumes: []
  grpc: true
  hostNetwork: false
  nodeMeta:
    host-ip: ${HOST_IP}
    pod-name: ${HOSTNAME}
  priorityClassName: ""
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 100
  serviceAccount: {}
  snapshotAgent:
    configSecret: {}
    enabled: false
    replicas: 2
    resources:
      limits:
        cpu: 50m
        memory: 50Mi
      requests:
        cpu: 50m
        memory: 50Mi
    serviceAccount: {}
  tolerations: ""
connectInject:
  aclBindingRuleSelector: serviceaccount.name!=default
  aclInjectToken: {}
  consulNamespaces:
    consulDestinationNamespace: default
    mirroringK8S: false
    mirroringK8SPrefix: ""
  default: false
  enabled: false
  failurePolicy: Fail
  initContainer:
    resources:
      limits:
        cpu: 50m
        memory: 150Mi
      requests:
        cpu: 50m
        memory: 25Mi
  k8sAllowNamespaces:
  - '*'
  k8sDenyNamespaces: []
  logLevel: ""
  metrics:
    defaultEnableMerging: false
    defaultEnabled: '-'
    defaultMergedMetricsPort: 20100
    defaultPrometheusScrapePath: /metrics
    defaultPrometheusScrapePort: 20200
  namespaceSelector: |
    matchExpressions:
      - key: "kubernetes.io/metadata.name"
        operator: "NotIn"
        values: ["kube-system","local-path-storage"]
  overrideAuthMethodName: ""
  priorityClassName: ""
  replicas: 2
  resources:
    limits:
      cpu: 50m
      memory: 50Mi
    requests:
      cpu: 50m
      memory: 50Mi
  serviceAccount: {}
  sidecarProxy:
    resources:
      limits: {}
      requests: {}
  transparentProxy:
    defaultEnabled: true
    defaultOverwriteProbes: true
controller:
  aclToken: {}
  enabled: false
  logLevel: ""
  priorityClassName: ""
  replicas: 1
  resources:
    limits:
      cpu: 100m
      memory: 50Mi
    requests:
      cpu: 100m
      memory: 50Mi
  serviceAccount: {}
dns:
  enableRedirection: false
  enabled: false
  type: ClusterIP
externalServers:
  enabled: false
  hosts: []
  httpsPort: 8501
  useSystemRoots: false
global:
  acls:
    bootstrapToken: {}
    createReplicationToken: false
    manageSystemACLs: true
    replicationToken: {}
  adminPartitions:
    enabled: false
    name: default
    service:
      nodePort: {}
      type: LoadBalancer
  consulSidecarContainer:
    resources:
      limits:
        cpu: 20m
        memory: 50Mi
      requests:
        cpu: 20m
        memory: 25Mi
  datacenter: global
  domain: consul
  enableConsulNamespaces: false
  enablePodSecurityPolicies: false
  enabled: true
  enterpriseLicense:
    enableLicenseAutoload: true
  federation:
    createFederationSecret: false
    enabled: false
  gossipEncryption:
    autoGenerate: false
    secretKey: key
    secretName: consul-gossip-encryption-key
  image: hashicorp/consul:1.10.4
  imageEnvoy: envoyproxy/envoy-alpine:v1.18.4
  imageK8S: hashicorp/consul-k8s-control-plane:0.38.0
  imagePullSecrets: []
  logJSON: false
  logLevel: info
  metrics:
    agentMetricsRetentionTime: 1m
    enableAgentMetrics: true
    enableGatewayMetrics: true
    enabled: true
  openshift:
    enabled: false
  recursors: []
  secretsBackend:
    vault:
      ca:
        secretKey: ""
        secretName: ""
      connectCA:
        additionalConfig: |
          {}
        address: ""
        intermediatePKIPath: ""
        rootPKIPath: ""
      consulCARole: ""
      consulClientRole: ""
      consulServerRole: ""
      enabled: false
  tls:
    caCert: {}
    caKey: {}
    enableAutoEncrypt: true
    enabled: true
    httpsOnly: false
    serverAdditionalDNSSANs:
    - consul.loadtest.armada.accelbyte.io
    - consul-ui.loadtest.armada.accelbyte.io
    - consul-server
    serverAdditionalIPSANs: []
    verify: true
ingressGateways:
  defaults:
    affinity: |
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: {{ template "consul.name" . }}
                release: "{{ .Release.Name }}"
                component: ingress-gateway
            topologyKey: kubernetes.io/hostname
    consulNamespace: default
    initCopyConsulContainer:
      resources:
        limits:
          cpu: 50m
          memory: 150Mi
        requests:
          cpu: 50m
          memory: 25Mi
    priorityClassName: ""
    replicas: 2
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi
    service:
      ports:
      - nodePort: null
        port: 8080
      - nodePort: null
        port: 8443
      type: ClusterIP
    serviceAccount: {}
  enabled: false
  gateways:
  - name: ingress-gateway
meshGateway:
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: {{ template "consul.name" . }}
              release: "{{ .Release.Name }}"
              component: mesh-gateway
          topologyKey: kubernetes.io/hostname
  consulServiceName: mesh-gateway
  containerPort: 8443
  enabled: false
  hostNetwork: false
  initCopyConsulContainer:
    resources:
      limits:
        cpu: 50m
        memory: 150Mi
      requests:
        cpu: 50m
        memory: 25Mi
  initServiceInitContainer:
    resources:
      limits:
        cpu: 50m
        memory: 50Mi
      requests:
        cpu: 50m
        memory: 50Mi
  priorityClassName: ""
  replicas: 2
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi
  service:
    enabled: true
    port: 443
    type: LoadBalancer
  serviceAccount: {}
  wanAddress:
    port: 443
    source: Service
    static: ""
prometheus:
  enabled: false
server:
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: {{ template "consul.name" . }}
              release: "{{ .Release.Name }}"
              component: server
          topologyKey: kubernetes.io/hostname
  connect: true
  containerSecurityContext: {}
  disruptionBudget:
    enabled: true
  enabled: '-'
  exposeGossipAndRPCPorts: true
  extraConfig: |
    {
      "advertise_addr": "{{ `{{` }} GetPublicIP {{ `}}` }}",
      "bind_addr": "{{ `{{` }} GetPublicIP {{ `}}` }}"
    }
  extraContainers: []
  extraEnvironmentVars: {}
  extraVolumes: []
  nodeSelector: |
    consul-servers: armada-consul-servers-001
  ports:
    serflan:
      port: 8301
  priorityClassName: ""
  replicas: 3
  resources:
    limits:
      cpu: "2"
      memory: 8Gi
    requests:
      cpu: "1"
      memory: 4Gi
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 100
  serverCert: {}
  service: {}
  serviceAccount: {}
  storage: 10Gi
  storageClass: ebs-sc-gp3
  tolerations: |
    - key: "consul-servers"
      operator: "Equal"
      value: "true"
      effect: "NoExecute"
  topologySpreadConstraints: ""
  updatePartition: 0
syncCatalog:
  aclSyncToken: {}
  addK8SNamespaceSuffix: true
  consulNamespaces:
    consulDestinationNamespace: default
    mirroringK8S: false
    mirroringK8SPrefix: ""
  consulNodeName: k8s-sync
  default: true
  enabled: false
  k8sAllowNamespaces:
  - '*'
  k8sDenyNamespaces:
  - kube-system
  - kube-public
  logLevel: ""
  nodePortSyncType: ExternalFirst
  priorityClassName: ""
  resources:
    limits:
      cpu: 50m
      memory: 50Mi
    requests:
      cpu: 50m
      memory: 50Mi
  serviceAccount: {}
  syncClusterIPServices: true
  toConsul: true
  toK8S: true
terminatingGateways:
  defaults:
    affinity: |
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: {{ template "consul.name" . }}
                release: "{{ .Release.Name }}"
                component: terminating-gateway
            topologyKey: kubernetes.io/hostname
    consulNamespace: default
    extraVolumes: []
    initCopyConsulContainer:
      resources:
        limits:
          cpu: 50m
          memory: 150Mi
        requests:
          cpu: 50m
          memory: 25Mi
    priorityClassName: ""
    replicas: 2
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi
    serviceAccount: {}
  enabled: false
  gateways:
  - name: terminating-gateway
tests:
  enabled: true
ui:
  enabled: true
  ingress:
    enabled: false
    hosts: []
    ingressClassName: ""
    pathType: Prefix
    tls: []
  metrics:
    baseURL: http://prometheus-server
    enabled: '-'
    provider: prometheus
  service:
    enabled: true
    nodePort: {}
    port:
      http: 80
      https: 443
webhookCertManager: {}
```

Additionally, please provide details regarding the Kubernetes Infrastructure, as shown below:
- Kubernetes version: v1.20.7
- Cloud Provider : AWS EKS
- Networking CNI plugin in use: AWS VPC CNI

### Additional Context

We want to advertise public ip of our consul server
