### ISSUE TITLE
Consul Connect Inject failing for Pods without Services

### ISSUE THREAD

**Issue by expnch** [hashicorp/consul-k8s#962]
<!--
You've selected this issue type since you'd like to clarify your understanding about a particular area within Consul K8s. There are situations when an issue or feature request does not really classify the type of help you are requesting from the Consul K8s team. We'd like to help and engage the community through Github!
-->

#### Question

We just deployed v0.36.0 of the consul-k8s Helmchart to our cluster.  After restarting and redeploying our applications, we're seeing `Init` crashloops for any pods that don't have a corresponding Kubernetes Service defined, even though we've annotated those Pods (via the specs in their corresponding Deployments and Jobs).  What is the correct way to deploy applications that do not need/have a Service?  We do not have ACLs enabled.  Pods with Services are starting up just fine.

### Helm Configuration

1. We ran helm install with the following `values.yaml`:
```
global:
  datacenter: dc
  tls:
    enabled: true
    enableAutoEncrypt: true
  gossipEncryption:
    secretName: gossip-secret
    secretKey: key
  consulSidecarContainer:
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "150Mi"
server:
  image: consul:1.10.4
  resources:
    requests:
      memory: "200Mi"
      cpu: "300m"
    limits:
      memory: "200Mi"
      cpu: "300m"
client:
  image: consul:1.10.4
  resources:
    requests:
      memory: "250Mi"
    limits:
      memory: "250Mi"
connectInject:
  enabled: true
  default: false
  resources:
    requests:
      memory: "75Mi"
    limits:
      memory: "128Mi"
```

2. Our Deployment spec looks like:
```
apiVersion: apps/v1                                                                                                                                                                                                                                                                                                                                                         
kind: Deployment                                                                                                                                                                                                                                                                                                                                                            
metadata:                                                                                                                                                                                                                                                                                                                                                                   
  annotations:                                                                                                                                                                                                                                                                                                                                                              
    deployment.kubernetes.io/revision: "106"                                                                                                                                                                                                                                                                                                       
  labels:                                                                                                                                                                                                                                                                                                                                                                   
    app: app-a                                                                                                                                                                                                                                                                                                                                                 
    app.kubernetes.io/managed-by: Helm                                                                                                                                                                                                                                                                                                                                      
    app.kubernetes.io/name: app-a                                                                                                                                                                                                                                                                                                                            
  name: app-a                                                                                                                                                                                                                                                                                                                                                 
  namespace: a                                                                                                                                                                                                                                                                                                                                                                         
spec:                                                                                                                                                                                                                                                                                                                                                                       
  progressDeadlineSeconds: 600                                                                                                                                                                                                                                                                                                                                              
  replicas: 1                                                                                                                                                                                                                                                                                                                                                 
  selector:                                                                                                                                                                                                                                                                                                                                                                 
    matchLabels:                                                                                                                                                                                                                                                                                                                                                            
      app.kubernetes.io/name: app-a                                                                                                                                                                                                                                                                                                                           
  strategy:
    rollingUpdate:
      maxSurge: 25%                                                                                                                                                                                                                                                                                                                                                         
      maxUnavailable: 25%                                                                                                                                                                                                                                                                                                                                                   
    type: RollingUpdate                                                                                                                                                                                                                                                                                                                                                     
  template:                                                                                                                                                                                                                                                                                                                                                                 
    metadata:                                                                                                                                                                                                                                                                                                                                                               
      annotations:                                                                                                                                                                                                                                                                                                                                                          
        consul.hashicorp.com/connect-inject: "true"                                                                                                                                                                                                                                                                                                                         
        consul.hashicorp.com/connect-service: app-a                                                                                                                                                                                                                                                                                                          
        consul.hashicorp.com/connect-service-upstreams: app-b                                                                                                                                                                                                                                                                                                  
        consul.hashicorp.com/transparent-proxy: "false"                                                                                                                                                                                                                                                                                                                     
      labels:                                                                                                                                                                                                                                                                                                                                                               
        app.kubernetes.io/name: app-a
  spec:                                                                                                                                                                                                                                                                                                                                                                   
      containers:                                                                                                                                                                                                                                                                                                                                                           
      - env:                                                                                                                                                                                                                                                                                                                                                                
        - name: SERVICE_NAME                                                                                                                                                                                                                                                                                                                                                
          valueFrom:                                                                                                                                                                                                                                                                                                                                                        
            fieldRef:                                                                                                                                                                                                                                                                                                                                                       
              apiVersion: v1                                                                                                                                                                                                                                                                                                                                                
              fieldPath: metadata.name                                                                                                                                                                                                                                                                                                                                      
        image: app-a:latest
        imagePullPolicy: IfNotPresent
        name: app-a
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          failureThreshold: 3
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "4"
            memory: 5G
          requests:
            cpu: "3"
            memory: 4G
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: app-a-sa
      serviceAccountName: app-a-sa
      terminationGracePeriodSeconds: 30
```

### Logs
<details>
  <summary>Logs from app-a `consul-connect-inject-init` container</summary>

```
2022-01-11T23:16:07.749Z [INFO]  Unable to find registered services; retrying
2022-01-11T23:16:08.750Z [INFO]  Unable to find registered services; retrying
2022-01-11T23:16:09.751Z [INFO]  Unable to find registered services; retrying
2022-01-11T23:16:10.752Z [INFO]  Unable to find registered services; retrying
2022-01-11T23:16:11.753Z [INFO]  Unable to find registered services; retrying
2022-01-11T23:16:12.754Z [INFO]  Unable to find registered services; retrying
2022-01-11T23:16:13.755Z [INFO]  Unable to find registered services; retrying
2022-01-11T23:16:14.755Z [INFO]  Unable to find registered services; retrying
2022-01-11T23:16:15.756Z [INFO]  Unable to find registered services; retrying
2022-01-11T23:16:16.757Z [INFO]  Unable to find registered services; retrying
2022-01-11T23:16:16.757Z [INFO]  Check to ensure a Kubernetes service has been created for this application. If your pod is not starting also check the connect-inject deployment logs.
```

</details>
