### ISSUE TITLE
Not able to expose harshicorp consul through istio-ingress gateway

### ISSUE THREAD

**Issue by raonelakurti** [hashicorp/consul-k8s#972]
#### Question

I'm trying to make use of consul KV store on k8s cluster and expose through istio-ingress gateway. 
What are my options? 
How can I pass a rootpath prefix to consul and expose the consul-ui through istio-ingressgateway?

installation command:
```
helm install -f  consul-values.yaml  --name consul hashicorp/consul --version "0.23.1" --namespace consul --wait
```

1. When running helm install with the following `values.yaml`:
```
global:
  name: consul
  enabled: true
  datacenter: dc1
  gossipEncryption:
    secretName: "consul-gossip-encryption-key"
    secretKey: "key"
  acls:
    manageSystemACLs: true
  
server:
  storage: 50Gi
  replicas: 3
  bootstrapExpect: 3
ui:
  enabled: true
connectInject:
  enabled: true
controller:
  enabled: true
```
@ishustava Could you please help me.
