### ISSUE TITLE
consul-server pods stuck in pending state when exposeGossipAndRPCPorts is set to true

### ISSUE THREAD

**Issue by liad5h** [hashicorp/consul-k8s#980]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

I am running consul on aws eks v1.18.20-eks-c9f1ce and chart version 0.39.0.
When I set server.exposeGossipAndRPCPorts to `true`, the consul-server pods are stuck in pending state with the following error:

```
Events:
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Warning  FailedScheduling  29s (x10 over 8m29s)  default-scheduler  0/3 nodes are available: 3 node(s) didn't have free ports for the requested pod ports.
```

As long as exposeGossipAndRPCPorts is set to `false`, everything works.

### Reproduction Steps

1. create an EKS cluster
2. create helm values file:
```
client:
  enabled: false

global:
  datacenter: "eu-central-1"
  gossipEncryption:
    secretName: "consul-gossip-encryption-key"
    secretKey: "key"
  tls:
    enabled: false
  acls:
    manageSystemACLs: true
  metrics:
    enabled: true
    enableAgentMetrics: true

server:
  enabled: true
  #exposeGossipAndRPCPorts: true
  ports:
    serflan:
        port: 9301

ui:
  service:
    port:
      http: 8500
    type: "LoadBalancer"
    annotations: |
      "external-dns.alpha.kubernetes.io/hostname": "consul.x.com"
      "service.beta.kubernetes.io/aws-load-balancer-backend-protocol": "http"
      "service.beta.kubernetes.io/aws-load-balancer-scheme": "internal"
      "service.beta.kubernetes.io/aws-load-balancer-ip-address-type": "ipv4"
      "service.beta.kubernetes.io/load-balancer-source-ranges": "x.x.x.x/24"
      "service.beta.kubernetes.io/aws-load-balancer-internal": "true"
      "service.beta.kubernetes.io/aws-load-balancer-type": "nlb-ip"
```
3. deploy consul
```
helm install consul hashicorp/consul --version 0.39.0 --namespace consul --set global.name=consul -f /tmp/helm-values.yaml
```

### Logs

ports from `kubectl describe pod`: 
```
    Ports:       8500/TCP, 9301/TCP, 9301/UDP, 8302/TCP, 8302/UDP, 8300/TCP, 8600/TCP, 8600/UDP
    Host Ports:  0/TCP, 9301/TCP, 9301/UDP, 8302/TCP, 8302/UDP, 8300/TCP, 0/TCP, 0/UDP
```

### Expected behavior

pods will reach the running state and gossip ports will be exposed so external clients can connect to the datacenter.
