### ISSUE TITLE
I tried envoy.tracers.skywalking tracer，No span data created by envoy was found in skywalking . Because it is mentioned in the envoy document that the start in the router must be start_child_span set to true to get the correct topology and tracking data. I was wondering if there's a way to configure the start child span options .Can you provide a demo? I'm not sure. does consul currently support the combination of skywalking ?Thank you!

### ISSUE THREAD

**Issue by berylshow** [hashicorp/consul-k8s#992]
###   consul-helm 0.30.0
```yaml
 image: "hashicorp/consul:1.10.0"
  imageK8S: "hashicorp/consul-k8s:0.24.0"
  imageEnvoy: "envoyproxy/envoy-alpine:v1.18.2"
```

```yaml
### ProxyDefaults.yaml
apiVersion: consul.hashicorp.com/v1alpha1
kind: ProxyDefaults
metadata:
  name: global
spec:
  config:
    protocol: http
    envoy_tracing_json: |
        {
            "http": {
                "name": "envoy.tracers.skywalking",
                "typedConfig": {
                    "@type": "type.googleapis.com/envoy.config.trace.v3.SkyWalkingConfig",
                    "grpc_service": {
                        "envoy_grpc": {
                            "cluster_name": "collector_cluster_name"
                        },
                        "timeout": "10s"
                    }
                }
            }
        }
    envoy_extra_static_clusters_json: |
        {
            "name": "collector_cluster_name",
            "connect_timeout": "1s",
            "type": "strict_dns",
            "lb_policy": "round_robin",
            "http2_protocol_options": {},
            "load_assignment": {
                "cluster_name": "collector_cluster_name",
                "endpoints": [{
                    "lb_endpoints": [{
                        "endpoint": {
                            "address": {
                                "socket_address": {
                                    "address": "skywalkingdev-oap.es",
                                    "port_value": 11800
                                }
                            }
                        }
                    }]
                }]
            }
        }
```

### Additional Context
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/trace/v3/skywalking.proto#config-trace-v3-skywalkingconfig
https://www.consul.io/docs/connect/distributed-tracing#considerations
hashicorp/consul#6645
